#!/usr/bin/env bash

# Create dist folder and copy everything into it
if [[ -d "dist" ]]; then
  rm -rf dist
fi

mkdir dist

# Copy only the relevant files into our dist folder
cp -r css \
  html \
  image_assets \
  js \
  manifest.json \
  popup.js \
  dist

# Zip it up
cd dist
zip -r extension.zip ./*
find . -not -name "extension.zip" -delete
