
export const MessageTypes = {
  BASIC_DATA_REQUEST: 'BASIC_DATA_REQUEST',
  BASIC_DATA_RESPONSE: 'BASIC_DATA_RESPONSE',
  CONTENTS_REQUEST: 'CONTENTS_REQUEST',
  CONTENTS_RESPONSE: 'CONTENTS_RESPONSE',
  INSTRUCTIONS_REQUEST: 'INSTRUCTIONS_REQUEST',
  INSTRUCTIONS_RESPONSE: 'INSTRUCTIONS_RESPONSE',
  UPDATE_PREFERENCES_REQUEST: 'UPDATE_PREFERENCES_REQUEST',
  UPDATE_PREFERENCES_RESPONSE: 'UPDATE_PREFERENCES_RESPONSE',
  CONTROL_ICON_CLICK: 'CONTROL_ICON_CLICK',
  EMPTY_RESPONSE: 'EMPTY_RESPONSE',
  POPUP_BOX_OPEN: 'POPUP_BOX_OPEN',
  SERP_REQUEST: 'SERP_REQUEST',
  SERP_RESPONSE: 'SERP_RESPONSE',
  FEED_META_REQUEST: 'FEED_REQUEST',
  FEED_META_RESPONSE: 'FEED_RESPONSE',
  MANIFEST_REQUEST: 'MANIFEST_REQUEST',
  MANIFEST_RESPONSE: 'MANIFEST_RESPONSE',
  RESTORE_EXTENSION: 'RESTORE_EXTENSION',
  BLACKLIST_URL: 'BLACK_LIST_URL',
  BLACKLIST_REMOVE_URL: 'BLACKLIST_REMOVE_URL',
  DOMAIN_PREFERENCES: 'DOMAIN_PREFERENCES',
  DOMAIN_PREFERENCE_REMOVED: 'DOMAIN_PREFERENCE_REMOVED',
  REFRESH_FEED_REQUEST: 'REFRESH_FEED_REQUEST',
  REFRESH_FEED_RESPONSE: 'REFRESH_FEED_RESPONSE',
}

export const ContentTypes = {
  CONTENT_BOX: 'content_box',
  POPUP_CONTENT: 'popup_content',
  POPUP_SEARCH: 'popup_search',
  POPUP_DISABLED: 'popup_disabled',
};


export const ModelTypes = {
  FEED: 'feed',
  PAGE: 'page',
  SERP: 'serp',
  USER: 'user',
  PREFERENCES: 'preferences',
  SEARCH: 'search',
  ADDON: 'addon',
  REWARD: 'reward',
}

/**
 * @typedef {string} SerpType
 * @enum {SerpType}
 */
export const SerpTypes = {
  GOOGLE: 'google',
  ZBOZI: 'zbozi',
  HEUREKA: 'heureka',
  SEZNAM: 'seznam',
}

export const ControlIconTypes = {
  CLOSE: 'close',
  HIDE: 'hide',
}

export const DomainMatchTypes = {
  STARTS_WITH: 'startsWith',
  DOMAIN_CONTAINS: 'domainContains',
}