// MARK: - Desktop Groups

const facebookDesktopGroups_DisableSocialFocus = {
  type: "checkbox",
  name: {
    ar: "تعطيل التركيز الاجتماعي على الفيسبوك",
    ca: "Desactiveu SocialFocus a Facebook",
    "zh-CN": "在 Facebook 上禁用 SocialFocus",
    "zh-TW": "在 Facebook 上停用 SocialFocus",
    hr: "Onemogućite SocialFocus na Facebooku",
    cs: "Zakázat SocialFocus na Facebooku",
    da: "Deaktiver SocialFocus på Facebook",
    nl: "Schakel SocialFocus uit op Facebook",
    en: "Disable SocialFocus on Facebook",
    fi: "Poista SocialFocus käytöstä Facebookissa",
    fr: "Désactivez SocialFocus sur Facebook",
    de: "Deaktivieren Sie SocialFocus auf Facebook",
    el: "Απενεργοποιήστε το SocialFocus στο Facebook",
    he: "השבת את SocialFocus בפייסבוק",
    hi: "फेसबुक पर सोशलफोकस अक्षम करें",
    hu: "A SocialFocus letiltása a Facebookon",
    id: "Nonaktifkan Fokus Sosial di Facebook",
    it: "Disattiva SocialFocus su Facebook",
    ja: "Facebook で SocialFocus を無効にする",
    ko: "Facebook에서 SocialFocus 비활성화",
    ms: "Lumpuhkan SocialFocus pada Facebook",
    no: "Deaktiver SocialFocus på Facebook",
    pl: "Wyłącz SocialFocus na Facebooku",
    pt: "Desative o SocialFocus no Facebook",
    ro: "Dezactivează SocialFocus pe Facebook",
    ru: "Отключить SocialFocus на Facebook",
    sk: "Zakázať SocialFocus na Facebooku",
    es: "Deshabilitar SocialFocus en Facebook",
    sv: "Inaktivera SocialFocus på Facebook",
    th: "ปิดการใช้งาน SocialFocus บน Facebook",
    tr: "Facebook'ta SocialFocus'u devre dışı bırakın",
    uk: "Вимкніть SocialFocus у Facebook",
    vi: "Tắt SocialFocus trên Facebook",
  },
  id: "socialFocus_facebook_master_toggle",
  defaultValue: false,
};

const facebookDesktopGroups_Essentials = [
  {
    type: "checkbox",
    name: {
      ar: "حظر الفيسبوك",
      ca: "Bloqueja Facebook",
      "zh-CN": "封锁脸书",
      "zh-TW": "封鎖臉書",
      hr: "Blokiraj Facebook",
      cs: "Blokovat Facebook",
      da: "Bloker Facebook",
      nl: "Blokkeer Facebook",
      en: "Block Facebook",
      fi: "Estä Facebook",
      fr: "Bloquer Facebook",
      de: "Facebook blockieren",
      el: "Αποκλεισμός του Facebook",
      he: "חסום את פייסבוק",
      hi: "फेसबुक को ब्लॉक करें",
      hu: "Facebook letiltása",
      id: "Blokir Facebook",
      it: "Blocca Facebook",
      ja: "Facebookをブロックする",
      ko: "페이스북 차단",
      ms: "Sekat Facebook",
      no: "Blokker Facebook",
      pl: "Zablokuj Facebooka",
      pt: "Bloquear Facebook",
      ro: "Blocați Facebook",
      ru: "Блокировать Facebook",
      sk: "Blokovať Facebook",
      es: "Bloquear facebook",
      sv: "Blockera Facebook",
      th: "บล็อกเฟสบุ๊ค",
      tr: "Facebook'u engelle",
      uk: "Заблокувати Facebook",
      vi: "Chặn Facebook",
    },
    id: "socialFocus_facebook_block_facebook",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "الوضع الرمادي",
      ca: "Mode gris",
      "zh-CN": "灰度模式",
      "zh-TW": "灰階模式",
      hr: "Sivi način rada",
      cs: "Šedý režim",
      da: "Grå tilstand",
      nl: "Grijze modus",
      en: "Gray Mode",
      fi: "Harmaa tila",
      fr: "Mode gris",
      de: "Graumodus",
      el: "Γκρι λειτουργία",
      he: "מצב אפור",
      hi: "ग्रे मोड",
      hu: "Szürke mód",
      id: "Modus Abu-abu",
      it: "Modalità grigia",
      ja: "グレーモード",
      ko: "그레이 모드",
      ms: "Mod Kelabu",
      no: "Grå modus",
      pl: "Tryb szary",
      pt: "Modo cinza",
      ro: "Modul gri",
      ru: "Серый режим",
      sk: "Šedý režim",
      es: "Modo gris",
      sv: "Grått läge",
      th: "โหมดสีเทา",
      tr: "Gri Mod",
      uk: "Сірий режим",
      vi: "Chế độ màu xám",
    },
    id: "socialFocus_facebook_gray_mode",
    defaultValue: false,
  },
];

const facebookDesktopGroups_TimeLimit = [
  {
    type: "select",
    name: {
      ar: "الحد اليومي",
      ca: "Límit diari",
      "zh-CN": "每日限额",
      "zh-TW": "每日限額",
      hr: "Dnevni limit",
      cs: "Denní limit",
      da: "Daglig grænse",
      nl: "Dagelijkse limiet",
      en: "Daily Limit",
      fi: "Päivittäinen raja",
      fr: "Limite quotidienne",
      de: "Tageslimit",
      el: "Ημερήσιο Όριο",
      he: "מגבלה יומית",
      hi: "दैनिक सीमा",
      hu: "Napi limit",
      id: "Batas Harian",
      it: "Limite giornaliero",
      ja: "1日あたりの制限",
      ko: "일일 한도",
      ms: "Had Harian",
      no: "Daglig grense",
      pl: "Limit dzienny",
      pt: "Limite Diário",
      ro: "Limită zilnică",
      ru: "Дневной лимит",
      sk: "Denný limit",
      es: "Límite diario",
      sv: "Daglig gräns",
      th: "ขีดจำกัดรายวัน",
      tr: "Günlük Limit",
      uk: "Денний ліміт",
      vi: "Giới hạn hàng ngày",
    },
    id: "socialFocus_daily_limit",
    defaultValue: "noLimit",
    selects: [
      {
        name: {
          ar: "بلا حدود",
          ca: "Sense límits",
          "zh-CN": "没有限制",
          "zh-TW": "沒有限制",
          hr: "Bez ograničenja",
          cs: "Bez omezení",
          da: "Ingen grænser",
          nl: "Geen grenzen",
          en: "No Limits",
          fi: "Ei rajoja",
          fr: "Aucune limite",
          de: "Keine Grenzen",
          el: "Χωρίς όρια",
          he: "ללא גבולות",
          hi: "असीम",
          hu: "Nincs határ",
          id: "Tanpa Batas",
          it: "Nessun limite",
          ja: "制限なし",
          ko: "한계 없음",
          ms: "Tiada Had",
          no: "Ingen grenser",
          pl: "Bez ograniczeń",
          pt: "Sem Limites",
          ro: "Fără limite",
          ru: "Без ограничений",
          sk: "Žiadne limity",
          es: "Sin límites",
          sv: "Inga gränser",
          th: "ไม่มีขีดจำกัด",
          tr: "Sınır Yok",
          uk: "Без обмежень",
          vi: "Không có giới hạn",
        },
        id: "noLimit",
      },
    ],
  },
  {
    type: "checkbox",
    name: {
      ar: "عرض الموقت على الموقع",
      ca: "Mostra el temporitzador al lloc",
      "zh-CN": "现场显示计时器",
      "zh-TW": "現場顯示計時器",
      hr: "Prikaz mjerača vremena na licu mjesta",
      cs: "Zobrazit časovač na místě",
      da: "Vis timer på stedet",
      nl: "Timer op locatie weergeven",
      en: "Display Timer On Site",
      fi: "Näytä ajastin paikan päällä",
      fr: "Afficher la minuterie sur site",
      de: "Timer vor Ort anzeigen",
      el: "Εμφάνιση χρονοδιακόπτη στον ιστότοπο",
      he: "הצגת טיימר באתר",
      hi: "साइट पर टाइमर प्रदर्शित करें",
      hu: "Időzítő megjelenítése a helyszínen",
      id: "Tampilkan Timer Di Situs",
      it: "Visualizza il timer sul sito",
      ja: "オンサイトでタイマーを表示",
      ko: "사이트에 타이머 표시",
      ms: "Paparkan Pemasa Di Tapak",
      no: "Vis timer på stedet",
      pl: "Wyświetl timer na miejscu",
      pt: "Exibir temporizador no local",
      ro: "Afișează cronometrul la fața locului",
      ru: "Отображение таймера на месте",
      sk: "Zobraziť časovač na mieste",
      es: "Mostrar temporizador en el sitio",
      sv: "Visa timer på plats",
      th: "แสดงตัวจับเวลาบนเว็บไซต์",
      tr: "Zamanlayıcıyı Sitede Görüntüle",
      uk: "Відображення таймера на сайті",
      vi: "Hiển thị bộ đếm thời gian trên trang web",
    },
    id: "socialFocus_facebook_daily_limit_show_timer_draggable",
    defaultValue: false,
  },
];

const facebookDesktopGroups_Feed = [
  {
    type: "checkbox",
    name: {
      ar: "إخفاء موجز الصفحة الرئيسية",
      ca: "Amaga el feed d'inici",
      "zh-CN": "隐藏主页动态",
      "zh-TW": "隱藏主頁動態",
      hr: "Sakrij početnu stranicu",
      cs: "Skrýt domovský kanál",
      da: "Skjul hjemmefeed",
      nl: "Homefeed verbergen",
      en: "Hide Home Feed",
      fi: "Piilota kotisyöte",
      fr: "Masquer le flux d’accueil",
      de: "Home-Feed ausblenden",
      el: "Απόκρυψη αρχικής ροής",
      he: "הסתר עדכון ביתי",
      hi: "होम फ़ीड छिपाएँ",
      hu: "Home Feed elrejtése",
      id: "Sembunyikan Umpan Beranda",
      it: "Nascondi feed domestico",
      ja: "ホームフィードを隠す",
      ko: "홈 피드 숨기기",
      ms: "Sembunyikan Suapan Rumah",
      no: "Skjul hjemmefeed",
      pl: "Ukryj kanał główny",
      pt: "Ocultar feed inicial",
      ro: "Ascunde fluxul de acasă",
      ru: "Скрыть главную ленту",
      sk: "Skryť domovský kanál",
      es: "Ocultar feed de inicio",
      sv: "Dölj hemflöde",
      th: "ซ่อนฟีดหน้าแรก",
      tr: "Ana Sayfa Akışını Gizle",
      uk: "Приховати домашню стрічку",
      vi: "Ẩn nguồn cấp dữ liệu trang chủ",
    },
    id: "socialFocus_facebook_feed_hide_home_feed",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء قسم 'القصص'",
      ca: "Amaga la secció 'Històries'",
      "zh-CN": "隐藏“故事”部分",
      "zh-TW": "隱藏「故事」部分",
      hr: "Sakrij odjeljak 'Priče'",
      cs: "Skrýt sekci „Příběhy“",
      da: "Skjul afsnittet 'Historier'",
      nl: "Sectie 'Verhalen' verbergen",
      en: "Hide 'Stories' Section",
      fi: "Piilota Tarinat-osio",
      fr: "Masquer la section « Histoires »",
      de: "Abschnitt „Geschichten“ ausblenden",
      el: "Απόκρυψη ενότητας 'Ιστορίες'",
      he: "הסתר מדור 'סיפורים'",
      hi: "'कहानियाँ' अनुभाग छिपाएँ",
      hu: "A „Történetek” szakasz elrejtése",
      id: "Sembunyikan Bagian 'Cerita'",
      it: "Nascondi la sezione 'Storie'",
      ja: "「ストーリー」セクションを非表示にする",
      ko: "'스토리' 섹션 숨기기",
      ms: "Sembunyikan Bahagian 'Cerita'",
      no: "Skjul 'Stories'-delen",
      pl: "Ukryj sekcję „Historie”",
      pt: "Ocultar seção 'Histórias'",
      ro: "Ascundeți secțiunea „Povestiri”",
      ru: "Скрыть раздел «Истории»",
      sk: "Skryť sekciu „Príbehy“",
      es: "Ocultar la sección 'Historias'",
      sv: "Göm avsnittet 'Berättelser'",
      th: "ซ่อนส่วน 'เรื่องราว'",
      tr: "'Hikayeler' Bölümünü Gizle",
      uk: "Сховати розділ «Історії»",
      vi: "Ẩn phần 'Truyện'",
    },
    id: "socialFocus_facebook_feed_hide_section_stories",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء المشاركات الدعائية",
      ca: "Amaga les publicacions patrocinades",
      "zh-CN": "隐藏赞助帖子",
      "zh-TW": "隱藏贊助貼文",
      hr: "Sakrij sponzorirane postove",
      cs: "Skrýt sponzorované příspěvky",
      da: "Skjul sponsorerede indlæg",
      nl: "Gesponsorde berichten verbergen",
      en: "Hide Sponsored Posts",
      fi: "Piilota sponsoroidut viestit",
      fr: "Masquer les publications sponsorisées",
      de: "Gesponserte Beiträge ausblenden",
      el: "Απόκρυψη διαφημιζόμενων αναρτήσεων",
      he: "הסתר פוסטים ממומנים",
      hi: "प्रायोजित पोस्ट छिपाएँ",
      hu: "Szponzorált bejegyzések elrejtése",
      id: "Sembunyikan Postingan Bersponsor",
      it: "Nascondi post sponsorizzati",
      ja: "スポンサー付きの投稿を非表示にする",
      ko: "스폰서 게시물 숨기기",
      ms: "Sembunyikan Catatan Tajaan",
      no: "Skjul sponsede innlegg",
      pl: "Ukryj posty sponsorowane",
      pt: "Ocultar postagens patrocinadas",
      ro: "Ascundeți postările sponsorizate",
      ru: "Скрыть рекламные сообщения",
      sk: "Skryť sponzorované príspevky",
      es: "Ocultar publicaciones patrocinadas",
      sv: "Dölj sponsrade inlägg",
      th: "ซ่อนโพสต์ที่ได้รับการสนับสนุน",
      tr: "Sponsorlu Gönderileri Gizle",
      uk: "Приховати спонсоровані публікації",
      vi: "Ẩn bài viết được tài trợ",
    },
    id: "socialFocus_facebook_feed_hide_sponsored_posts",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء المشاركات من المجموعات",
      ca: "Amaga les publicacions dels grups",
      "zh-CN": "隐藏群组中的帖子",
      "zh-TW": "隱藏群組中的貼文",
      hr: "Sakrij postove iz grupa",
      cs: "Skrýt příspěvky ze skupin",
      da: "Skjul indlæg fra grupper",
      nl: "Berichten uit groepen verbergen",
      en: "Hide Posts from Groups",
      fi: "Piilota viestit ryhmistä",
      fr: "Masquer les publications des groupes",
      de: "Beiträge aus Gruppen ausblenden",
      el: "Απόκρυψη αναρτήσεων από ομάδες",
      he: "הסתר פוסטים מקבוצות",
      hi: "समूहों से पोस्ट छिपाएँ",
      hu: "Bejegyzések elrejtése a Csoportokból",
      id: "Sembunyikan Postingan dari Grup",
      it: "Nascondi post dai gruppi",
      ja: "グループからの投稿を非表示にする",
      ko: "그룹에서 게시물 숨기기",
      ms: "Sembunyikan Siaran daripada Kumpulan",
      no: "Skjul innlegg fra grupper",
      pl: "Ukryj posty w grupach",
      pt: "Ocultar postagens de grupos",
      ro: "Ascundeți postările din grupuri",
      ru: "Скрыть сообщения из групп",
      sk: "Skryť príspevky zo skupín",
      es: "Ocultar publicaciones de grupos",
      sv: "Dölj inlägg från grupper",
      th: "ซ่อนโพสต์จากกลุ่ม",
      tr: "Gruplardaki Gönderileri Gizle",
      uk: "Приховати публікації з груп",
      vi: "Ẩn bài viết khỏi nhóm",
    },
    id: "socialFocus_facebook_feed_hide_group_posts",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء المشاركات من الأشخاص لمتابعتهم",
      ca: "Amaga les publicacions de les persones per seguir",
      "zh-CN": "隐藏要关注的人的帖子",
      "zh-TW": "隱藏要關注的人的帖子",
      hr: "Sakrij postove od osoba za praćenje",
      cs: "Skrýt příspěvky od lidí ke sledování",
      da: "Skjul indlæg fra personer at følge",
      nl: "Verberg berichten van mensen die u wilt volgen",
      en: "Hide Posts from People to Follow",
      fi: "Piilota viestit seurattavilta ihmisiltä",
      fr: "Masquer les publications des personnes à suivre",
      de: "Verstecken Sie Beiträge von Personen, denen Sie folgen möchten",
      el: "Απόκρυψη αναρτήσεων από άτομα προς παρακολούθηση",
      he: "הסתר פוסטים מאנשים לעקוב אחריהם",
      hi: "फ़ॉलो करने के लिए लोगों से पोस्ट छुपाएं",
      hu: "Bejegyzések elrejtése a követendő személyek közül",
      id: "Sembunyikan Postingan dari Orang untuk Diikuti",
      it: "Nascondi i post alle persone da seguire",
      ja: "フォローするユーザーの投稿を非表示にする",
      ko: "팔로우할 사람들의 게시물 숨기기",
      ms: "Sembunyikan Siaran daripada Orang untuk Diikuti",
      no: "Skjul innlegg fra personer å følge",
      pl: "Ukryj posty przed osobami, które chcesz obserwować",
      pt: "Ocultar postagens de pessoas para seguir",
      ro: "Ascunde postările de la persoanele de urmărit",
      ru: "Скрыть сообщения от людей, на которых можно подписаться",
      sk: "Skryť príspevky od ľudí na sledovanie",
      es: "Ocultar publicaciones de personas a seguir",
      sv: "Dölj inlägg från personer att följa",
      th: "ซ่อนโพสต์จากบุคคลที่จะติดตาม",
      tr: "Takip Edilecek Kişilerden Gönderileri Gizle",
      uk: "Приховайте публікації від людей, на яких слід стежити",
      vi: "Ẩn bài viết khỏi những người để theo dõi",
    },
    id: "socialFocus_facebook_feed_hide_posts_from_people_to_follow",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء قسم 'أشخاص قد تعرفهم'",
      ca: "Amaga la secció 'Persones que potser coneixeu'",
      "zh-CN": "隐藏“您可能认识的人”部分",
      "zh-TW": "隱藏「您可能認識的人」部分",
      hr: "Sakrij odjeljak 'Osobe koje možda poznaješ'",
      cs: "Skryjte sekci „Lidé, které možná znáte“",
      da: "Skjul sektionen 'Personer, du måske kender'",
      nl: "Sectie 'Mensen die u mogelijk kent' verbergen",
      en: "Hide 'People you may know' Section",
      fi: "Piilota 'Ihmiset, jotka saatat tuntea' -osio",
      fr: "Masquer la section « Personnes que vous connaissez peut-être »",
      de: "Abschnitt „Personen, die Sie vielleicht kennen“ ausblenden",
      el: "Απόκρυψη της ενότητας 'Άτομα που μπορεί να γνωρίζετε'",
      he: "הסתר את הקטע 'אנשים שאתה עשוי להכיר'",
      hi: "'वे लोग जिन्हें आप जानते हों' अनुभाग छिपाएँ",
      hu: "Az 'Emberek, akiket ismerhet' szakasz elrejtése",
      id: "Sembunyikan Bagian 'Orang yang mungkin Anda kenal'",
      it: "Nascondi la sezione 'Persone che potresti conoscere'",
      ja: "「知り合いかも知れません」セクションを非表示にする",
      ko: "'알 수도 있는 사람' 섹션 숨기기",
      ms: "Sembunyikan Bahagian 'Orang yang mungkin anda kenali'",
      no: "Skjul delen 'Folk du kanskje kjenner'",
      pl: "Ukryj sekcję „Osoby, które możesz znać”",
      pt: "Ocultar a seção 'Pessoas que você talvez conheça'",
      ro: "Ascundeți secțiunea „Persoane pe care poate le cunoașteți”",
      ru: "Скрыть раздел «Люди, которых вы можете знать»",
      sk: "Skryť sekciu „Ľudia, ktorých možno poznáte“",
      es: "Ocultar la sección 'Personas que quizás conozcas'",
      sv: "Dölj avsnittet 'Personer du kanske känner'",
      th: "ซ่อนส่วน 'บุคคลที่คุณอาจรู้จัก'",
      tr: "'Tanıyor olabileceğiniz kişiler' Bölümünü gizle",
      uk: "Сховати розділ «Люди, яких ви можете знати»",
      vi: "Ẩn phần 'Những người bạn có thể biết'",
    },
    id: "socialFocus_facebook_feed_hide_section_people_you_may_know",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء قسم 'البكرات ومقاطع الفيديو القصيرة'",
      ca: "Amaga la secció 'Reels i vídeos curts'",
      "zh-CN": "隐藏“卷轴和短视频”部分",
      "zh-TW": "隱藏“捲軸和短視頻”部分",
      hr: "Sakrij odjeljak 'Releji i kratki videozapisi'",
      cs: "Skryjte sekci 'Civky a krátká videa'",
      da: "Skjul sektionen 'Hjuler og korte videoer'",
      nl: "Sectie 'Reels en korte video's' verbergen",
      en: "Hide 'Reels and short videos' Section",
      fi: "Piilota Kelat ja lyhyet videot -osio",
      fr: "Masquer la section « Bobines et courtes vidéos »",
      de: "Abschnitt „Reels und kurze Videos“ ausblenden",
      el: "Απόκρυψη ενότητας 'Κολί και σύντομα βίντεο'",
      he: "הסתר את הקטע 'סלילים וסרטונים קצרים'",
      hi: "'रील और लघु वीडियो' अनुभाग छिपाएँ",
      hu: "A „Tekercsek és rövid videók” szakasz elrejtése",
      id: "Sembunyikan Bagian 'Gulungan dan video pendek'",
      it: "Nascondi la sezione 'Reels e brevi video'",
      ja: "「リールとショートビデオ」セクションを非表示にする",
      ko: "'릴 및 짧은 동영상' 섹션 숨기기",
      ms: "Sembunyikan Bahagian 'Kekili dan video pendek'",
      no: "Skjul delen 'Sneller og korte videoer'",
      pl: "Ukryj sekcję „Reklamy i krótkie filmy”",
      pt: "Ocultar a seção 'Momentos e vídeos curtos'",
      ro: "Ascundeți secțiunea „Role și videoclipuri scurte”",
      ru: "Скрыть раздел «Ролики и короткие видеоролики»",
      sk: "Skryť sekciu „Modely a krátke videá“",
      es: "Ocultar Sección 'Reels y vídeos cortos'",
      sv: "Göm sektionen 'Reels och korta videor'",
      th: "ซ่อนส่วน 'คลิปม้วนและวิดีโอสั้น'",
      tr: "'Makaralar ve kısa videolar' Bölümünü gizle",
      uk: "Сховати розділ «Котушки та короткі відео»",
      vi: "Ẩn phần 'Câu chuyện và video ngắn'",
    },
    id: "socialFocus_facebook_feed_hide_section_reels_and_short_videos",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء قسم 'المجموعات المقترحة'",
      ca: "Amaga la secció 'Grups suggerits'",
      "zh-CN": "隐藏“建议的组”部分",
      "zh-TW": "隱藏「建議的群組」部分",
      hr: "Sakrij odjeljak 'Predložene grupe'",
      cs: "Skrýt sekci „Navrhované skupiny“",
      da: "Skjul sektionen 'Foreslåede grupper'",
      nl: "Sectie 'Voorgestelde groepen' verbergen",
      en: "Hide 'Suggested Groups' Section",
      fi: "Piilota Ehdotetut ryhmät -osio",
      fr: "Masquer la section « Groupes suggérés »",
      de: "Abschnitt „Vorgeschlagene Gruppen“ ausblenden",
      el: "Απόκρυψη ενότητας 'Προτεινόμενες ομάδες'",
      he: "הסתר את הקטע 'קבוצות מוצעות'",
      hi: "'सुझाए गए समूह' अनुभाग छिपाएँ",
      hu: "A „Javasolt csoportok” szakasz elrejtése",
      id: "Sembunyikan Bagian 'Grup yang Disarankan'",
      it: "Nascondi la sezione 'Gruppi suggeriti'",
      ja: "「推奨グループ」セクションを非表示にする",
      ko: "'추천 그룹' 섹션 숨기기",
      ms: "Sembunyikan Bahagian 'Kumpulan Cadangan'",
      no: "Skjul delen 'Foreslåtte grupper'",
      pl: "Ukryj sekcję „Sugerowane grupy”",
      pt: "Ocultar a seção 'Grupos sugeridos'",
      ro: "Ascundeți secțiunea „Grupuri sugerate”",
      ru: "Скрыть раздел «Предлагаемые группы»",
      sk: "Skryť sekciu „Navrhované skupiny“",
      es: "Ocultar la sección 'Grupos sugeridos'",
      sv: "Dölj avsnittet 'Föreslagna grupper'",
      th: "ซ่อนส่วน 'กลุ่มที่แนะนำ'",
      tr: "'Önerilen Gruplar' Bölümünü Gizle",
      uk: "Сховати розділ «Пропоновані групи»",
      vi: "Ẩn phần 'Nhóm được đề xuất'",
    },
    id: "socialFocus_facebook_feed_hide_suggested_groups",
    defaultValue: false,
  },
];

// MARK: Header

const facebookDesktopGroups_Header = [
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'الأصدقاء'",
      ca: "Amaga el botó 'Amics'",
      "zh-CN": "隐藏“好友”按钮",
      "zh-TW": "隱藏「好友」按鈕",
      hr: "Sakrij gumb 'Prijatelji'",
      cs: "Skrýt tlačítko „Přátelé“",
      da: "Skjul 'Venner'-knap",
      nl: "Knop 'Vrienden' verbergen",
      en: "Hide 'Friends' Button",
      fi: "Piilota Ystävät-painike",
      fr: "Masquer le bouton « Amis »",
      de: "Schaltfläche „Freunde“ ausblenden",
      el: "Απόκρυψη κουμπιού «Φίλοι»",
      he: "הסתר כפתור 'חברים'",
      hi: "'मित्र' बटन छिपाएँ",
      hu: "A 'Barátok' gomb elrejtése",
      id: "Sembunyikan Tombol 'Teman'",
      it: "Nascondi il pulsante 'Amici'",
      ja: "「友達」ボタンを非表示にする",
      ko: "'친구' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Kawan'",
      no: "Skjul 'Venner'-knappen",
      pl: "Ukryj przycisk „Znajomi”",
      pt: "Ocultar botão ‘Amigos’",
      ro: "Ascundeți butonul „Prieteni”",
      ru: "Скрыть кнопку «Друзья»",
      sk: "Skryť tlačidlo „Priatelia“",
      es: "Ocultar el botón 'Amigos'",
      sv: "Dölj 'Vänner'-knappen",
      th: "ซ่อนปุ่ม 'เพื่อน'",
      tr: "'Arkadaşlar' Düğmesini Gizle",
      uk: "Приховати кнопку «Друзі»",
      vi: "Ẩn nút 'Bạn bè'",
    },
    id: "socialFocus_facebook_header_hide_button_friends",
    defaultValue: false,
  },

  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'المشاهدة'",
      ca: "Amaga el botó 'Mira'",
      "zh-CN": "隐藏“观看”按钮",
      "zh-TW": "隱藏「觀看」按鈕",
      hr: "Sakrij gumb 'Gledaj'",
      cs: "Skrýt tlačítko 'Sledovat'",
      da: "Skjul 'Se'-knappen",
      nl: "Knop 'Kijken' verbergen",
      en: "Hide 'Watch' Button",
      fi: "Piilota Katso-painike",
      fr: "Masquer le bouton « Regarder »",
      de: "Schaltfläche „Beobachten“ ausblenden",
      el: "Απόκρυψη κουμπιού «Ρολόι»",
      he: "הסתר את לחצן 'צפה'",
      hi: "'देखें' बटन छिपाएँ",
      hu: "A „Megtekintés” gomb elrejtése",
      id: "Sembunyikan Tombol 'Tonton'",
      it: "Nascondi il pulsante 'Guarda'",
      ja: "「見る」ボタンを非表示にする",
      ko: "'보기' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Tonton'",
      no: "Skjul 'Se'-knappen",
      pl: "Ukryj przycisk „Oglądaj”",
      pt: "Ocultar botão 'Assistir'",
      ro: "Ascundeți butonul „Urmăriți”",
      ru: "Скрыть кнопку «Смотреть»",
      sk: "Skryť tlačidlo „Sledovať“",
      es: "Ocultar el botón 'Ver'",
      sv: "Dölj 'Titta'-knappen",
      th: "ซ่อนปุ่ม 'ดู'",
      tr: "'İzle' Düğmesini Gizle",
      uk: "Сховати кнопку 'Переглянути'",
      vi: "Ẩn nút 'Xem'",
    },
    id: "socialFocus_facebook_header_hide_button_watch",
    defaultValue: false,
  },

  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'المجموعات'",
      ca: "Amaga el botó 'Grups'",
      "zh-CN": "隐藏“组”按钮",
      "zh-TW": "隱藏“群組”按鈕",
      hr: "Sakrij gumb 'Grupe'",
      cs: "Skrýt tlačítko 'Skupiny'",
      da: "Skjul knappen 'Grupper'",
      nl: "Knop 'Groepen' verbergen",
      en: "Hide 'Groups' Button",
      fi: "Piilota Ryhmät-painike",
      fr: "Masquer le bouton « Groupes »",
      de: "Schaltfläche „Gruppen“ ausblenden",
      el: "Απόκρυψη κουμπιού «Ομάδες»",
      he: "הסתר את לחצן 'קבוצות'",
      hi: "'समूह' बटन छिपाएँ",
      hu: "A 'Csoportok' gomb elrejtése",
      id: "Sembunyikan Tombol 'Grup'",
      it: "Nascondi il pulsante 'Gruppi'",
      ja: "「グループ」ボタンを非表示にする",
      ko: "'그룹' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Kumpulan'",
      no: "Skjul 'Grupper'-knappen",
      pl: "Ukryj przycisk „Grupy”",
      pt: "Ocultar botão 'Grupos'",
      ro: "Ascundeți butonul „Grupuri”",
      ru: "Скрыть кнопку «Группы»",
      sk: "Skryť tlačidlo „Skupiny“",
      es: "Ocultar el botón 'Grupos'",
      sv: "Göm 'Grupper'-knappen",
      th: "ซ่อนปุ่ม 'กลุ่ม'",
      tr: "'Gruplar' Düğmesini Gizle",
      uk: "Приховати кнопку «Групи»",
      vi: "Ẩn nút 'Nhóm'",
    },
    id: "socialFocus_facebook_header_hide_button_groups",
    defaultValue: false,
  },

  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'الألعاب'",
      ca: "Amaga el botó 'Jocs'",
      "zh-CN": "隐藏“游戏”按钮",
      "zh-TW": "隱藏“遊戲”按鈕",
      hr: "Sakrij gumb 'Igre'",
      cs: "Skrýt tlačítko „Hry“",
      da: "Skjul knappen 'Gaming'",
      nl: "Knop 'Gaming' verbergen",
      en: "Hide 'Gaming' Button",
      fi: "Piilota 'Gaming'-painike",
      fr: "Masquer le bouton « Jeu »",
      de: "Schaltfläche „Gaming“ ausblenden",
      el: "Απόκρυψη κουμπιού 'Gaming'",
      he: "הסתר את כפתור 'Gaming'",
      hi: "'गेमिंग' बटन छुपाएं",
      hu: "A „Gaming” gomb elrejtése",
      id: "Sembunyikan Tombol 'Permainan'",
      it: "Nascondi il pulsante 'Gioco'",
      ja: "「ゲーム」ボタンを隠す",
      ko: "'게임' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Gaming'",
      no: "Skjul 'Gaming'-knappen",
      pl: "Ukryj przycisk „Gra”",
      pt: "Ocultar botão 'Jogos'",
      ro: "Ascundeți butonul „Jocuri”",
      ru: "Скрыть кнопку «Игры»",
      sk: "Skryť tlačidlo „Hry“",
      es: "Ocultar el botón 'Juegos'",
      sv: "Dölj 'Gaming'-knappen",
      th: "ซ่อนปุ่ม 'เกม'",
      tr: "'Oyun' Düğmesini Gizle",
      uk: "Сховати кнопку «Ігри»",
      vi: "Ẩn nút 'Chơi game'",
    },
    id: "socialFocus_facebook_header_hide_button_gaming",
    defaultValue: false,
  },

  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'إنشاء'",
      ca: "Amaga el botó 'Crea'",
      "zh-CN": "隐藏“创建”按钮",
      "zh-TW": "隱藏“創建”按鈕",
      hr: "Sakrij gumb 'Stvori'",
      cs: "Skrýt tlačítko „Vytvořit“",
      da: "Skjul knappen 'Opret'",
      nl: "Knop 'Maken' verbergen",
      en: "Hide 'Create' Button",
      fi: "Piilota Luo-painike",
      fr: "Masquer le bouton « Créer »",
      de: "Schaltfläche „Erstellen“ ausblenden",
      el: "Απόκρυψη κουμπιού «Δημιουργία»",
      he: "הסתר את לחצן 'צור'",
      hi: "'बनाएँ' बटन छिपाएँ",
      hu: "A „Létrehozás” gomb elrejtése",
      id: "Sembunyikan Tombol 'Buat'",
      it: "Nascondi il pulsante 'Crea'",
      ja: "「作成」ボタンを非表示にする",
      ko: "'만들기' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Buat'",
      no: "Skjul 'Opprett'-knappen",
      pl: "Ukryj przycisk „Utwórz”",
      pt: "Ocultar botão 'Criar'",
      ro: "Ascunde butonul „Creare”",
      ru: "Скрыть кнопку «Создать»",
      sk: "Skryť tlačidlo „Vytvoriť“",
      es: "Ocultar el botón 'Crear'",
      sv: "Dölj 'Skapa'-knappen",
      th: "ซ่อนปุ่ม 'สร้าง'",
      tr: "'Oluştur' Düğmesini Gizle",
      uk: "Сховати кнопку «Створити»",
      vi: "Ẩn nút 'Tạo'",
    },
    id: "socialFocus_facebook_header_hide_button_create",
    defaultValue: false,
  },

  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'القائمة'",
      ca: "Amaga el botó 'Menú'",
      "zh-CN": "隐藏“菜单”按钮",
      "zh-TW": "隱藏“選單”按鈕",
      hr: "Sakrij gumb 'Izbornik'",
      cs: "Skrýt tlačítko „Nabídka“",
      da: "Skjul 'Menu'-knap",
      nl: "Knop 'Menu' verbergen",
      en: "Hide 'Menu' Button",
      fi: "Piilota valikkopainike",
      fr: "Masquer le bouton « Menu »",
      de: "Schaltfläche „Menü“ ausblenden",
      el: "Απόκρυψη κουμπιού 'Μενού'",
      he: "הסתר את לחצן 'תפריט'",
      hi: "'मेनू' बटन छिपाएँ",
      hu: "A „Menü” gomb elrejtése",
      id: "Sembunyikan Tombol 'Menu'",
      it: "Nascondi il pulsante 'Menu'",
      ja: "「メニュー」ボタンを隠す",
      ko: "'메뉴' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Menu'",
      no: "Skjul 'Meny'-knappen",
      pl: "Ukryj przycisk „Menu”",
      pt: "Ocultar botão 'Menu'",
      ro: "Ascunde butonul „Meniu”",
      ru: "Скрыть кнопку «Меню»",
      sk: "Skryť tlačidlo „Menu“",
      es: "Ocultar el botón 'Menú'",
      sv: "Dölj 'Meny'-knappen",
      th: "ซ่อนปุ่ม 'เมนู'",
      tr: "'Menü' Düğmesini Gizle",
      uk: "Сховати кнопку «Меню»",
      vi: "Ẩn nút 'Menu'",
    },
    id: "socialFocus_facebook_header_hide_button_menu",
    defaultValue: false,
  },

  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'الماسنجر'",
      ca: "Amaga el botó 'Messenger'",
      "zh-CN": "隐藏“信使”按钮",
      "zh-TW": "隱藏「信差」按鈕",
      hr: "Sakrij gumb 'Messenger'",
      cs: "Skrýt tlačítko 'Messenger'",
      da: "Skjul 'Messenger'-knap",
      nl: "Knop 'Messenger' verbergen",
      en: "Hide 'Messenger' Button",
      fi: "Piilota 'Messenger'-painike",
      fr: "Masquer le bouton « Messenger »",
      de: "Schaltfläche „Messenger“ ausblenden",
      el: "Απόκρυψη κουμπιού «Αγγελιοφόρος»",
      he: "הסתר את לחצן 'מסנג'ר'",
      hi: "'मैसेंजर' बटन छिपाएँ",
      hu: "A „Messenger” gomb elrejtése",
      id: "Sembunyikan Tombol 'Messenger'",
      it: "Nascondi il pulsante 'Messaggero'",
      ja: "「メッセンジャー」ボタンを非表示にする",
      ko: "'메신저' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Messenger'",
      no: "Skjul 'Messenger'-knappen",
      pl: "Ukryj przycisk „Posłaniec”",
      pt: "Ocultar botão 'Messenger'",
      ro: "Ascundeți butonul „Messenger”",
      ru: "Скрыть кнопку «Мессенджер»",
      sk: "Skryť tlačidlo „Messenger“",
      es: "Ocultar el botón 'Messenger'",
      sv: "Dölj 'Messenger'-knappen",
      th: "ซ่อนปุ่ม 'Messenger'",
      tr: "'Messenger' Düğmesini Gizle",
      uk: "Сховати кнопку «Месенджер»",
      vi: "Ẩn nút 'Messenger'",
    },
    id: "socialFocus_facebook_header_hide_button_messanger",
    defaultValue: false,
  },

  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'الإخطارات'",
      ca: "Amaga el botó 'Notificacions'",
      "zh-CN": "隐藏“通知”按钮",
      "zh-TW": "隱藏「通知」按鈕",
      hr: "Sakrij gumb 'Obavijesti'",
      cs: "Skrýt tlačítko 'Oznámení'",
      da: "Skjul knappen 'Meddelelser'",
      nl: "Knop 'Meldingen' verbergen",
      en: "Hide 'Notifications' Button",
      fi: "Piilota Ilmoitukset-painike",
      fr: "Masquer le bouton « Notifications »",
      de: "Schaltfläche „Benachrichtigungen“ ausblenden",
      el: "Απόκρυψη κουμπιού «Ειδοποιήσεις»",
      he: "הסתר את לחצן 'התראות'",
      hi: "'सूचनाएँ' बटन छिपाएँ",
      hu: "Az „Értesítések” gomb elrejtése",
      id: "Sembunyikan Tombol 'Pemberitahuan'",
      it: "Nascondi il pulsante 'Notifiche'",
      ja: "「通知」ボタンを非表示にする",
      ko: "'알림' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Pemberitahuan'",
      no: "Skjul 'Varslinger'-knappen",
      pl: "Ukryj przycisk „Powiadomienia”",
      pt: "Ocultar botão 'Notificações'",
      ro: "Ascundeți butonul „Notificări”",
      ru: "Скрыть кнопку «Уведомления»",
      sk: "Skryť tlačidlo „Upozornenia“",
      es: "Ocultar el botón 'Notificaciones'",
      sv: "Dölj knappen 'Meddelanden'",
      th: "ซ่อนปุ่ม 'การแจ้งเตือน'",
      tr: "'Bildirimler' Düğmesini Gizle",
      uk: "Сховати кнопку «Сповіщення»",
      vi: "Ẩn nút 'Thông báo'",
    },
    id: "socialFocus_facebook_header_hide_button_notifications",
    defaultValue: false,
  },
];

// MARK: Right Bar

const facebookDesktopGroups_RightBar = [
  {
    type: "checkbox",
    name: {
      ar: "إخفاء الحظر 'المدعوم'",
      ca: "Amaga el bloc 'Patrocinat'",
      "zh-CN": "隐藏“赞助”块",
      "zh-TW": "隱藏「贊助」區塊",
      hr: "Sakrij 'Sponzorirani' blok",
      cs: "Skrýt blok „Sponzorováno“",
      da: "Skjul 'Sponsoreret' blok",
      nl: "Verberg 'Gesponsord' blok",
      en: "Hide 'Sponsored' Block",
      fi: "Piilota 'sponsoroitu' lohko",
      fr: "Masquer le bloc « sponsorisé »",
      de: "„Gesponserten“ Block ausblenden",
      el: "Απόκρυψη αποκλεισμού 'Χορηγούμενων'",
      he: "הסתר בלוק 'ממומן'",
      hi: "'प्रायोजित' ब्लॉक छिपाएँ",
      hu: "A „Szponzorált” blokk elrejtése",
      id: "Sembunyikan Blok 'Disponsori'",
      it: "Nascondi il blocco 'Sponsorizzato'",
      ja: "「スポンサー付き」ブロックを非表示にする",
      ko: "'후원' 블록 숨기기",
      ms: "Sembunyikan Blok 'Tajaan'",
      no: "Skjul 'Sponset' blokk",
      pl: "Ukryj blok „sponsorowany”",
      pt: "Ocultar bloco 'Patrocinado'",
      ro: "Ascundeți blocul „Sponsorizat”",
      ru: "Скрыть блок «Рекламные»",
      sk: "Skryť blok „Sponzorované“",
      es: "Ocultar bloque 'patrocinado'",
      sv: "Dölj 'sponsrat' block",
      th: "ซ่อนบล็อก 'ผู้สนับสนุน'",
      tr: "'Sponsorlu' Bloğu Gizle",
      uk: "Сховати блок «Спонсорований»",
      vi: "Ẩn khối 'Được tài trợ'",
    },
    id: "socialFocus_facebook_right_bar_hide_block_sponsored",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء حظر 'جهات الاتصال'",
      ca: "Amaga el bloc 'Contactes'",
      "zh-CN": "隐藏“联系人”块",
      "zh-TW": "隱藏「聯絡人」區塊",
      hr: "Sakrij blok 'Kontakti'",
      cs: "Skrýt blok 'Kontakty'",
      da: "Skjul 'Kontakter'-blok",
      nl: "Blok 'Contacten' verbergen",
      en: "Hide 'Contacts' Block",
      fi: "Piilota Yhteystiedot-lohko",
      fr: "Masquer le bloc « Contacts »",
      de: "Block „Kontakte“ ausblenden",
      el: "Απόκρυψη μπλοκ 'Επαφές'",
      he: "הסתר בלוק 'אנשי קשר'",
      hi: "'संपर्क' ब्लॉक छिपाएँ",
      hu: "A „Névjegyek” blokk elrejtése",
      id: "Sembunyikan Blok 'Kontak'",
      it: "Nascondi il blocco 'Contatti'",
      ja: "「連絡先」ブロックを非表示にする",
      ko: "'연락처' 차단 숨기기",
      ms: "Sembunyikan Blok 'Kenalan'",
      no: "Skjul 'Kontakter'-blokk",
      pl: "Ukryj blok „Kontakty”",
      pt: "Ocultar bloco ‘Contatos’",
      ro: "Ascunde blocul „Contacte”",
      ru: "Скрыть блок «Контакты»",
      sk: "Skryť blok „Kontakty“",
      es: "Ocultar bloque 'Contactos'",
      sv: "Dölj 'Kontakter'-blocket",
      th: "ซ่อนบล็อก 'ผู้ติดต่อ'",
      tr: "'Kişiler' Bloğunu Gizle",
      uk: "Сховати блок «Контакти»",
      vi: "Ẩn khối 'Danh bạ'",
    },
    id: "socialFocus_facebook_right_bar_hide_block_contacts",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء حظر 'المحادثات الجماعية'",
      ca: "Amaga el bloc 'Converses de grup'",
      "zh-CN": "隐藏“群组对话”块",
      "zh-TW": "隱藏「群組對話」區塊",
      hr: "Sakrij blok 'Grupni razgovori'",
      cs: "Skrýt blok „Skupinové konverzace“",
      da: "Skjul 'Gruppesamtaler'-blok",
      nl: "Blokkeer 'Groepsgesprekken' verbergen",
      en: "Hide 'Group conversations' Block",
      fi: "Piilota Ryhmäkeskustelujen esto",
      fr: "Masquer le bloc « Conversations de groupe »",
      de: "Block „Gruppengespräche“ ausblenden",
      el: "Απόκρυψη αποκλεισμού 'Ομαδικές συνομιλίες'",
      he: "הסתר חסימת 'שיחות קבוצתיות'",
      hi: "'समूह वार्तालाप' छिपाएँ ब्लॉक करें",
      hu: "A „Csoportos beszélgetések” blokk elrejtése",
      id: "Sembunyikan Blok 'Percakapan grup'",
      it: "Nascondi il blocco 'Conversazioni di gruppo'",
      ja: "「グループ会話」ブロックを非表示にする",
      ko: "'그룹 대화' 차단 숨기기",
      ms: "Sembunyikan Sekat 'Perbualan kumpulan'",
      no: "Skjul 'Gruppesamtaler'-blokken",
      pl: "Ukryj blok „Rozmowy grupowe”",
      pt: "Ocultar o bloco ‘Conversas em grupo’",
      ro: "Ascunde blocul „Conversații de grup”",
      ru: "Скрыть блок «Групповые беседы»",
      sk: "Skryť blok „Skupinové konverzácie“",
      es: "Ocultar bloque 'Conversaciones grupales'",
      sv: "Dölj blocket 'Gruppkonversationer'",
      th: "ซ่อนบล็อก 'การสนทนากลุ่ม'",
      tr: "'Grup konuşmaları' Engelini gizle",
      uk: "Сховати блок 'Групові розмови'",
      vi: "Ẩn khối 'Cuộc trò chuyện nhóm'",
    },
    id: "socialFocus_facebook_right_bar_hide_block_group_conversations",
    defaultValue: false,
  },
];

// MARK: Left Bar

const facebookDesktopGroups_LeftNavigationBar = [
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'الملف الشخصي'",
      ca: "Amaga el botó 'Perfil'",
      "zh-CN": "隐藏“个人资料”按钮",
      "zh-TW": "隱藏「個人資料」按鈕",
      hr: "Sakrij gumb 'Profil'",
      cs: "Skrýt tlačítko „Profil“",
      da: "Skjul 'Profil'-knap",
      nl: "Knop 'Profiel' verbergen",
      en: "Hide 'Profile' Button",
      fi: "Piilota 'Profiili'-painike",
      fr: "Masquer le bouton « Profil »",
      de: "Schaltfläche „Profil“ ausblenden",
      el: "Κουμπί απόκρυψης 'Προφίλ'",
      he: "הסתר כפתור 'פרופיל'",
      hi: "'प्रोफ़ाइल' बटन छिपाएँ",
      hu: "A „Profil” gomb elrejtése",
      id: "Sembunyikan Tombol 'Profil'",
      it: "Nascondi il pulsante 'Profilo'",
      ja: "「プロフィール」ボタンを非表示にする",
      ko: "'프로필' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Profil'",
      no: "Skjul 'Profil'-knappen",
      pl: "Ukryj przycisk „Profil”",
      pt: "Ocultar botão 'Perfil'",
      ro: "Ascunde butonul „Profil”",
      ru: "Скрыть кнопку «Профиль»",
      sk: "Skryť tlačidlo „Profil“",
      es: "Ocultar botón 'Perfil'",
      sv: "Dölj 'Profil'-knappen",
      th: "ซ่อนปุ่ม 'โปรไฟล์'",
      tr: "'Profil' Düğmesini Gizle",
      uk: "Приховати кнопку «Профіль»",
      vi: "Ẩn nút 'Hồ sơ'",
    },
    id: "socialFocus_facebook_left_bar_hide_button_profile",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'البحث عن أصدقاء'",
      ca: "Amaga el botó 'Troba amics'",
      "zh-CN": "隐藏“查找朋友”按钮",
      "zh-TW": "隱藏「尋找朋友」按鈕",
      hr: "Sakrij gumb 'Pronađi prijatelje'",
      cs: "Skrýt tlačítko „Najít přátele“",
      da: "Skjul knappen 'Find venner'",
      nl: "Verberg de knop 'Vrienden zoeken'",
      en: "Hide 'Find Friends' Button",
      fi: "Piilota Etsi ystäviä -painike",
      fr: "Masquer le bouton « Trouver des amis »",
      de: "Schaltfläche „Freunde finden“ ausblenden",
      el: "Απόκρυψη κουμπιού «Εύρεση φίλων»",
      he: "הסתר את לחצן 'מצא חברים'",
      hi: "'मित्र खोजें' बटन छिपाएँ",
      hu: "A 'Barátok keresése' gomb elrejtése",
      id: "Sembunyikan Tombol 'Temukan Teman'",
      it: "Nascondi il pulsante 'Trova amici'",
      ja: "「友達を探す」ボタンを非表示にする",
      ko: "'친구 찾기' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Cari Rakan'",
      no: "Skjul 'Finn venner'-knappen",
      pl: "Ukryj przycisk „Znajdź znajomych”",
      pt: "Ocultar o botão ‘Encontrar amigos’",
      ro: "Ascundeți butonul „Găsiți prieteni”",
      ru: "Скрыть кнопку «Найти друзей»",
      sk: "Skryť tlačidlo „Nájsť priateľov“",
      es: "Ocultar el botón 'Buscar amigos'",
      sv: "Dölj knappen Hitta vänner",
      th: "ซ่อนปุ่ม 'ค้นหาเพื่อน'",
      tr: "'Arkadaş Bul' Düğmesini Gizle",
      uk: "Приховати кнопку «Знайти друзів»",
      vi: "Ẩn nút 'Tìm bạn bè'",
    },
    id: "socialFocus_facebook_left_bar_hide_button_friends",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'الذكريات'",
      ca: "Amaga el botó 'Memòries'",
      "zh-CN": "隐藏“回忆”按钮",
      "zh-TW": "隱藏“回憶”按鈕",
      hr: "Sakrij gumb 'Uspomene'",
      cs: "Skrýt tlačítko „Vzpomínky“",
      da: "Skjul 'Memories'-knap",
      nl: "Knop 'Herinneringen' verbergen",
      en: "Hide 'Memories' Button",
      fi: "Piilota Muistot-painike",
      fr: "Masquer le bouton « Mémoires »",
      de: "Schaltfläche „Erinnerungen“ ausblenden",
      el: "Κουμπί απόκρυψης 'Μνήμες'",
      he: "הסתר כפתור 'זכרונות'",
      hi: "'यादें' बटन छिपाएँ",
      hu: "Az „Emlékek” gomb elrejtése",
      id: "Sembunyikan Tombol 'Kenangan'",
      it: "Nascondi il pulsante 'Ricordi'",
      ja: "「思い出」ボタンを隠す",
      ko: "'추억' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Memories'",
      no: "Skjul 'minner'-knappen",
      pl: "Ukryj przycisk „Wspomnienia”",
      pt: "Ocultar botão 'Memórias'",
      ro: "Ascunde butonul „Amintiri”",
      ru: "Скрыть кнопку «Воспоминания»",
      sk: "Skryť tlačidlo 'Spomienky'",
      es: "Ocultar el botón 'Recuerdos'",
      sv: "Dölj 'Memories'-knappen",
      th: "ซ่อนปุ่ม 'ความทรงจำ'",
      tr: "'Anılar' Düğmesini Gizle",
      uk: "Сховати кнопку «Спогади»",
      vi: "Ẩn nút 'Ký ức'",
    },
    id: "socialFocus_facebook_left_bar_hide_button_memories",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء الزر 'المحفوظ'",
      ca: "Amaga el botó 'Desat'",
      "zh-CN": "隐藏“已保存”按钮",
      "zh-TW": "隱藏「已儲存」按鈕",
      hr: "Sakrij gumb 'Spremljeno'",
      cs: "Skrýt tlačítko „Uložené“",
      da: "Skjul knappen 'Gem'",
      nl: "Knop 'Opgeslagen' verbergen",
      en: "Hide 'Saved' Button",
      fi: "Piilota 'Tallennettu'-painike",
      fr: "Masquer le bouton « Enregistré »",
      de: "Schaltfläche „Gespeichert“ ausblenden",
      el: "Απόκρυψη κουμπιού «Αποθηκευμένο»",
      he: "הסתר את הלחצן 'שמור'",
      hi: "'सहेजा गया' बटन छिपाएँ",
      hu: "A „Mentett” gomb elrejtése",
      id: "Sembunyikan Tombol 'Tersimpan'",
      it: "Nascondi il pulsante 'Salvato'",
      ja: "「保存済み」ボタンを非表示にする",
      ko: "'저장됨' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Disimpan'",
      no: "Skjul 'Lagret'-knappen",
      pl: "Ukryj przycisk „Zapisano”",
      pt: "Ocultar botão 'Salvo'",
      ro: "Ascundeți butonul „Salvat”",
      ru: "Скрыть кнопку «Сохранено»",
      sk: "Skryť tlačidlo „Uložené“",
      es: "Ocultar botón 'Guardado'",
      sv: "Dölj knappen 'Sparat'",
      th: "ซ่อนปุ่ม 'บันทึก'",
      tr: "'Kaydedildi' Düğmesini Gizle",
      uk: "Сховати кнопку «Збережено»",
      vi: "Ẩn nút 'Đã lưu'",
    },
    id: "socialFocus_facebook_left_bar_hide_button_saved",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'المجموعات'",
      ca: "Amaga el botó 'Grups'",
      "zh-CN": "隐藏“组”按钮",
      "zh-TW": "隱藏“群組”按鈕",
      hr: "Sakrij gumb 'Grupe'",
      cs: "Skrýt tlačítko 'Skupiny'",
      da: "Skjul knappen 'Grupper'",
      nl: "Knop 'Groepen' verbergen",
      en: "Hide 'Groups' Button",
      fi: "Piilota Ryhmät-painike",
      fr: "Masquer le bouton « Groupes »",
      de: "Schaltfläche „Gruppen“ ausblenden",
      el: "Απόκρυψη κουμπιού «Ομάδες»",
      he: "הסתר את לחצן 'קבוצות'",
      hi: "'समूह' बटन छिपाएँ",
      hu: "A 'Csoportok' gomb elrejtése",
      id: "Sembunyikan Tombol 'Grup'",
      it: "Nascondi il pulsante 'Gruppi'",
      ja: "「グループ」ボタンを非表示にする",
      ko: "'그룹' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Kumpulan'",
      no: "Skjul 'Grupper'-knappen",
      pl: "Ukryj przycisk „Grupy”",
      pt: "Ocultar botão 'Grupos'",
      ro: "Ascundeți butonul „Grupuri”",
      ru: "Скрыть кнопку «Группы»",
      sk: "Skryť tlačidlo „Skupiny“",
      es: "Ocultar el botón 'Grupos'",
      sv: "Dölj knappen 'Grupper'",
      th: "ซ่อนปุ่ม 'กลุ่ม'",
      tr: "'Gruplar' Düğmesini Gizle",
      uk: "Приховати кнопку «Групи»",
      vi: "Ẩn nút 'Nhóm'",
    },
    id: "socialFocus_facebook_left_bar_hide_button_groups",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'الفيديو'",
      ca: "Amaga el botó 'Vídeo'",
      "zh-CN": "隐藏“视频”按钮",
      "zh-TW": "隱藏“視訊”按鈕",
      hr: "Sakrij gumb 'Video'",
      cs: "Skrýt tlačítko „Video“",
      da: "Skjul 'Video'-knap",
      nl: "Knop 'Video' verbergen",
      en: "Hide 'Video' Button",
      fi: "Piilota 'Video'-painike",
      fr: "Masquer le bouton « Vidéo »",
      de: "Schaltfläche „Video“ ausblenden",
      el: "Απόκρυψη κουμπιού 'Βίντεο'",
      he: "הסתר את לחצן 'וידאו'",
      hi: "'वीडियो' बटन छिपाएँ",
      hu: "A „Videó” gomb elrejtése",
      id: "Sembunyikan Tombol 'Video'",
      it: "Nascondi il pulsante 'Video'",
      ja: "「ビデオ」ボタンを隠す",
      ko: "'비디오' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Video'",
      no: "Skjul 'Video'-knappen",
      pl: "Ukryj przycisk „Wideo”",
      pt: "Ocultar botão 'Vídeo'",
      ro: "Ascunde butonul „Video”",
      ru: "Скрыть кнопку «Видео»",
      sk: "Skryť tlačidlo „Video“",
      es: "Ocultar el botón 'Vídeo'",
      sv: "Dölj 'Video'-knappen",
      th: "ซ่อนปุ่ม 'วิดีโอ'",
      tr: "'Video' Düğmesini Gizle",
      uk: "Сховати кнопку «Відео»",
      vi: "Ẩn nút 'Video'",
    },
    id: "socialFocus_facebook_left_bar_hide_button_video",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'السوق'",
      ca: "Amaga el botó 'Mercat'",
      "zh-CN": "隐藏“市场”按钮",
      "zh-TW": "隱藏“市場”按鈕",
      hr: "Sakrij gumb 'Tržište'",
      cs: "Skrýt tlačítko „Tržiště“",
      da: "Skjul 'Markedsplads'-knap",
      nl: "Knop 'Marktplaats' verbergen",
      en: "Hide 'Marketplace' Button",
      fi: "Piilota Marketplace-painike",
      fr: "Masquer le bouton « Place de marché »",
      de: "Schaltfläche „Marktplatz“ ausblenden",
      el: "Απόκρυψη κουμπιού 'Marketplace'",
      he: "הסתר את לחצן 'מרקטפלייס'",
      hi: "'मार्केटप्लेस' बटन छिपाएँ",
      hu: "A „Piactér” gomb elrejtése",
      id: "Sembunyikan Tombol 'Marketplace'",
      it: "Nascondi il pulsante 'Mercato'",
      ja: "「マーケットプレイス」ボタンを隠す",
      ko: "'마켓플레이스' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Marketplace'",
      no: "Skjul 'Markedsplass'-knappen",
      pl: "Ukryj przycisk „Rynek”",
      pt: "Ocultar botão 'Marketplace'",
      ro: "Ascundeți butonul „Piață”",
      ru: "Скрыть кнопку «Торговая площадка»",
      sk: "Skryť tlačidlo Trhovisko",
      es: "Ocultar el botón 'Mercado'",
      sv: "Dölj 'Marknadsplats'-knappen",
      th: "ซ่อนปุ่ม 'ตลาดกลาง'",
      tr: "'Pazaryeri' Düğmesini Gizle",
      uk: "Сховати кнопку 'Биржа'",
      vi: "Ẩn nút 'Thị trường'",
    },
    id: "socialFocus_facebook_left_bar_hide_button_marketplace",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'الخلاصات'",
      ca: "Amaga el botó 'Feeds'",
      "zh-CN": "隐藏“提要”按钮",
      "zh-TW": "隱藏「提要」按鈕",
      hr: "Sakrij gumb 'Feeds'",
      cs: "Skrýt tlačítko 'Fedy'",
      da: "Skjul 'Feeds'-knap",
      nl: "Knop 'Feeds' verbergen",
      en: "Hide 'Feeds' Button",
      fi: "Piilota 'Syötteet'-painike",
      fr: "Masquer le bouton « Flux »",
      de: "Schaltfläche „Feeds“ ausblenden",
      el: "Απόκρυψη κουμπιού 'Ροές'",
      he: "הסתר כפתור 'הזנות'",
      hi: "'फ़ीड्स' बटन छिपाएँ",
      hu: "A „Hírcsatornák” gomb elrejtése",
      id: "Sembunyikan Tombol 'Umpan'",
      it: "Nascondi il pulsante 'Feed'",
      ja: "「フィード」ボタンを非表示にする",
      ko: "'피드' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Suapan'",
      no: "Skjul 'Feeds'-knappen",
      pl: "Ukryj przycisk „Kanały”",
      pt: "Ocultar botão 'Feeds'",
      ro: "Ascundeți butonul „Feeduri”",
      ru: "Скрыть кнопку «Ленты»",
      sk: "Skryť tlačidlo „Informačné kanály“",
      es: "Ocultar el botón 'Feeds'",
      sv: "Dölj 'Feeds'-knappen",
      th: "ซ่อนปุ่ม 'ฟีด'",
      tr: "'Yayınlar' Düğmesini Gizle",
      uk: "Сховати кнопку «Канали»",
      vi: "Ẩn nút 'Nguồn cấp dữ liệu'",
    },
    id: "socialFocus_facebook_left_bar_hide_button_feeds",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'الأحداث'",
      ca: "Amaga el botó 'Esdeveniments'",
      "zh-CN": "隐藏“活动”按钮",
      "zh-TW": "隱藏“活動”按鈕",
      hr: "Sakrij gumb 'Događaji'",
      cs: "Skrýt tlačítko „Události“",
      da: "Skjul 'Begivenheder'-knap",
      nl: "Knop 'Gebeurtenissen' verbergen",
      en: "Hide 'Events' Button",
      fi: "Piilota Tapahtumat-painike",
      fr: "Masquer le bouton « Événements »",
      de: "Schaltfläche „Ereignisse“ ausblenden",
      el: "Κουμπί απόκρυψης 'Εκδηλώσεις'",
      he: "הסתר את לחצן 'אירועים'",
      hi: "'इवेंट' बटन छिपाएँ",
      hu: "Az „Események” gomb elrejtése",
      id: "Sembunyikan Tombol 'Acara'",
      it: "Nascondi il pulsante 'Eventi'",
      ja: "「イベント」ボタンを非表示にする",
      ko: "'이벤트' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Acara'",
      no: "Skjul 'Hendelser'-knappen",
      pl: "Ukryj przycisk „Wydarzenia”",
      pt: "Ocultar botão 'Eventos'",
      ro: "Ascunde butonul „Evenimente”",
      ru: "Скрыть кнопку «События»",
      sk: "Skryť tlačidlo „Udalosti“",
      es: "Ocultar el botón 'Eventos'",
      sv: "Dölj 'Händelser'-knappen",
      th: "ซ่อนปุ่ม 'กิจกรรม'",
      tr: "'Etkinlikler' Düğmesini Gizle",
      uk: "Сховати кнопку «Події»",
      vi: "Ẩn nút 'Sự kiện'",
    },
    id: "socialFocus_facebook_left_bar_hide_button_events",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'مدير الإعلانات'",
      ca: "Amaga el botó 'Gestor d'anuncis'",
      "zh-CN": "隐藏“广告管理器”按钮",
      "zh-TW": "隱藏「廣告管理器」按鈕",
      hr: "Sakrij gumb 'Ads Manager'",
      cs: "Skrýt tlačítko Správce reklam",
      da: "Skjul knappen 'Annonceadministrator'",
      nl: "Knop 'Advertentiebeheer' verbergen",
      en: "Hide 'Ads Manager' Button",
      fi: "Piilota Mainosten hallinta -painike",
      fr: "Masquer le bouton « Gestionnaire de publicités »",
      de: "Schaltfläche „Anzeigenmanager“ ausblenden",
      el: "Απόκρυψη του κουμπιού 'Διαχείριση διαφημίσεων'",
      he: "הסתר את לחצן 'מנהל המודעות'",
      hi: "'विज्ञापन प्रबंधक' बटन छिपाएँ",
      hu: "A 'Hirdetéskezelő' gomb elrejtése",
      id: "Sembunyikan Tombol 'Manajer Iklan'",
      it: "Nascondi il pulsante 'Gestione annunci'",
      ja: "「広告マネージャー」ボタンを非表示にする",
      ko: "'광고 관리자' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Pengurus Iklan'",
      no: "Skjul Annonseadministrator-knappen",
      pl: "Ukryj przycisk „Menedżer reklam”",
      pt: "Ocultar botão 'Gerenciador de anúncios'",
      ro: "Ascundeți butonul „Manager de anunțuri”",
      ru: "Скрыть кнопку «Менеджер рекламы»",
      sk: "Skryť tlačidlo Správca reklám",
      es: "Ocultar el botón 'Administrador de anuncios'",
      sv: "Dölj knappen 'Annonshanterare'",
      th: "ซ่อนปุ่ม 'ตัวจัดการโฆษณา'",
      tr: "'Reklam Yöneticisi' Düğmesini Gizle",
      uk: "Приховати кнопку «Ads Manager»",
      vi: "Ẩn nút 'Trình quản lý quảng cáo'",
    },
    id: "socialFocus_facebook_left_bar_hide_button_ads_manager",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'جمع التبرعات'",
      ca: "Amaga el botó 'Recaptacions de fons'",
      "zh-CN": "隐藏“筹款活动”按钮",
      "zh-TW": "隱藏「籌款活動」按鈕",
      hr: "Sakrij gumb 'Prikupljanje sredstava'",
      cs: "Skrýt tlačítko „Fundraisers“",
      da: "Skjul knappen 'Fundraisers'",
      nl: "Knop 'Inzamelingsacties' verbergen",
      en: "Hide 'Fundraisers' Button",
      fi: "Piilota 'Varainkeruu'-painike",
      fr: "Masquer le bouton « Collectes de fonds »",
      de: "Schaltfläche „Spendenaktionen“ ausblenden",
      el: "Απόκρυψη κουμπιού «Ερανοί»",
      he: "הסתר את כפתור 'גיוסי תרומות'",
      hi: "'धन संचयन' बटन छिपाएँ",
      hu: "Az „Adománygyűjtések” gomb elrejtése",
      id: "Sembunyikan Tombol 'Pengumpul Dana'",
      it: "Nascondi il pulsante 'Raccolte fondi'",
      ja: "「募金活動」ボタンを非表示にする",
      ko: "'모금 행사' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Pengumpul dana'",
      no: "Skjul innsamlingsknappen",
      pl: "Ukryj przycisk „Zbiórki”",
      pt: "Ocultar o botão 'Arrecadação de fundos'",
      ro: "Ascundeți butonul „Strângeri de fonduri”",
      ru: "Скрыть кнопку «Сбор средств»",
      sk: "Skryť tlačidlo 'Finančné zbierky'",
      es: "Ocultar el botón 'Recaudación de fondos'",
      sv: "Dölj knappen 'Insamlingar'",
      th: "ซ่อนปุ่ม 'ระดมทุน'",
      tr: "'Bağış Toplayanlar' Düğmesini Gizle",
      uk: "Сховати кнопку «Збір коштів»",
      vi: "Ẩn nút 'Gây quỹ'",
    },
    id: "socialFocus_facebook_left_bar_hide_button_fundraisers",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'رؤية المزيد'",
      ca: "Amaga el botó 'Veure més'",
      "zh-CN": "隐藏“查看更多”按钮",
      "zh-TW": "隱藏「看更多」按鈕",
      hr: "Sakrij gumb 'Vidi više'",
      cs: "Skrýt tlačítko „Zobrazit více“",
      da: "Skjul knappen 'Se mere'",
      nl: "Knop 'Meer bekijken' verbergen",
      en: "Hide 'See more' Button",
      fi: "Piilota Katso lisää -painike",
      fr: "Masquer le bouton « Voir plus »",
      de: "Schaltfläche „Mehr anzeigen“ ausblenden",
      el: "Απόκρυψη κουμπιού 'Δείτε περισσότερα'",
      he: "הסתר את לחצן 'ראה עוד'",
      hi: "'और देखें' बटन छिपाएँ",
      hu: "A „Továbbiak” gomb elrejtése",
      id: "Sembunyikan Tombol 'Lihat selengkapnya'",
      it: "Nascondi il pulsante 'Vedi altro'",
      ja: "「もっと見る」ボタンを非表示にする",
      ko: "'더보기' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Lihat lagi'",
      no: "Skjul 'Se mer'-knappen",
      pl: "Ukryj przycisk „Zobacz więcej”",
      pt: "Ocultar o botão 'Ver mais'",
      ro: "Ascunde butonul „Vezi mai multe”",
      ru: "Скрыть кнопку «Показать больше»",
      sk: "Skryť tlačidlo „Zobraziť viac“",
      es: "Ocultar el botón 'Ver más'",
      sv: "Dölj 'Se mer'-knappen",
      th: "ซ่อนปุ่ม 'ดูเพิ่มเติม'",
      tr: "'Daha fazlasını gör' düğmesini gizle",
      uk: "Сховати кнопку 'Показати більше'",
      vi: "Ẩn nút 'Xem thêm'",
    },
    id: "socialFocus_facebook_left_bar_hide_button_see_more",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء التذييل",
      ca: "Amaga el peu de pàgina",
      "zh-CN": "隐藏页脚",
      "zh-TW": "隱藏頁尾",
      hr: "Sakrij podnožje",
      cs: "Skrýt zápatí",
      da: "Skjul sidefod",
      nl: "Voettekst verbergen",
      en: "Hide Footer",
      fi: "Piilota alatunniste",
      fr: "Masquer le pied de page",
      de: "Fußzeile ausblenden",
      el: "Απόκρυψη υποσέλιδου",
      he: "הסתר כותרת תחתונה",
      hi: "फ़ुटर छिपाएँ",
      hu: "Lábléc elrejtése",
      id: "Sembunyikan Catatan Kaki",
      it: "Nascondi piè di pagina",
      ja: "フッターを隠す",
      ko: "바닥글 숨기기",
      ms: "Sembunyikan Pengaki",
      no: "Skjul bunntekst",
      pl: "Ukryj stopkę",
      pt: "Ocultar rodapé",
      ro: "Ascunde subsolul",
      ru: "Скрыть нижний колонтитул",
      sk: "Skryť pätu",
      es: "Ocultar pie de página",
      sv: "Dölj sidfot",
      th: "ซ่อนส่วนท้าย",
      tr: "Alt Bilgiyi Gizle",
      uk: "Приховати нижній колонтитул",
      vi: "Ẩn chân trang",
    },
    id: "socialFocus_facebook_left_bar_hide_footer",
    defaultValue: false,
  },
];

// MARK: Other

const facebookDesktopGroups_Other = [
  {
    type: "checkbox",
    name: {
      ar: "إخفاء الزر العائم 'رسالة جديدة'",
      ca: "Amaga el botó flotant 'Nou missatge'",
      "zh-CN": "隐藏“新消息”浮动按钮",
      "zh-TW": "隱藏「新訊息」浮動按鈕",
      hr: "Sakrij plutajući gumb 'Nova poruka'",
      cs: "Skrýt plovoucí tlačítko „Nová zpráva“",
      da: "Skjul 'Ny besked' flydende knap",
      nl: "Zwevende knop 'Nieuw bericht' verbergen",
      en: "Hide 'New Message' Floating Button",
      fi: "Piilota 'Uusi viesti' kelluva painike",
      fr: "Masquer le bouton flottant « Nouveau message »",
      de: "Schwebende Schaltfläche „Neue Nachricht“ ausblenden",
      el: "Απόκρυψη αιωρούμενου κουμπιού 'Νέο μήνυμα'",
      he: "הסתר את הלחצן הצף 'הודעה חדשה'",
      hi: "'नया संदेश' फ़्लोटिंग बटन छिपाएँ",
      hu: "Az „Új üzenet” lebegő gomb elrejtése",
      id: "Sembunyikan Tombol Mengambang 'Pesan Baru'",
      it: "Nascondi il pulsante mobile 'Nuovo messaggio'",
      ja: "「新規メッセージ」フローティング ボタンを非表示にする",
      ko: "'새 메시지' 플로팅 버튼 숨기기",
      ms: "Sembunyikan Butang Terapung 'Mesej Baharu'",
      no: "Skjul 'Ny melding' flytende knapp",
      pl: "Ukryj pływający przycisk „Nowa wiadomość”",
      pt: "Ocultar botão flutuante 'Nova mensagem'",
      ro: "Ascundeți butonul plutitor „Mesaj nou”",
      ru: "Скрыть плавающую кнопку «Новое сообщение»",
      sk: "Skryť plávajúce tlačidlo „Nová správa“",
      es: "Ocultar el botón flotante 'Nuevo mensaje'",
      sv: "Dölj 'Nytt meddelande' flytande knapp",
      th: "ซ่อนปุ่มลอย 'ข้อความใหม่'",
      tr: "'Yeni Mesaj' Kayan Düğmesini Gizle",
      uk: "Сховати плаваючу кнопку «Нове повідомлення»",
      vi: "Ẩn nút nổi 'Tin nhắn mới'",
    },
    id: "socialFocus_facebook_other_hide_floating_button_new_message",
    defaultValue: false,
  },
];

// MARK: - Desktop Builder

const facebookDesktopGroups = [
  {
    groupName: {
      ar: "",
      ca: "",
      "zh-CN": "",
      "zh-TW": "",
      hr: "",
      cs: "",
      da: "",
      nl: "",
      en: "",
      fi: "",
      fr: "",
      de: "",
      el: "",
      he: "",
      hi: "",
      hu: "",
      id: "",
      it: "",
      ja: "",
      ko: "",
      ms: "",
      no: "",
      pl: "",
      pt: "",
      ro: "",
      ru: "",
      sk: "",
      es: "",
      sv: "",
      th: "",
      tr: "",
      uk: "",
      vi: "",
    },
    groupId: "disableSocialFocus",
    parentCategoryId: "facebook",
    options: [facebookDesktopGroups_DisableSocialFocus],
  },
  {
    groupName: {
      ar: "أساسيات",
      ca: "Essencials",
      "zh-CN": "必需品",
      "zh-TW": "必需品",
      hr: "Osnove",
      cs: "Essentials",
      da: "Essentialer",
      nl: "Essentiële zaken",
      en: "Essentials",
      fi: "Essentials",
      fr: "Essentiel",
      de: "Wesentliches",
      el: "Βασικά",
      he: "יסודות",
      hi: "अनिवार्य",
      hu: "Essentials",
      id: "Penting",
      it: "Elementi essenziali",
      ja: "必需品",
      ko: "골자",
      ms: "Perkara-perkara penting",
      no: "Essensielle",
      pl: "Elementy zasadnicze",
      pt: "Fundamentos",
      ro: "Esențiale",
      ru: "Основы",
      sk: "Essentials",
      es: "Esenciales",
      sv: "Essentials",
      th: "สิ่งจำเป็น",
      tr: "Temeller",
      uk: "Основи",
      vi: "Yếu tố cần thiết",
    },
    groupId: "essentials",
    parentCategoryId: "facebook",
    options: facebookDesktopGroups_Essentials,
  },
  {
    groupName: {
      ar: "الحد الزمني",
      ca: "Límit de temps",
      "zh-CN": "时限",
      "zh-TW": "時限",
      hr: "Vremensko ograničenje",
      cs: "Časový limit",
      da: "Tidsgrænse",
      nl: "Tijdslimiet",
      en: "Time Limit",
      fi: "Määräaika",
      fr: "Limite de temps",
      de: "Zeitlimit",
      el: "Προθεσμία",
      he: "מגבלת זמן",
      hi: "समय सीमा",
      hu: "Időkorlát",
      id: "Batas waktu",
      it: "Limite di tempo",
      ja: "期限",
      ko: "시간 제한",
      ms: "Had Masa",
      no: "Tidsbegrensning",
      pl: "Limit czasu",
      pt: "Limite de tempo",
      ro: "Limită de timp",
      ru: "Лимит времени",
      sk: "Časový limit",
      es: "Límite de tiempo",
      sv: "Tidsgräns",
      th: "จำกัดเวลา",
      tr: "Zaman Sınırı",
      uk: "Обмеження часу",
      vi: "Giới hạn thời gian",
    },
    groupId: "timeLimit",
    parentCategoryId: "facebook",
    options: facebookDesktopGroups_TimeLimit,
  },
  {
    groupName: {
      ar: "الصفحة الرئيسية",
      ca: "Pàgina d'inici",
      "zh-CN": "主页",
      "zh-TW": "首頁",
      hr: "Početna stranica",
      cs: "Domovská stránka",
      da: "Hjemmeside",
      nl: "Startpagina",
      en: "Home Page",
      fi: "Kotisivu",
      fr: "Page d'accueil",
      de: "Startseite",
      el: "Αρχική Σελίδα",
      he: "דף הבית",
      hi: "होम पेज",
      hu: "Kezdőlap",
      id: "Halaman Beranda",
      it: "Pagina iniziale",
      ja: "ホームページ",
      ko: "홈 페이지",
      ms: "Halaman Utama",
      no: "Hjemmeside",
      pl: "Strona główna",
      pt: "Pagina inicial",
      ro: "Pagina principala",
      ru: "Домашняя страница",
      sk: "Domovská stránka",
      es: "Página de inicio",
      sv: "Hemsida",
      th: "หน้าแรก",
      tr: "Ana Sayfa",
      uk: "Домашня сторінка",
      vi: "Trang chủ",
    },
    groupId: "feed",
    parentCategoryId: "facebook",
    options: facebookDesktopGroups_Feed,
  },

  {
    groupName: {
      ar: "رأس",
      ca: "Capçalera",
      "zh-CN": "标头",
      "zh-TW": "標頭",
      hr: "Zaglavlje",
      cs: "Záhlaví",
      da: "Header",
      nl: "Koptekst",
      en: "Header",
      fi: "Otsikko",
      fr: "Entête",
      de: "Header",
      el: "Επί κεφαλής",
      he: "כּוֹתֶרֶת",
      hi: "हैडर",
      hu: "Fejléc",
      id: "Tajuk",
      it: "Intestazione",
      ja: "ヘッダ",
      ko: "머리글",
      ms: "Kepala",
      no: "Overskrift",
      pl: "Nagłówek",
      pt: "Cabeçalho",
      ro: "Antet",
      ru: "Заголовок",
      sk: "Hlavička",
      es: "Encabezamiento",
      sv: "Rubrik",
      th: "หัวข้อ",
      tr: "Başlık",
      uk: "Заголовок",
      vi: "Tiêu đề",
    },
    groupId: "header",
    parentCategoryId: "facebook",
    options: facebookDesktopGroups_Header,
  },

  {
    groupName: {
      ar: "شريط التنقل الأيسر",
      ca: "Barra de navegació esquerra",
      "zh-CN": "左侧导航栏",
      "zh-TW": "左側導覽列",
      hr: "Lijeva navigacijska traka",
      cs: "Levý navigační panel",
      da: "Venstre navigationslinje",
      nl: "Linker navigatiebalk",
      en: "Left Navigation Bar",
      fi: "Vasen navigointipalkki",
      fr: "Barre de navigation gauche",
      de: "Linke Navigationsleiste",
      el: "Αριστερή γραμμή πλοήγησης",
      he: "סרגל הניווט השמאלי",
      hi: "बायां नेविगेशन बार",
      hu: "Bal oldali navigációs sáv",
      id: "Bilah Navigasi Kiri",
      it: "Barra di navigazione sinistra",
      ja: "左側のナビゲーション バー",
      ko: "왼쪽 탐색 모음",
      ms: "Bar Navigasi Kiri",
      no: "Venstre navigasjonslinje",
      pl: "Lewy pasek nawigacyjny",
      pt: "Barra de navegação esquerda",
      ro: "Bara de navigare din stânga",
      ru: "Левая панель навигации",
      sk: "Ľavý navigačný panel",
      es: "Barra de navegación izquierda",
      sv: "Vänster navigeringsfält",
      th: "แถบนำทางด้านซ้าย",
      tr: "Sol Gezinti Çubuğu",
      uk: "Ліва панель навігації",
      vi: "Thanh điều hướng bên trái",
    },
    groupId: "leftNavigationBar",
    parentCategoryId: "facebook",
    options: facebookDesktopGroups_LeftNavigationBar,
  },

  {
    groupName: {
      ar: "الشريط الأيمن",
      ca: "Barra dreta",
      "zh-CN": "右栏",
      "zh-TW": "右欄",
      hr: "Desna traka",
      cs: "Pravá lišta",
      da: "Højre bjælke",
      nl: "Rechter balk",
      en: "Right Bar",
      fi: "Oikea baari",
      fr: "Barre de droite",
      de: "Rechte Leiste",
      el: "Δεξιά Μπάρα",
      he: "בר ימין",
      hi: "सही बार",
      hu: "Jobb bár",
      id: "Bilah Kanan",
      it: "Barra destra",
      ja: "右バー",
      ko: "오른쪽 막대",
      ms: "Bar Kanan",
      no: "Høyre stolpe",
      pl: "Prawy pasek",
      pt: "Barra Direita",
      ro: "Bara din dreapta",
      ru: "Правая панель",
      sk: "Pravá lišta",
      es: "Barra derecha",
      sv: "Höger bar",
      th: "แถบขวา",
      tr: "Sağ Çubuk",
      uk: "Права панель",
      vi: "Thanh bên phải",
    },
    groupId: "rightBar",
    parentCategoryId: "facebook",
    options: facebookDesktopGroups_RightBar,
  },

  {
    groupName: {
      ar: "آحرون",
      ca: "Altres",
      "zh-CN": "其他的",
      "zh-TW": "其他的",
      hr: "Drugi",
      cs: "Ostatní",
      da: "Andre",
      nl: "Anderen",
      en: "Others",
      fi: "Muut",
      fr: "Autres",
      de: "Andere",
      el: "Οι υπολοιποι",
      he: "אחרים",
      hi: "अन्य",
      hu: "Mások",
      id: "Yang lain",
      it: "Altri",
      ja: "その他",
      ko: "기타",
      ms: "Lain-lain",
      no: "Andre",
      pl: "Inni",
      pt: "Outros",
      ro: "Alții",
      ru: "Другие",
      sk: "Iní",
      es: "Otros",
      sv: "Andra",
      th: "คนอื่น",
      tr: "Diğerleri",
      uk: "Інші",
      vi: "Người khác",
    },
    groupId: "other",
    parentCategoryId: "facebook",
    options: facebookDesktopGroups_Other,
  },
];

// MARK: - Mobile Groups

const facebookMobileGroups_DisableSocialFocus = {
  type: "checkbox",
  name: {
    ar: "تعطيل التركيز الاجتماعي على الفيسبوك",
    ca: "Desactiveu SocialFocus a Facebook",
    "zh-CN": "在 Facebook 上禁用 SocialFocus",
    "zh-TW": "在 Facebook 上停用 SocialFocus",
    hr: "Onemogućite SocialFocus na Facebooku",
    cs: "Zakázat SocialFocus na Facebooku",
    da: "Deaktiver SocialFocus på Facebook",
    nl: "Schakel SocialFocus uit op Facebook",
    en: "Disable SocialFocus on Facebook",
    fi: "Poista SocialFocus käytöstä Facebookissa",
    fr: "Désactivez SocialFocus sur Facebook",
    de: "Deaktivieren Sie SocialFocus auf Facebook",
    el: "Απενεργοποιήστε το SocialFocus στο Facebook",
    he: "השבת את SocialFocus בפייסבוק",
    hi: "फेसबुक पर सोशलफोकस अक्षम करें",
    hu: "A SocialFocus letiltása a Facebookon",
    id: "Nonaktifkan Fokus Sosial di Facebook",
    it: "Disattiva SocialFocus su Facebook",
    ja: "Facebook で SocialFocus を無効にする",
    ko: "Facebook에서 SocialFocus 비활성화",
    ms: "Lumpuhkan SocialFocus pada Facebook",
    no: "Deaktiver SocialFocus på Facebook",
    pl: "Wyłącz SocialFocus na Facebooku",
    pt: "Desative o SocialFocus no Facebook",
    ro: "Dezactivează SocialFocus pe Facebook",
    ru: "Отключить SocialFocus на Facebook",
    sk: "Zakázať SocialFocus na Facebooku",
    es: "Deshabilitar SocialFocus en Facebook",
    sv: "Inaktivera SocialFocus på Facebook",
    th: "ปิดการใช้งาน SocialFocus บน Facebook",
    tr: "Facebook'ta SocialFocus'u devre dışı bırakın",
    uk: "Вимкніть SocialFocus у Facebook",
    vi: "Tắt SocialFocus trên Facebook",
  },
  id: "socialFocus_facebook_master_toggle",
  defaultValue: false,
};

const facebookMobileGroups_Essentials = [
  {
    type: "checkbox",
    name: {
      ar: "حظر الفيسبوك",
      ca: "Bloqueja Facebook",
      "zh-CN": "封锁脸书",
      "zh-TW": "封鎖臉書",
      hr: "Blokiraj Facebook",
      cs: "Blokovat Facebook",
      da: "Bloker Facebook",
      nl: "Blokkeer Facebook",
      en: "Block Facebook",
      fi: "Estä Facebook",
      fr: "Bloquer Facebook",
      de: "Facebook blockieren",
      el: "Αποκλεισμός του Facebook",
      he: "חסום את פייסבוק",
      hi: "फेसबुक को ब्लॉक करें",
      hu: "Facebook letiltása",
      id: "Blokir Facebook",
      it: "Blocca Facebook",
      ja: "Facebookをブロックする",
      ko: "페이스북 차단",
      ms: "Sekat Facebook",
      no: "Blokker Facebook",
      pl: "Zablokuj Facebooka",
      pt: "Bloquear Facebook",
      ro: "Blocați Facebook",
      ru: "Блокировать Facebook",
      sk: "Blokovať Facebook",
      es: "Bloquear facebook",
      sv: "Blockera Facebook",
      th: "บล็อกเฟสบุ๊ค",
      tr: "Facebook'u engelle",
      uk: "Заблокувати Facebook",
      vi: "Chặn Facebook",
    },
    id: "socialFocus_facebook_block_facebook",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "الوضع الرمادي",
      ca: "Mode gris",
      "zh-CN": "灰度模式",
      "zh-TW": "灰階模式",
      hr: "Sivi način rada",
      cs: "Šedý režim",
      da: "Grå tilstand",
      nl: "Grijze modus",
      en: "Gray Mode",
      fi: "Harmaa tila",
      fr: "Mode gris",
      de: "Graumodus",
      el: "Γκρι λειτουργία",
      he: "מצב אפור",
      hi: "ग्रे मोड",
      hu: "Szürke mód",
      id: "Modus Abu-abu",
      it: "Modalità grigia",
      ja: "グレーモード",
      ko: "그레이 모드",
      ms: "Mod Kelabu",
      no: "Grå modus",
      pl: "Tryb szary",
      pt: "Modo cinza",
      ro: "Modul gri",
      ru: "Серый режим",
      sk: "Šedý režim",
      es: "Modo gris",
      sv: "Grått läge",
      th: "โหมดสีเทา",
      tr: "Gri Mod",
      uk: "Сірий режим",
      vi: "Chế độ màu xám",
    },
    id: "socialFocus_facebook_gray_mode",
    defaultValue: false,
  },
];

const facebookMobileGroups_TimeLimit = [
  {
    type: "select",
    name: {
      ar: "الحد اليومي",
      ca: "Límit diari",
      "zh-CN": "每日限额",
      "zh-TW": "每日限額",
      hr: "Dnevni limit",
      cs: "Denní limit",
      da: "Daglig grænse",
      nl: "Dagelijkse limiet",
      en: "Daily Limit",
      fi: "Päivittäinen raja",
      fr: "Limite quotidienne",
      de: "Tageslimit",
      el: "Ημερήσιο Όριο",
      he: "מגבלה יומית",
      hi: "दैनिक सीमा",
      hu: "Napi limit",
      id: "Batas Harian",
      it: "Limite giornaliero",
      ja: "1日あたりの制限",
      ko: "일일 한도",
      ms: "Had Harian",
      no: "Daglig grense",
      pl: "Limit dzienny",
      pt: "Limite Diário",
      ro: "Limită zilnică",
      ru: "Дневной лимит",
      sk: "Denný limit",
      es: "Límite diario",
      sv: "Daglig gräns",
      th: "ขีดจำกัดรายวัน",
      tr: "Günlük Limit",
      uk: "Денний ліміт",
      vi: "Giới hạn hàng ngày",
    },
    id: "socialFocus_daily_limit",
    defaultValue: "noLimit",
    selects: [
      {
        name: {
          ar: "بلا حدود",
          ca: "Sense límits",
          "zh-CN": "没有限制",
          "zh-TW": "沒有限制",
          hr: "Bez ograničenja",
          cs: "Bez omezení",
          da: "Ingen grænser",
          nl: "Geen grenzen",
          en: "No Limits",
          fi: "Ei rajoja",
          fr: "Aucune limite",
          de: "Keine Grenzen",
          el: "Χωρίς όρια",
          he: "ללא גבולות",
          hi: "असीम",
          hu: "Nincs határ",
          id: "Tanpa Batas",
          it: "Nessun limite",
          ja: "制限なし",
          ko: "한계 없음",
          ms: "Tiada Had",
          no: "Ingen grenser",
          pl: "Bez ograniczeń",
          pt: "Sem Limites",
          ro: "Fără limite",
          ru: "Без ограничений",
          sk: "Žiadne limity",
          es: "Sin límites",
          sv: "Inga gränser",
          th: "ไม่มีขีดจำกัด",
          tr: "Sınır Yok",
          uk: "Без обмежень",
          vi: "Không có giới hạn",
        },
        id: "noLimit",
      },
    ],
  },
  {
    type: "checkbox",
    name: {
      ar: "عرض الموقت على الموقع",
      ca: "Mostra el temporitzador al lloc",
      "zh-CN": "现场显示计时器",
      "zh-TW": "現場顯示計時器",
      hr: "Prikaz mjerača vremena na licu mjesta",
      cs: "Zobrazit časovač na místě",
      da: "Vis timer på stedet",
      nl: "Timer op locatie weergeven",
      en: "Display Timer On Site",
      fi: "Näytä ajastin paikan päällä",
      fr: "Afficher la minuterie sur site",
      de: "Timer vor Ort anzeigen",
      el: "Εμφάνιση χρονοδιακόπτη στον ιστότοπο",
      he: "הצגת טיימר באתר",
      hi: "साइट पर टाइमर प्रदर्शित करें",
      hu: "Időzítő megjelenítése a helyszínen",
      id: "Tampilkan Timer Di Situs",
      it: "Visualizza il timer sul sito",
      ja: "オンサイトでタイマーを表示",
      ko: "사이트에 타이머 표시",
      ms: "Paparkan Pemasa Di Tapak",
      no: "Vis timer på stedet",
      pl: "Wyświetl timer na miejscu",
      pt: "Exibir temporizador no local",
      ro: "Afișează cronometrul la fața locului",
      ru: "Отображение таймера на месте",
      sk: "Zobraziť časovač na mieste",
      es: "Mostrar temporizador en el sitio",
      sv: "Visa timer på plats",
      th: "แสดงตัวจับเวลาบนเว็บไซต์",
      tr: "Zamanlayıcıyı Sitede Görüntüle",
      uk: "Відображення таймера на сайті",
      vi: "Hiển thị bộ đếm thời gian trên trang web",
    },
    id: "socialFocus_facebook_daily_limit_show_timer",
    defaultValue: false,
  },
];

const facebookMobileGroups_HomeFeed = [
  {
    type: "checkbox",
    name: {
      ar: "إخفاء موجز الصفحة الرئيسية",
      ca: "Amaga el feed d'inici",
      "zh-CN": "隐藏主页动态",
      "zh-TW": "隱藏主頁動態",
      hr: "Sakrij početnu stranicu",
      cs: "Skrýt domovský kanál",
      da: "Skjul hjemmefeed",
      nl: "Homefeed verbergen",
      en: "Hide Home Feed",
      fi: "Piilota kotisyöte",
      fr: "Masquer le flux d’accueil",
      de: "Home-Feed ausblenden",
      el: "Απόκρυψη αρχικής ροής",
      he: "הסתר עדכון ביתי",
      hi: "होम फ़ीड छिपाएँ",
      hu: "Home Feed elrejtése",
      id: "Sembunyikan Umpan Beranda",
      it: "Nascondi feed domestico",
      ja: "ホームフィードを隠す",
      ko: "홈 피드 숨기기",
      ms: "Sembunyikan Suapan Rumah",
      no: "Skjul hjemmefeed",
      pl: "Ukryj kanał główny",
      pt: "Ocultar feed inicial",
      ro: "Ascunde fluxul de acasă",
      ru: "Скрыть главную ленту",
      sk: "Skryť domovský kanál",
      es: "Ocultar feed de inicio",
      sv: "Dölj hemflöde",
      th: "ซ่อนฟีดหน้าแรก",
      tr: "Ana Sayfa Akışını Gizle",
      uk: "Приховати домашню стрічку",
      vi: "Ẩn nguồn cấp dữ liệu trang chủ",
    },
    id: "socialFocus_facebook_home_feed_hide_feed",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء قسم 'القصص'",
      ca: "Amaga la secció 'Històries'",
      "zh-CN": "隐藏“故事”部分",
      "zh-TW": "隱藏「故事」部分",
      hr: "Sakrij odjeljak 'Priče'",
      cs: "Skrýt sekci „Příběhy“",
      da: "Skjul afsnittet 'Historier'",
      nl: "Sectie 'Verhalen' verbergen",
      en: "Hide 'Stories' Section",
      fi: "Piilota Tarinat-osio",
      fr: "Masquer la section « Histoires »",
      de: "Abschnitt „Geschichten“ ausblenden",
      el: "Απόκρυψη ενότητας 'Ιστορίες'",
      he: "הסתר מדור 'סיפורים'",
      hi: "'कहानियाँ' अनुभाग छिपाएँ",
      hu: "A „Történetek” szakasz elrejtése",
      id: "Sembunyikan Bagian 'Cerita'",
      it: "Nascondi la sezione 'Storie'",
      ja: "「ストーリー」セクションを非表示にする",
      ko: "'스토리' 섹션 숨기기",
      ms: "Sembunyikan Bahagian 'Cerita'",
      no: "Skjul 'Stories'-delen",
      pl: "Ukryj sekcję „Historie”",
      pt: "Ocultar seção 'Histórias'",
      ro: "Ascundeți secțiunea „Povestiri”",
      ru: "Скрыть раздел «Истории»",
      sk: "Skryť sekciu „Príbehy“",
      es: "Ocultar la sección 'Historias'",
      sv: "Göm avsnittet 'Berättelser'",
      th: "ซ่อนส่วน 'เรื่องราว'",
      tr: "'Hikayeler' Bölümünü Gizle",
      uk: "Сховати розділ «Історії»",
      vi: "Ẩn phần 'Truyện'",
    },
    id: "socialFocus_facebook_feed_hide_section_stories",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء قسم 'البكرات ومقاطع الفيديو القصيرة'",
      ca: "Amaga la secció 'Reels i vídeos curts'",
      "zh-CN": "隐藏“卷轴和短视频”部分",
      "zh-TW": "隱藏“捲軸和短視頻”部分",
      hr: "Sakrij odjeljak 'Releji i kratki videozapisi'",
      cs: "Skryjte sekci 'Civky a krátká videa'",
      da: "Skjul sektionen 'Hjuler og korte videoer'",
      nl: "Sectie 'Reels en korte video's' verbergen",
      en: "Hide 'Reels and short videos' Section",
      fi: "Piilota Kelat ja lyhyet videot -osio",
      fr: "Masquer la section « Bobines et courtes vidéos »",
      de: "Abschnitt „Reels und kurze Videos“ ausblenden",
      el: "Απόκρυψη ενότητας 'Κολί και σύντομα βίντεο'",
      he: "הסתר את הקטע 'סלילים וסרטונים קצרים'",
      hi: "'रील और लघु वीडियो' अनुभाग छिपाएँ",
      hu: "A „Tekercsek és rövid videók” szakasz elrejtése",
      id: "Sembunyikan Bagian 'Gulungan dan video pendek'",
      it: "Nascondi la sezione 'Reels e brevi video'",
      ja: "「リールとショートビデオ」セクションを非表示にする",
      ko: "'릴 및 짧은 동영상' 섹션 숨기기",
      ms: "Sembunyikan Bahagian 'Kekili dan video pendek'",
      no: "Skjul delen 'Sneller og korte videoer'",
      pl: "Ukryj sekcję „Reklamy i krótkie filmy”",
      pt: "Ocultar a seção 'Momentos e vídeos curtos'",
      ro: "Ascundeți secțiunea „Role și videoclipuri scurte”",
      ru: "Скрыть раздел «Ролики и короткие видеоролики»",
      sk: "Skryť sekciu „Modely a krátke videá“",
      es: "Ocultar Sección 'Reels y vídeos cortos'",
      sv: "Göm sektionen 'Reels och korta videor'",
      th: "ซ่อนส่วน 'คลิปม้วนและวิดีโอสั้น'",
      tr: "'Makaralar ve kısa videolar' Bölümünü gizle",
      uk: "Сховати розділ «Котушки та короткі відео»",
      vi: "Ẩn phần 'Câu chuyện và video ngắn'",
    },
    id: "socialFocus_facebook_feed_hide_section_reels_and_short_videos",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء المشاركات الدعائية",
      ca: "Amaga les publicacions patrocinades",
      "zh-CN": "隐藏赞助帖子",
      "zh-TW": "隱藏贊助貼文",
      hr: "Sakrij sponzorirane postove",
      cs: "Skrýt sponzorované příspěvky",
      da: "Skjul sponsorerede indlæg",
      nl: "Gesponsorde berichten verbergen",
      en: "Hide Sponsored Posts",
      fi: "Piilota sponsoroidut viestit",
      fr: "Masquer les publications sponsorisées",
      de: "Gesponserte Beiträge ausblenden",
      el: "Απόκρυψη διαφημιζόμενων αναρτήσεων",
      he: "הסתר פוסטים ממומנים",
      hi: "प्रायोजित पोस्ट छिपाएँ",
      hu: "Szponzorált bejegyzések elrejtése",
      id: "Sembunyikan Postingan Bersponsor",
      it: "Nascondi post sponsorizzati",
      ja: "スポンサー付きの投稿を非表示にする",
      ko: "스폰서 게시물 숨기기",
      ms: "Sembunyikan Catatan Tajaan",
      no: "Skjul sponsede innlegg",
      pl: "Ukryj posty sponsorowane",
      pt: "Ocultar postagens patrocinadas",
      ro: "Ascundeți postările sponsorizate",
      ru: "Скрыть рекламные сообщения",
      sk: "Skryť sponzorované príspevky",
      es: "Ocultar publicaciones patrocinadas",
      sv: "Dölj sponsrade inlägg",
      th: "ซ่อนโพสต์ที่ได้รับการสนับสนุน",
      tr: "Sponsorlu Gönderileri Gizle",
      uk: "Приховати спонсоровані публікації",
      vi: "Ẩn bài viết được tài trợ",
    },
    id: "socialFocus_facebook_feed_hide_sponsored_posts",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء المشاركات من الأشخاص لمتابعتهم",
      ca: "Amaga les publicacions de les persones per seguir",
      "zh-CN": "隐藏要关注的人的帖子",
      "zh-TW": "隱藏要關注的人的帖子",
      hr: "Sakrij postove od osoba za praćenje",
      cs: "Skrýt příspěvky od lidí ke sledování",
      da: "Skjul indlæg fra personer at følge",
      nl: "Verberg berichten van mensen die u wilt volgen",
      en: "Hide Posts from People to Follow",
      fi: "Piilota viestit seurattavilta ihmisiltä",
      fr: "Masquer les publications des personnes à suivre",
      de: "Verstecken Sie Beiträge von Personen, denen Sie folgen möchten",
      el: "Απόκρυψη αναρτήσεων από άτομα προς παρακολούθηση",
      he: "הסתר פוסטים מאנשים לעקוב אחריהם",
      hi: "फ़ॉलो करने के लिए लोगों से पोस्ट छुपाएं",
      hu: "Bejegyzések elrejtése a követendő személyek közül",
      id: "Sembunyikan Postingan dari Orang untuk Diikuti",
      it: "Nascondi i post alle persone da seguire",
      ja: "フォローするユーザーの投稿を非表示にする",
      ko: "팔로우할 사람들의 게시물 숨기기",
      ms: "Sembunyikan Siaran daripada Orang untuk Diikuti",
      no: "Skjul innlegg fra personer å følge",
      pl: "Ukryj posty przed osobami, które chcesz obserwować",
      pt: "Ocultar postagens de pessoas para seguir",
      ro: "Ascunde postările de la persoanele de urmărit",
      ru: "Скрыть сообщения от людей, на которых можно подписаться",
      sk: "Skryť príspevky od ľudí na sledovanie",
      es: "Ocultar publicaciones de personas a seguir",
      sv: "Dölj inlägg från personer att följa",
      th: "ซ่อนโพสต์จากบุคคลที่จะติดตาม",
      tr: "Takip Edilecek Kişilerden Gönderileri Gizle",
      uk: "Приховайте публікації від людей, на яких слід стежити",
      vi: "Ẩn bài viết khỏi những người để theo dõi",
    },
    id: "socialFocus_facebook_feed_hide_posts_from_people_to_follow",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء قسم 'المجموعات المقترحة'",
      ca: "Amaga la secció 'Grups suggerits'",
      "zh-CN": "隐藏“建议的组”部分",
      "zh-TW": "隱藏「建議的群組」部分",
      hr: "Sakrij odjeljak 'Predložene grupe'",
      cs: "Skrýt sekci „Navrhované skupiny“",
      da: "Skjul sektionen 'Foreslåede grupper'",
      nl: "Sectie 'Voorgestelde groepen' verbergen",
      en: "Hide 'Suggested Groups' Section",
      fi: "Piilota Ehdotetut ryhmät -osio",
      fr: "Masquer la section « Groupes suggérés »",
      de: "Abschnitt „Vorgeschlagene Gruppen“ ausblenden",
      el: "Απόκρυψη ενότητας 'Προτεινόμενες ομάδες'",
      he: "הסתר את הקטע 'קבוצות מוצעות'",
      hi: "'सुझाए गए समूह' अनुभाग छिपाएँ",
      hu: "A „Javasolt csoportok” szakasz elrejtése",
      id: "Sembunyikan Bagian 'Grup yang Disarankan'",
      it: "Nascondi la sezione 'Gruppi suggeriti'",
      ja: "「推奨グループ」セクションを非表示にする",
      ko: "'추천 그룹' 섹션 숨기기",
      ms: "Sembunyikan Bahagian 'Kumpulan Cadangan'",
      no: "Skjul delen 'Foreslåtte grupper'",
      pl: "Ukryj sekcję „Sugerowane grupy”",
      pt: "Ocultar a seção 'Grupos sugeridos'",
      ro: "Ascundeți secțiunea „Grupuri sugerate”",
      ru: "Скрыть раздел «Предлагаемые группы»",
      sk: "Skryť sekciu „Navrhované skupiny“",
      es: "Ocultar la sección 'Grupos sugeridos'",
      sv: "Dölj avsnittet 'Föreslagna grupper'",
      th: "ซ่อนส่วน 'กลุ่มที่แนะนำ'",
      tr: "'Önerilen Gruplar' Bölümünü Gizle",
      uk: "Сховати розділ «Пропоновані групи»",
      vi: "Ẩn phần 'Nhóm được đề xuất'",
    },
    id: "socialFocus_facebook_home_feed_section_suggested_groups",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء قسم 'الأشخاص الذين قد تعرفهم'",
      ca: "Amaga la secció 'Persones que pots conèixer'",
      "zh-CN": "隐藏“您可能认识的人”部分",
      "zh-TW": "隱藏「您可能認識的人」部分",
      hr: "Sakrij odjeljak 'Osobe koje možda poznajete'",
      cs: "Skryjte sekci „Lidé, které možná znáte“",
      da: "Skjul sektionen 'Personer du måske kender'",
      nl: "Sectie 'Mensen die u misschien kent' verbergen",
      en: "Hide 'People You May Know' Section",
      fi: "Piilota 'Ihmiset, jotka saatat tuntea' -osio",
      fr: "Masquer la section « Personnes que vous connaissez peut-être »",
      de: "Abschnitt „Personen, die Sie vielleicht kennen“ ausblenden",
      el: "Απόκρυψη ενότητας 'Άτομα που μπορεί να γνωρίζετε'",
      he: "הסתר את הקטע 'אנשים שאתה עשוי להכיר'",
      hi: "'वे लोग जिन्हें आप जानते हों' अनुभाग छिपाएँ",
      hu: "Az „Emberek, akiket ismerhet” szakasz elrejtése",
      id: "Sembunyikan Bagian 'Orang yang Mungkin Anda Kenal'",
      it: "Nascondi la sezione 'Persone che potresti conoscere'",
      ja: "「知り合いかも知れません」セクションを非表示にする",
      ko: "'알 수도 있는 사람' 섹션 숨기기",
      ms: "Sembunyikan Bahagian 'Orang Yang Anda Mungkin Kenal'",
      no: "Skjul delen 'Folk du kanskje kjenner'",
      pl: "Ukryj sekcję „Osoby, które możesz znać”",
      pt: "Ocultar a seção 'Pessoas que você talvez conheça'",
      ro: "Ascundeți secțiunea „Persoane pe care le puteți cunoaște”",
      ru: "Скрыть раздел «Люди, которых вы можете знать»",
      sk: "Skryť sekciu „Ľudia, ktorých možno poznáte“",
      es: "Ocultar la sección 'Personas que quizás conozcas'",
      sv: "Dölj avsnittet 'Personer du kanske känner'",
      th: "ซ่อนส่วน 'บุคคลที่คุณอาจรู้จัก'",
      tr: "'Tanıyor Olabileceğiniz Kişiler' Bölümünü Gizle",
      uk: "Сховати розділ «Люди, яких ви можете знати»",
      vi: "Ẩn phần 'Những người bạn có thể biết'",
    },
    id: "socialFocus_facebook_home_feed_hide_sect_people",
    defaultValue: false,
  },
];

const facebookMobileGroups_HeaderNavigation = [
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'الصفحة الرئيسية'",
      ca: "Amaga el botó 'Inici'",
      "zh-CN": "隐藏“主页”按钮",
      "zh-TW": "隱藏「首頁」按鈕",
      hr: "Sakrij gumb 'Početna'",
      cs: "Skrýt tlačítko „Domů“",
      da: "Skjul 'Hjem'-knap",
      nl: "Verberg de 'Home'-knop",
      en: "Hide 'Home' Button",
      fi: "Piilota Koti-painike",
      fr: "Masquer le bouton « Accueil »",
      de: "„Home“-Schaltfläche ausblenden",
      el: "Απόκρυψη κουμπιού 'Αρχική σελίδα'",
      he: "הסתר את כפתור 'בית'",
      hi: "'होम' बटन छिपाएँ",
      hu: "A „Kezdőlap” gomb elrejtése",
      id: "Sembunyikan Tombol 'Beranda'",
      it: "Nascondi il pulsante 'Home'",
      ja: "「ホーム」ボタンを隠す",
      ko: "'홈' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Home'",
      no: "Skjul 'Hjem'-knappen",
      pl: "Ukryj przycisk „Strona główna”",
      pt: "Ocultar o botão 'Home'",
      ro: "Ascundeți butonul „Acasă”",
      ru: "Скрыть кнопку «Домой»",
      sk: "Skryť tlačidlo „Domov“",
      es: "Ocultar el botón 'Inicio'",
      sv: "Dölj 'Hem'-knappen",
      th: "ซ่อนปุ่ม 'หน้าแรก'",
      tr: "'Ana Sayfa' Düğmesini Gizle",
      uk: "Сховати кнопку «Додому»",
      vi: "Ẩn nút 'Trang chủ'",
    },
    id: "socialFocus_facebook_headerNav_hide_button_home",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'الأصدقاء'",
      ca: "Amaga el botó 'Amics'",
      "zh-CN": "隐藏“好友”按钮",
      "zh-TW": "隱藏「好友」按鈕",
      hr: "Sakrij gumb 'Prijatelji'",
      cs: "Skrýt tlačítko „Přátelé“",
      da: "Skjul 'Venner'-knap",
      nl: "Knop 'Vrienden' verbergen",
      en: "Hide 'Friends' Button",
      fi: "Piilota Ystävät-painike",
      fr: "Masquer le bouton « Amis »",
      de: "Schaltfläche „Freunde“ ausblenden",
      el: "Απόκρυψη κουμπιού «Φίλοι»",
      he: "הסתר כפתור 'חברים'",
      hi: "'मित्र' बटन छिपाएँ",
      hu: "A 'Barátok' gomb elrejtése",
      id: "Sembunyikan Tombol 'Teman'",
      it: "Nascondi il pulsante 'Amici'",
      ja: "「友達」ボタンを非表示にする",
      ko: "'친구' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Kawan'",
      no: "Skjul 'Venner'-knappen",
      pl: "Ukryj przycisk „Znajomi”",
      pt: "Ocultar botão ‘Amigos’",
      ro: "Ascundeți butonul „Prieteni”",
      ru: "Скрыть кнопку «Друзья»",
      sk: "Skryť tlačidlo „Priatelia“",
      es: "Ocultar el botón 'Amigos'",
      sv: "Dölj 'Vänner'-knappen",
      th: "ซ่อนปุ่ม 'เพื่อน'",
      tr: "'Arkadaşlar' Düğmesini Gizle",
      uk: "Приховати кнопку «Друзі»",
      vi: "Ẩn nút 'Bạn bè'",
    },
    id: "socialFocus_facebook_headerNav_hide_button_friends",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'الماسنجر'",
      ca: "Amaga el botó 'Messenger'",
      "zh-CN": "隐藏“信使”按钮",
      "zh-TW": "隱藏「信差」按鈕",
      hr: "Sakrij gumb 'Messenger'",
      cs: "Skrýt tlačítko 'Messenger'",
      da: "Skjul 'Messenger'-knap",
      nl: "Knop 'Messenger' verbergen",
      en: "Hide 'Messenger' Button",
      fi: "Piilota 'Messenger'-painike",
      fr: "Masquer le bouton « Messenger »",
      de: "Schaltfläche „Messenger“ ausblenden",
      el: "Απόκρυψη κουμπιού «Αγγελιοφόρος»",
      he: "הסתר את לחצן 'מסנג'ר'",
      hi: "'मैसेंजर' बटन छिपाएँ",
      hu: "A „Messenger” gomb elrejtése",
      id: "Sembunyikan Tombol 'Messenger'",
      it: "Nascondi il pulsante 'Messaggero'",
      ja: "「メッセンジャー」ボタンを非表示にする",
      ko: "'메신저' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Messenger'",
      no: "Skjul 'Messenger'-knappen",
      pl: "Ukryj przycisk „Posłaniec”",
      pt: "Ocultar botão 'Messenger'",
      ro: "Ascundeți butonul „Messenger”",
      ru: "Скрыть кнопку «Мессенджер»",
      sk: "Skryť tlačidlo „Messenger“",
      es: "Ocultar el botón 'Messenger'",
      sv: "Dölj 'Messenger'-knappen",
      th: "ซ่อนปุ่ม 'Messenger'",
      tr: "'Messenger' Düğmesini Gizle",
      uk: "Сховати кнопку «Месенджер»",
      vi: "Ẩn nút 'Messenger'",
    },
    id: "socialFocus_facebook_headerNav_hide_button_messanger",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'الفيديوهات'",
      ca: "Amaga el botó 'Vídeos'",
      "zh-CN": "隐藏“视频”按钮",
      "zh-TW": "隱藏“視訊”按鈕",
      hr: "Sakrij gumb 'Videozapisi'",
      cs: "Skrýt tlačítko „Videa“",
      da: "Skjul knappen 'Videoer'",
      nl: "Knop 'Video's' verbergen",
      en: "Hide 'Videos' Button",
      fi: "Piilota 'Videot' -painike",
      fr: "Masquer le bouton « Vidéos »",
      de: "Schaltfläche „Videos“ ausblenden",
      el: "Κουμπί απόκρυψης 'Βίντεο'",
      he: "הסתר כפתור 'סרטונים'",
      hi: "'वीडियो' बटन छिपाएँ",
      hu: "A „Videók” gomb elrejtése",
      id: "Sembunyikan Tombol 'Video'",
      it: "Nascondi il pulsante 'Video'",
      ja: "「ビデオ」ボタンを非表示にする",
      ko: "'동영상' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Video'",
      no: "Skjul 'Videoer'-knappen",
      pl: "Ukryj przycisk „Wideo”",
      pt: "Ocultar botão 'Vídeos'",
      ro: "Ascundeți butonul „Videoclipuri”",
      ru: "Скрыть кнопку «Видео»",
      sk: "Skryť tlačidlo „Videá“",
      es: "Ocultar el botón 'Vídeos'",
      sv: "Dölj 'Videos'-knappen",
      th: "ซ่อนปุ่ม 'วิดีโอ'",
      tr: "'Videolar' Düğmesini Gizle",
      uk: "Сховати кнопку «Відео»",
      vi: "Ẩn nút 'Video'",
    },
    id: "socialFocus_facebook_headerNav_hide_button_videos",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'الإخطارات'",
      ca: "Amaga el botó 'Notificacions'",
      "zh-CN": "隐藏“通知”按钮",
      "zh-TW": "隱藏「通知」按鈕",
      hr: "Sakrij gumb 'Obavijesti'",
      cs: "Skrýt tlačítko 'Oznámení'",
      da: "Skjul knappen 'Meddelelser'",
      nl: "Knop 'Meldingen' verbergen",
      en: "Hide 'Notifications' Button",
      fi: "Piilota Ilmoitukset-painike",
      fr: "Masquer le bouton « Notifications »",
      de: "Schaltfläche „Benachrichtigungen“ ausblenden",
      el: "Απόκρυψη κουμπιού «Ειδοποιήσεις»",
      he: "הסתר את לחצן 'התראות'",
      hi: "'सूचनाएँ' बटन छिपाएँ",
      hu: "Az „Értesítések” gomb elrejtése",
      id: "Sembunyikan Tombol 'Pemberitahuan'",
      it: "Nascondi il pulsante 'Notifiche'",
      ja: "「通知」ボタンを非表示にする",
      ko: "'알림' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Pemberitahuan'",
      no: "Skjul 'Varslinger'-knappen",
      pl: "Ukryj przycisk „Powiadomienia”",
      pt: "Ocultar botão 'Notificações'",
      ro: "Ascundeți butonul „Notificări”",
      ru: "Скрыть кнопку «Уведомления»",
      sk: "Skryť tlačidlo „Upozornenia“",
      es: "Ocultar el botón 'Notificaciones'",
      sv: "Dölj knappen 'Meddelanden'",
      th: "ซ่อนปุ่ม 'การแจ้งเตือน'",
      tr: "'Bildirimler' Düğmesini Gizle",
      uk: "Сховати кнопку «Сповіщення»",
      vi: "Ẩn nút 'Thông báo'",
    },
    id: "socialFocus_facebook_headerNav_hide_button_notifications",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'السوق'",
      ca: "Amaga el botó 'Mercat'",
      "zh-CN": "隐藏“市场”按钮",
      "zh-TW": "隱藏“市場”按鈕",
      hr: "Sakrij gumb 'Tržište'",
      cs: "Skrýt tlačítko „Tržiště“",
      da: "Skjul 'Markedsplads'-knap",
      nl: "Knop 'Marktplaats' verbergen",
      en: "Hide 'Marketplace' Button",
      fi: "Piilota Marketplace-painike",
      fr: "Masquer le bouton « Place de marché »",
      de: "Schaltfläche „Marktplatz“ ausblenden",
      el: "Απόκρυψη κουμπιού 'Marketplace'",
      he: "הסתר את לחצן 'מרקטפלייס'",
      hi: "'मार्केटप्लेस' बटन छिपाएँ",
      hu: "A „Piactér” gomb elrejtése",
      id: "Sembunyikan Tombol 'Marketplace'",
      it: "Nascondi il pulsante 'Mercato'",
      ja: "「マーケットプレイス」ボタンを隠す",
      ko: "'마켓플레이스' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Marketplace'",
      no: "Skjul 'Markedsplass'-knappen",
      pl: "Ukryj przycisk „Rynek”",
      pt: "Ocultar botão 'Marketplace'",
      ro: "Ascundeți butonul „Piață”",
      ru: "Скрыть кнопку «Торговая площадка»",
      sk: "Skryť tlačidlo Trhovisko",
      es: "Ocultar el botón 'Mercado'",
      sv: "Dölj 'Marknadsplats'-knappen",
      th: "ซ่อนปุ่ม 'ตลาดกลาง'",
      tr: "'Pazaryeri' Düğmesini Gizle",
      uk: "Сховати кнопку 'Биржа'",
      vi: "Ẩn nút 'Thị trường'",
    },
    id: "socialFocus_facebook_headerNav_hide_button_marketplace",
    defaultValue: false,
  },
];

// MARK: - Mobile Other

const facebookMobileGroups_Other = [
  {
    type: "checkbox",
    name: {
      ar: "إخفاء فتح في شعار التطبيق",
      ca: "Amaga el bàner obert a l'aplicació",
      "zh-CN": "隐藏在应用程序中打开的横幅",
      "zh-TW": "隱藏在應用程式中開啟的橫幅",
      hr: "Sakrij natpis Otvori u aplikaciji",
      cs: "Skrýt Otevřít v banneru aplikace",
      da: "Skjul åben i app-banner",
      nl: "Open in app-banner verbergen",
      en: "Hide Open In App Banner",
      fi: "Piilota Avaa sovelluksessa -banneri",
      fr: "Masquer la bannière Ouvrir dans l'application",
      de: "Offenes In-App-Banner ausblenden",
      el: "Απόκρυψη Banner Open In App",
      he: "הסתר באנר של פתח באפליקציה",
      hi: "ऐप बैनर में खुला छिपाएँ",
      hu: "A Megnyitás az alkalmazásban szalaghirdetés elrejtése",
      id: "Sembunyikan Spanduk Buka Di Aplikasi",
      it: "Nascondi banner Apri nell'app",
      ja: "「アプリ内で開く」バナーを非表示にする",
      ko: "앱에서 열려 있는 배너 숨기기",
      ms: "Sembunyikan Sepanduk Buka Dalam Apl",
      no: "Skjul Åpne i app-banner",
      pl: "Ukryj baner Otwórz w aplikacji",
      pt: "Ocultar banner aberto no aplicativo",
      ro: "Ascunde bannerul Open In App",
      ru: "Скрыть открытие в баннере приложения",
      sk: "Skryť nápis Otvoriť v aplikácii",
      es: "Ocultar banner Abrir en aplicación",
      sv: "Dölj öppna i app-banner",
      th: "ซ่อนเปิดในแบนเนอร์แอป",
      tr: "Uygulamada Aç Banner'ını Gizle",
      uk: "Приховати банер «Відкрити в програмі»",
      vi: "Ẩn biểu ngữ mở trong ứng dụng",
    },
    id: "socialFocus_facebook_mobile_other_hide_open_in_app_banner",
    defaultValue: false,
  },
];

// MARK: - Mobile Builder

const facebookMobileGroups = [
  {
    groupName: {
      ar: "",
      ca: "",
      "zh-CN": "",
      "zh-TW": "",
      hr: "",
      cs: "",
      da: "",
      nl: "",
      en: "",
      fi: "",
      fr: "",
      de: "",
      el: "",
      he: "",
      hi: "",
      hu: "",
      id: "",
      it: "",
      ja: "",
      ko: "",
      ms: "",
      no: "",
      pl: "",
      pt: "",
      ro: "",
      ru: "",
      sk: "",
      es: "",
      sv: "",
      th: "",
      tr: "",
      uk: "",
      vi: "",
    },
    groupId: "disableSocialFocus",
    parentCategoryId: "facebook",
    options: [facebookMobileGroups_DisableSocialFocus],
  },
  {
    groupName: {
      ar: "أساسيات",
      ca: "Essencials",
      "zh-CN": "必需品",
      "zh-TW": "必需品",
      hr: "Osnove",
      cs: "Essentials",
      da: "Essentialer",
      nl: "Essentiële zaken",
      en: "Essentials",
      fi: "Essentials",
      fr: "Essentiel",
      de: "Wesentliches",
      el: "Βασικά",
      he: "יסודות",
      hi: "अनिवार्य",
      hu: "Essentials",
      id: "Penting",
      it: "Elementi essenziali",
      ja: "必需品",
      ko: "골자",
      ms: "Perkara-perkara penting",
      no: "Essensielle",
      pl: "Elementy zasadnicze",
      pt: "Fundamentos",
      ro: "Esențiale",
      ru: "Основы",
      sk: "Essentials",
      es: "Esenciales",
      sv: "Essentials",
      th: "สิ่งจำเป็น",
      tr: "Temeller",
      uk: "Основи",
      vi: "Yếu tố cần thiết",
    },
    groupId: "essentials",
    parentCategoryId: "facebook",
    options: facebookMobileGroups_Essentials,
  },
  {
    groupName: {
      ar: "الحد الزمني",
      ca: "Límit de temps",
      "zh-CN": "时限",
      "zh-TW": "時限",
      hr: "Vremensko ograničenje",
      cs: "Časový limit",
      da: "Tidsgrænse",
      nl: "Tijdslimiet",
      en: "Time Limit",
      fi: "Määräaika",
      fr: "Limite de temps",
      de: "Zeitlimit",
      el: "Προθεσμία",
      he: "מגבלת זמן",
      hi: "समय सीमा",
      hu: "Időkorlát",
      id: "Batas waktu",
      it: "Limite di tempo",
      ja: "期限",
      ko: "시간 제한",
      ms: "Had Masa",
      no: "Tidsbegrensning",
      pl: "Limit czasu",
      pt: "Limite de tempo",
      ro: "Limită de timp",
      ru: "Лимит времени",
      sk: "Časový limit",
      es: "Límite de tiempo",
      sv: "Tidsgräns",
      th: "จำกัดเวลา",
      tr: "Zaman Sınırı",
      uk: "Обмеження часу",
      vi: "Giới hạn thời gian",
    },
    groupId: "timeLimit",
    parentCategoryId: "facebook",
    options: facebookMobileGroups_TimeLimit,
  },
  {
    groupName: {
      ar: "الصفحة الرئيسية",
      ca: "Pàgina d'inici",
      "zh-CN": "主页",
      "zh-TW": "首頁",
      hr: "Početna stranica",
      cs: "Domovská stránka",
      da: "Hjemmeside",
      nl: "Startpagina",
      en: "Home Page",
      fi: "Kotisivu",
      fr: "Page d'accueil",
      de: "Startseite",
      el: "Αρχική Σελίδα",
      he: "דף הבית",
      hi: "होम पेज",
      hu: "Kezdőlap",
      id: "Halaman Beranda",
      it: "Pagina iniziale",
      ja: "ホームページ",
      ko: "홈 페이지",
      ms: "Halaman Utama",
      no: "Hjemmeside",
      pl: "Strona główna",
      pt: "Pagina inicial",
      ro: "Pagina principala",
      ru: "Домашняя страница",
      sk: "Domovská stránka",
      es: "Página de inicio",
      sv: "Hemsida",
      th: "หน้าแรก",
      tr: "Ana Sayfa",
      uk: "Домашня сторінка",
      vi: "Trang chủ",
    },
    groupId: "homeFeed",
    parentCategoryId: "facebook",
    options: facebookMobileGroups_HomeFeed,
  },
  {
    groupName: {
      ar: "رأس",
      ca: "Capçalera",
      "zh-CN": "标头",
      "zh-TW": "標頭",
      hr: "Zaglavlje",
      cs: "Záhlaví",
      da: "Header",
      nl: "Koptekst",
      en: "Header",
      fi: "Otsikko",
      fr: "Entête",
      de: "Header",
      el: "Επί κεφαλής",
      he: "כּוֹתֶרֶת",
      hi: "हैडर",
      hu: "Fejléc",
      id: "Tajuk",
      it: "Intestazione",
      ja: "ヘッダ",
      ko: "머리글",
      ms: "Kepala",
      no: "Overskrift",
      pl: "Nagłówek",
      pt: "Cabeçalho",
      ro: "Antet",
      ru: "Заголовок",
      sk: "Hlavička",
      es: "Encabezamiento",
      sv: "Rubrik",
      th: "หัวข้อ",
      tr: "Başlık",
      uk: "Заголовок",
      vi: "Tiêu đề",
    },
    groupId: "headerNavigation",
    parentCategoryId: "facebook",
    options: facebookMobileGroups_HeaderNavigation,
  },
  {
    groupName: {
      ar: "آحرون",
      ca: "Altres",
      "zh-CN": "其他的",
      "zh-TW": "其他的",
      hr: "Drugi",
      cs: "Ostatní",
      da: "Andre",
      nl: "Anderen",
      en: "Others",
      fi: "Muut",
      fr: "Autres",
      de: "Andere",
      el: "Οι υπολοιποι",
      he: "אחרים",
      hi: "अन्य",
      hu: "Mások",
      id: "Yang lain",
      it: "Altri",
      ja: "その他",
      ko: "기타",
      ms: "Lain-lain",
      no: "Andre",
      pl: "Inni",
      pt: "Outros",
      ro: "Alții",
      ru: "Другие",
      sk: "Iní",
      es: "Otros",
      sv: "Andra",
      th: "คนอื่น",
      tr: "Diğerleri",
      uk: "Інші",
      vi: "Người khác",
    },
    groupId: "other",
    parentCategoryId: "facebook",
    options: facebookMobileGroups_Other,
    // options: facebookDesktopGroups_Other,
  },
];
