const pinterestDesktopGroups_DisableSocialFocus = {
  type: "checkbox",
  name: {
    ar: "تعطيل التركيز الاجتماعي على موقع Pinterest",
    ca: "Desactiveu SocialFocus a Pinterest",
    "zh-CN": "在 Pinterest 上禁用 SocialFocus",
    "zh-TW": "在 Pinterest 上停用 SocialFocus",
    hr: "Onemogućite SocialFocus na Pinterestu",
    cs: "Deaktivujte SocialFocus na Pinterestu",
    da: "Deaktiver SocialFocus på Pinterest",
    nl: "Schakel SocialFocus uit op Pinterest",
    en: "Disable SocialFocus on Pinterest",
    fi: "Poista SocialFocus käytöstä Pinterestissä",
    fr: "Désactivez SocialFocus sur Pinterest",
    de: "Deaktivieren Sie SocialFocus auf Pinterest",
    el: "Απενεργοποιήστε το SocialFocus στο Pinterest",
    he: "השבת את SocialFocus ב-Pinterest",
    hi: "Pinterest पर SocialFocus अक्षम करें",
    hu: "A SocialFocus letiltása a Pinteresten",
    id: "Nonaktifkan Fokus Sosial di Pinterest",
    it: "Disabilita SocialFocus su Pinterest",
    ja: "Pinterest で SocialFocus を無効にする",
    ko: "Pinterest에서 SocialFocus 비활성화",
    ms: "Lumpuhkan SocialFocus pada Pinterest",
    no: "Deaktiver SocialFocus på Pinterest",
    pl: "Wyłącz SocialFocus na Pintereście",
    pt: "Desative o SocialFocus no Pinterest",
    ro: "Dezactivează SocialFocus pe Pinterest",
    ru: "Отключить SocialFocus на Pinterest",
    sk: "Zakázať SocialFocus na Pintereste",
    es: "Deshabilitar SocialFocus en Pinterest",
    sv: "Inaktivera SocialFocus på Pinterest",
    th: "ปิดการใช้งาน SocialFocus บน Pinterest",
    tr: "Pinterest'te SocialFocus'u devre dışı bırakın",
    uk: "Вимкніть SocialFocus на Pinterest",
    vi: "Tắt SocialFocus trên Pinterest",
  },
  id: "socialFocus_pinterest_master_toggle",
  defaultValue: false,
};

const pinterestDesktopGroups_Essentials = [
  {
    type: "checkbox",
    name: {
      ar: "منع بينتريست",
      ca: "Bloqueja Pinterest",
      "zh-CN": "阻止 Pinterest",
      "zh-TW": "阻止 Pinterest",
      hr: "Blokiraj Pinterest",
      cs: "Blokovat Pinterest",
      da: "Bloker Pinterest",
      nl: "Blokkeer Pinterest",
      en: "Block Pinterest",
      fi: "Estä Pinterest",
      fr: "Bloquer Pinterest",
      de: "Pinterest blockieren",
      el: "Αποκλεισμός του Pinterest",
      he: "חסום את פינטרסט",
      hi: "Pinterest को ब्लॉक करें",
      hu: "Blokkolja a Pinterestet",
      id: "Blokir Pinterest",
      it: "Blocca Pinterest",
      ja: "Pinterest をブロックする",
      ko: "핀터레스트 차단",
      ms: "Sekat Pinterest",
      no: "Blokker Pinterest",
      pl: "Zablokuj Pinteresta",
      pt: "Bloquear Pinterest",
      ro: "Blocați Pinterest",
      ru: "Заблокировать Pinterest",
      sk: "Blokovať Pinterest",
      es: "Bloquear Pinterest",
      sv: "Blockera Pinterest",
      th: "บล็อก Pinterest",
      tr: "Pinterest'i engelle",
      uk: "Заблокувати Pinterest",
      vi: "Chặn Pinterest",
    },
    id: "socialFocus_pinterest_block_pinterest",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "الوضع الرمادي",
      ca: "Mode gris",
      "zh-CN": "灰度模式",
      "zh-TW": "灰階模式",
      hr: "Sivi način rada",
      cs: "Šedý režim",
      da: "Grå tilstand",
      nl: "Grijze modus",
      en: "Gray Mode",
      fi: "Harmaa tila",
      fr: "Mode gris",
      de: "Graumodus",
      el: "Γκρι λειτουργία",
      he: "מצב אפור",
      hi: "ग्रे मोड",
      hu: "Szürke mód",
      id: "Modus Abu-abu",
      it: "Modalità grigia",
      ja: "グレーモード",
      ko: "그레이 모드",
      ms: "Mod Kelabu",
      no: "Grå modus",
      pl: "Tryb szary",
      pt: "Modo cinza",
      ro: "Modul gri",
      ru: "Серый режим",
      sk: "Šedý režim",
      es: "Modo gris",
      sv: "Grått läge",
      th: "โหมดสีเทา",
      tr: "Gri Mod",
      uk: "Сірий режим",
      vi: "Chế độ màu xám",
    },
    id: "socialFocus_pinterest_gray_mode",
    defaultValue: false,
  },
];

const pinterestDesktopGroups_TimeLimit = [
  {
    type: "select",
    name: {
      ar: "الحد اليومي",
      ca: "Límit diari",
      "zh-CN": "每日限额",
      "zh-TW": "每日限額",
      hr: "Dnevni limit",
      cs: "Denní limit",
      da: "Daglig grænse",
      nl: "Dagelijkse limiet",
      en: "Daily Limit",
      fi: "Päivittäinen raja",
      fr: "Limite quotidienne",
      de: "Tageslimit",
      el: "Ημερήσιο Όριο",
      he: "מגבלה יומית",
      hi: "दैनिक सीमा",
      hu: "Napi limit",
      id: "Batas Harian",
      it: "Limite giornaliero",
      ja: "1日あたりの制限",
      ko: "일일 한도",
      ms: "Had Harian",
      no: "Daglig grense",
      pl: "Limit dzienny",
      pt: "Limite Diário",
      ro: "Limită zilnică",
      ru: "Дневной лимит",
      sk: "Denný limit",
      es: "Límite diario",
      sv: "Daglig gräns",
      th: "ขีดจำกัดรายวัน",
      tr: "Günlük Limit",
      uk: "Денний ліміт",
      vi: "Giới hạn hàng ngày",
    },
    id: "socialFocus_daily_limit",
    defaultValue: "noLimit",
    selects: [
      {
        name: {
          ar: "بلا حدود",
          ca: "Sense límits",
          "zh-CN": "没有限制",
          "zh-TW": "沒有限制",
          hr: "Bez ograničenja",
          cs: "Bez omezení",
          da: "Ingen grænser",
          nl: "Geen grenzen",
          en: "No Limits",
          fi: "Ei rajoja",
          fr: "Aucune limite",
          de: "Keine Grenzen",
          el: "Χωρίς όρια",
          he: "ללא גבולות",
          hi: "असीम",
          hu: "Nincs határ",
          id: "Tanpa Batas",
          it: "Nessun limite",
          ja: "制限なし",
          ko: "한계 없음",
          ms: "Tiada Had",
          no: "Ingen grenser",
          pl: "Bez ograniczeń",
          pt: "Sem Limites",
          ro: "Fără limite",
          ru: "Без ограничений",
          sk: "Žiadne limity",
          es: "Sin límites",
          sv: "Inga gränser",
          th: "ไม่มีขีดจำกัด",
          tr: "Sınır Yok",
          uk: "Без обмежень",
          vi: "Không có giới hạn",
        },
        id: "noLimit",
      },
    ],
  },
  {
    type: "checkbox",
    name: {
      ar: "عرض الموقت على الموقع",
      ca: "Mostra el temporitzador al lloc",
      "zh-CN": "现场显示计时器",
      "zh-TW": "現場顯示計時器",
      hr: "Prikaz mjerača vremena na licu mjesta",
      cs: "Zobrazit časovač na místě",
      da: "Vis timer på stedet",
      nl: "Timer op locatie weergeven",
      en: "Display Timer On Site",
      fi: "Näytä ajastin paikan päällä",
      fr: "Afficher la minuterie sur site",
      de: "Timer vor Ort anzeigen",
      el: "Εμφάνιση χρονοδιακόπτη στον ιστότοπο",
      he: "הצגת טיימר באתר",
      hi: "साइट पर टाइमर प्रदर्शित करें",
      hu: "Időzítő megjelenítése a helyszínen",
      id: "Tampilkan Timer Di Situs",
      it: "Visualizza il timer sul sito",
      ja: "オンサイトでタイマーを表示",
      ko: "사이트에 타이머 표시",
      ms: "Paparkan Pemasa Di Tapak",
      no: "Vis timer på stedet",
      pl: "Wyświetl timer na miejscu",
      pt: "Exibir temporizador no local",
      ro: "Afișează cronometrul la fața locului",
      ru: "Отображение таймера на месте",
      sk: "Zobraziť časovač na mieste",
      es: "Mostrar temporizador en el sitio",
      sv: "Visa timer på plats",
      th: "แสดงตัวจับเวลาบนเว็บไซต์",
      tr: "Zamanlayıcıyı Sitede Görüntüle",
      uk: "Відображення таймера на сайті",
      vi: "Hiển thị bộ đếm thời gian trên trang web",
    },
    id: "socialFocus_pinterest_daily_limit_show_timer_draggable",
    defaultValue: false,
  },
];

const pinterestDesktopGroups_Others = [
  {
    type: "checkbox",
    name: {
      ar: "إخفاء اقتراحات البحث",
      ca: "Amaga els suggeriments de cerca",
      "zh-CN": "隐藏搜索建议",
      "zh-TW": "隱藏搜尋建議",
      hr: "Sakrij prijedloge pretraživanja",
      cs: "Skrýt návrhy vyhledávání",
      da: "Skjul søgeforslag",
      nl: "Zoeksuggesties verbergen",
      en: "Hide Search Suggestions",
      fi: "Piilota hakuehdotukset",
      fr: "Masquer les suggestions de recherche",
      de: "Suchvorschläge ausblenden",
      el: "Απόκρυψη προτάσεων αναζήτησης",
      he: "הסתר הצעות חיפוש",
      hi: "खोज सुझाव छिपाएँ",
      hu: "Keresési javaslatok elrejtése",
      id: "Sembunyikan Saran Pencarian",
      it: "Nascondi suggerimenti di ricerca",
      ja: "検索候補を非表示にする",
      ko: "검색 제안 숨기기",
      ms: "Sembunyikan Cadangan Carian",
      no: "Skjul søkeforslag",
      pl: "Ukryj sugestie wyszukiwania",
      pt: "Ocultar sugestões de pesquisa",
      ro: "Ascundeți sugestiile de căutare",
      ru: "Скрыть поисковые предложения",
      sk: "Skryť návrhy vyhľadávania",
      es: "Ocultar sugerencias de búsqueda",
      sv: "Dölj sökförslag",
      th: "ซ่อนคำแนะนำการค้นหา",
      tr: "Arama Önerilerini Gizle",
      uk: "Приховати підказки пошуку",
      vi: "Ẩn đề xuất tìm kiếm",
    },
    id: "socialFocus_pinterest_hide_search_suggestion",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء دبابيس الفيديو",
      ca: "Amaga els pins de vídeo",
      "zh-CN": "隐藏视频 Pin 图",
      "zh-TW": "隱藏影片 Pin 圖",
      hr: "Sakrij video pribadače",
      cs: "Skrýt video piny",
      da: "Skjul videonåle",
      nl: "Videopinnen verbergen",
      en: "Hide Video Pins",
      fi: "Piilota videopinnit",
      fr: "Masquer les épingles vidéo",
      de: "Video-Pins ausblenden",
      el: "Απόκρυψη καρφιτσών βίντεο",
      he: "הסתר סיכות וידאו",
      hi: "वीडियो पिन छिपाएँ",
      hu: "Video Pins elrejtése",
      id: "Sembunyikan Pin Video",
      it: "Nascondi Pin video",
      ja: "ビデオピンを非表示にする",
      ko: "비디오 핀 숨기기",
      ms: "Sembunyikan Pin Video",
      no: "Skjul videonåler",
      pl: "Ukryj piny wideo",
      pt: "Ocultar pinos de vídeo",
      ro: "Ascundeți pinii video",
      ru: "Скрыть видео-пины",
      sk: "Skryť video piny",
      es: "Ocultar pines de vídeo",
      sv: "Dölj videonålar",
      th: "ซ่อนพินวิดีโอ",
      tr: "Video Pinlerini Gizle",
      uk: "Приховати закріплення відео",
      vi: "Ẩn ghim video",
    },
    id: "socialFocus_pinterest_hide_video_pins",
    defaultValue: false,
  },
];

// MARK: - Desktop Builder

const pinterestDesktopGroups = [
  {
    groupName: {
      ar: "",
      ca: "",
      "zh-CN": "",
      "zh-TW": "",
      hr: "",
      cs: "",
      da: "",
      nl: "",
      en: "",
      fi: "",
      fr: "",
      de: "",
      el: "",
      he: "",
      hi: "",
      hu: "",
      id: "",
      it: "",
      ja: "",
      ko: "",
      ms: "",
      no: "",
      pl: "",
      pt: "",
      ro: "",
      ru: "",
      sk: "",
      es: "",
      sv: "",
      th: "",
      tr: "",
      uk: "",
      vi: "",
    },
    groupId: "disableSocialFocus",
    parentCategoryId: "pinterest",
    options: [pinterestDesktopGroups_DisableSocialFocus],
  },
  {
    groupName: {
      ar: "أساسيات",
      ca: "Essencials",
      "zh-CN": "必需品",
      "zh-TW": "必需品",
      hr: "Osnove",
      cs: "Essentials",
      da: "Essentialer",
      nl: "Essentiële zaken",
      en: "Essentials",
      fi: "Essentials",
      fr: "Essentiel",
      de: "Wesentliches",
      el: "Βασικά",
      he: "יסודות",
      hi: "अनिवार्य",
      hu: "Essentials",
      id: "Penting",
      it: "Elementi essenziali",
      ja: "必需品",
      ko: "골자",
      ms: "Perkara-perkara penting",
      no: "Essensielle",
      pl: "Elementy zasadnicze",
      pt: "Fundamentos",
      ro: "Esențiale",
      ru: "Основы",
      sk: "Essentials",
      es: "Esenciales",
      sv: "Essentials",
      th: "สิ่งจำเป็น",
      tr: "Temeller",
      uk: "Основи",
      vi: "Yếu tố cần thiết",
    },
    groupId: "essentials",
    parentCategoryId: "pinterest",
    options: pinterestDesktopGroups_Essentials,
  },
  {
    groupName: {
      ar: "الحد الزمني",
      ca: "Límit de temps",
      "zh-CN": "时限",
      "zh-TW": "時限",
      hr: "Vremensko ograničenje",
      cs: "Časový limit",
      da: "Tidsgrænse",
      nl: "Tijdslimiet",
      en: "Time Limit",
      fi: "Määräaika",
      fr: "Limite de temps",
      de: "Zeitlimit",
      el: "Προθεσμία",
      he: "מגבלת זמן",
      hi: "समय सीमा",
      hu: "Időkorlát",
      id: "Batas waktu",
      it: "Limite di tempo",
      ja: "期限",
      ko: "시간 제한",
      ms: "Had Masa",
      no: "Tidsbegrensning",
      pl: "Limit czasu",
      pt: "Limite de tempo",
      ro: "Limită de timp",
      ru: "Лимит времени",
      sk: "Časový limit",
      es: "Límite de tiempo",
      sv: "Tidsgräns",
      th: "จำกัดเวลา",
      tr: "Zaman Sınırı",
      uk: "Обмеження часу",
      vi: "Giới hạn thời gian",
    },
    groupId: "timeLimit",
    parentCategoryId: "pinterest",
    options: pinterestDesktopGroups_TimeLimit,
  },
  {
    groupName: {
      ar: "آحرون",
      ca: "Altres",
      "zh-CN": "其他的",
      "zh-TW": "其他的",
      hr: "Drugi",
      cs: "Ostatní",
      da: "Andre",
      nl: "Anderen",
      en: "Others",
      fi: "Muut",
      fr: "Autres",
      de: "Andere",
      el: "Οι υπολοιποι",
      he: "אחרים",
      hi: "अन्य",
      hu: "Mások",
      id: "Yang lain",
      it: "Altri",
      ja: "その他",
      ko: "기타",
      ms: "Lain-lain",
      no: "Andre",
      pl: "Inni",
      pt: "Outros",
      ro: "Alții",
      ru: "Другие",
      sk: "Iní",
      es: "Otros",
      sv: "Andra",
      th: "คนอื่น",
      tr: "Diğerleri",
      uk: "Інші",
      vi: "Người khác",
    },
    groupId: "other",
    parentCategoryId: "pinterest",
    options: pinterestDesktopGroups_Others,
  },
];

const pinterestMobileGroups_DisableSocialFocus = {
  type: "checkbox",
  name: {
    ar: "تعطيل التركيز الاجتماعي على موقع Pinterest",
    ca: "Desactiveu SocialFocus a Pinterest",
    "zh-CN": "在 Pinterest 上禁用 SocialFocus",
    "zh-TW": "在 Pinterest 上停用 SocialFocus",
    hr: "Onemogućite SocialFocus na Pinterestu",
    cs: "Deaktivujte SocialFocus na Pinterestu",
    da: "Deaktiver SocialFocus på Pinterest",
    nl: "Schakel SocialFocus uit op Pinterest",
    en: "Disable SocialFocus on Pinterest",
    fi: "Poista SocialFocus käytöstä Pinterestissä",
    fr: "Désactivez SocialFocus sur Pinterest",
    de: "Deaktivieren Sie SocialFocus auf Pinterest",
    el: "Απενεργοποιήστε το SocialFocus στο Pinterest",
    he: "השבת את SocialFocus ב-Pinterest",
    hi: "Pinterest पर SocialFocus अक्षम करें",
    hu: "A SocialFocus letiltása a Pinteresten",
    id: "Nonaktifkan Fokus Sosial di Pinterest",
    it: "Disabilita SocialFocus su Pinterest",
    ja: "Pinterest で SocialFocus を無効にする",
    ko: "Pinterest에서 SocialFocus 비활성화",
    ms: "Lumpuhkan SocialFocus pada Pinterest",
    no: "Deaktiver SocialFocus på Pinterest",
    pl: "Wyłącz SocialFocus na Pintereście",
    pt: "Desative o SocialFocus no Pinterest",
    ro: "Dezactivează SocialFocus pe Pinterest",
    ru: "Отключить SocialFocus на Pinterest",
    sk: "Zakázať SocialFocus na Pintereste",
    es: "Deshabilitar SocialFocus en Pinterest",
    sv: "Inaktivera SocialFocus på Pinterest",
    th: "ปิดการใช้งาน SocialFocus บน Pinterest",
    tr: "Pinterest'te SocialFocus'u devre dışı bırakın",
    uk: "Вимкніть SocialFocus на Pinterest",
    vi: "Tắt SocialFocus trên Pinterest",
  },
  id: "socialFocus_pinterest_master_toggle",
  defaultValue: false,
};

const pinterestMobileGroups_Essentials = [
  {
    type: "checkbox",
    name: {
      ar: "منع بينتريست",
      ca: "Bloqueja Pinterest",
      "zh-CN": "阻止 Pinterest",
      "zh-TW": "阻止 Pinterest",
      hr: "Blokiraj Pinterest",
      cs: "Blokovat Pinterest",
      da: "Bloker Pinterest",
      nl: "Blokkeer Pinterest",
      en: "Block Pinterest",
      fi: "Estä Pinterest",
      fr: "Bloquer Pinterest",
      de: "Pinterest blockieren",
      el: "Αποκλεισμός του Pinterest",
      he: "חסום את פינטרסט",
      hi: "Pinterest को ब्लॉक करें",
      hu: "Blokkolja a Pinterestet",
      id: "Blokir Pinterest",
      it: "Blocca Pinterest",
      ja: "Pinterest をブロックする",
      ko: "핀터레스트 차단",
      ms: "Sekat Pinterest",
      no: "Blokker Pinterest",
      pl: "Zablokuj Pinteresta",
      pt: "Bloquear Pinterest",
      ro: "Blocați Pinterest",
      ru: "Заблокировать Pinterest",
      sk: "Blokovať Pinterest",
      es: "Bloquear Pinterest",
      sv: "Blockera Pinterest",
      th: "บล็อก Pinterest",
      tr: "Pinterest'i engelle",
      uk: "Заблокувати Pinterest",
      vi: "Chặn Pinterest",
    },
    id: "socialFocus_pinterest_block_pinterest",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "الوضع الرمادي",
      ca: "Mode gris",
      "zh-CN": "灰度模式",
      "zh-TW": "灰階模式",
      hr: "Sivi način rada",
      cs: "Šedý režim",
      da: "Grå tilstand",
      nl: "Grijze modus",
      en: "Gray Mode",
      fi: "Harmaa tila",
      fr: "Mode gris",
      de: "Graumodus",
      el: "Γκρι λειτουργία",
      he: "מצב אפור",
      hi: "ग्रे मोड",
      hu: "Szürke mód",
      id: "Modus Abu-abu",
      it: "Modalità grigia",
      ja: "グレーモード",
      ko: "그레이 모드",
      ms: "Mod Kelabu",
      no: "Grå modus",
      pl: "Tryb szary",
      pt: "Modo cinza",
      ro: "Modul gri",
      ru: "Серый режим",
      sk: "Šedý režim",
      es: "Modo gris",
      sv: "Grått läge",
      th: "โหมดสีเทา",
      tr: "Gri Mod",
      uk: "Сірий режим",
      vi: "Chế độ màu xám",
    },
    id: "socialFocus_pinterest_gray_mode",
    defaultValue: false,
  },
];

const pinterestMobileGroups_TimeLimit = [
  {
    type: "select",
    name: {
      ar: "الحد اليومي",
      ca: "Límit diari",
      "zh-CN": "每日限额",
      "zh-TW": "每日限額",
      hr: "Dnevni limit",
      cs: "Denní limit",
      da: "Daglig grænse",
      nl: "Dagelijkse limiet",
      en: "Daily Limit",
      fi: "Päivittäinen raja",
      fr: "Limite quotidienne",
      de: "Tageslimit",
      el: "Ημερήσιο Όριο",
      he: "מגבלה יומית",
      hi: "दैनिक सीमा",
      hu: "Napi limit",
      id: "Batas Harian",
      it: "Limite giornaliero",
      ja: "1日あたりの制限",
      ko: "일일 한도",
      ms: "Had Harian",
      no: "Daglig grense",
      pl: "Limit dzienny",
      pt: "Limite Diário",
      ro: "Limită zilnică",
      ru: "Дневной лимит",
      sk: "Denný limit",
      es: "Límite diario",
      sv: "Daglig gräns",
      th: "ขีดจำกัดรายวัน",
      tr: "Günlük Limit",
      uk: "Денний ліміт",
      vi: "Giới hạn hàng ngày",
    },
    id: "socialFocus_daily_limit",
    defaultValue: "noLimit",
    selects: [
      {
        name: {
          ar: "بلا حدود",
          ca: "Sense límits",
          "zh-CN": "没有限制",
          "zh-TW": "沒有限制",
          hr: "Bez ograničenja",
          cs: "Bez omezení",
          da: "Ingen grænser",
          nl: "Geen grenzen",
          en: "No Limits",
          fi: "Ei rajoja",
          fr: "Aucune limite",
          de: "Keine Grenzen",
          el: "Χωρίς όρια",
          he: "ללא גבולות",
          hi: "असीम",
          hu: "Nincs határ",
          id: "Tanpa Batas",
          it: "Nessun limite",
          ja: "制限なし",
          ko: "한계 없음",
          ms: "Tiada Had",
          no: "Ingen grenser",
          pl: "Bez ograniczeń",
          pt: "Sem Limites",
          ro: "Fără limite",
          ru: "Без ограничений",
          sk: "Žiadne limity",
          es: "Sin límites",
          sv: "Inga gränser",
          th: "ไม่มีขีดจำกัด",
          tr: "Sınır Yok",
          uk: "Без обмежень",
          vi: "Không có giới hạn",
        },
        id: "noLimit",
      },
    ],
  },
  {
    type: "checkbox",
    name: {
      ar: "عرض الموقت على الموقع",
      ca: "Mostra el temporitzador al lloc",
      "zh-CN": "现场显示计时器",
      "zh-TW": "現場顯示計時器",
      hr: "Prikaz mjerača vremena na licu mjesta",
      cs: "Zobrazit časovač na místě",
      da: "Vis timer på stedet",
      nl: "Timer op locatie weergeven",
      en: "Display Timer On Site",
      fi: "Näytä ajastin paikan päällä",
      fr: "Afficher la minuterie sur site",
      de: "Timer vor Ort anzeigen",
      el: "Εμφάνιση χρονοδιακόπτη στον ιστότοπο",
      he: "הצגת טיימר באתר",
      hi: "साइट पर टाइमर प्रदर्शित करें",
      hu: "Időzítő megjelenítése a helyszínen",
      id: "Tampilkan Timer Di Situs",
      it: "Visualizza il timer sul sito",
      ja: "オンサイトでタイマーを表示",
      ko: "사이트에 타이머 표시",
      ms: "Paparkan Pemasa Di Tapak",
      no: "Vis timer på stedet",
      pl: "Wyświetl timer na miejscu",
      pt: "Exibir temporizador no local",
      ro: "Afișează cronometrul la fața locului",
      ru: "Отображение таймера на месте",
      sk: "Zobraziť časovač na mieste",
      es: "Mostrar temporizador en el sitio",
      sv: "Visa timer på plats",
      th: "แสดงตัวจับเวลาบนเว็บไซต์",
      tr: "Zamanlayıcıyı Sitede Görüntüle",
      uk: "Відображення таймера на сайті",
      vi: "Hiển thị bộ đếm thời gian trên trang web",
    },
    id: "socialFocus_pinterest_daily_limit_show_timer",
    defaultValue: false,
  },
];

const pinterestMobileGroups_Others = [
  {
    type: "checkbox",
    name: {
      ar: "إخفاء اقتراحات البحث",
      ca: "Amaga els suggeriments de cerca",
      "zh-CN": "隐藏搜索建议",
      "zh-TW": "隱藏搜尋建議",
      hr: "Sakrij prijedloge pretraživanja",
      cs: "Skrýt návrhy vyhledávání",
      da: "Skjul søgeforslag",
      nl: "Zoeksuggesties verbergen",
      en: "Hide Search Suggestions",
      fi: "Piilota hakuehdotukset",
      fr: "Masquer les suggestions de recherche",
      de: "Suchvorschläge ausblenden",
      el: "Απόκρυψη προτάσεων αναζήτησης",
      he: "הסתר הצעות חיפוש",
      hi: "खोज सुझाव छिपाएँ",
      hu: "Keresési javaslatok elrejtése",
      id: "Sembunyikan Saran Pencarian",
      it: "Nascondi suggerimenti di ricerca",
      ja: "検索候補を非表示にする",
      ko: "검색 제안 숨기기",
      ms: "Sembunyikan Cadangan Carian",
      no: "Skjul søkeforslag",
      pl: "Ukryj sugestie wyszukiwania",
      pt: "Ocultar sugestões de pesquisa",
      ro: "Ascundeți sugestiile de căutare",
      ru: "Скрыть поисковые предложения",
      sk: "Skryť návrhy vyhľadávania",
      es: "Ocultar sugerencias de búsqueda",
      sv: "Dölj sökförslag",
      th: "ซ่อนคำแนะนำการค้นหา",
      tr: "Arama Önerilerini Gizle",
      uk: "Приховати підказки пошуку",
      vi: "Ẩn đề xuất tìm kiếm",
    },
    id: "socialFocus_pinterest_hide_search_suggestion",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء دبابيس الفيديو",
      ca: "Amaga els pins de vídeo",
      "zh-CN": "隐藏视频 Pin 图",
      "zh-TW": "隱藏影片 Pin 圖",
      hr: "Sakrij video pribadače",
      cs: "Skrýt video piny",
      da: "Skjul videonåle",
      nl: "Videopinnen verbergen",
      en: "Hide Video Pins",
      fi: "Piilota videopinnit",
      fr: "Masquer les épingles vidéo",
      de: "Video-Pins ausblenden",
      el: "Απόκρυψη καρφιτσών βίντεο",
      he: "הסתר סיכות וידאו",
      hi: "वीडियो पिन छिपाएँ",
      hu: "Video Pins elrejtése",
      id: "Sembunyikan Pin Video",
      it: "Nascondi Pin video",
      ja: "ビデオピンを非表示にする",
      ko: "비디오 핀 숨기기",
      ms: "Sembunyikan Pin Video",
      no: "Skjul videonåler",
      pl: "Ukryj piny wideo",
      pt: "Ocultar pinos de vídeo",
      ro: "Ascundeți pinii video",
      ru: "Скрыть видео-пины",
      sk: "Skryť video piny",
      es: "Ocultar pines de vídeo",
      sv: "Dölj videonålar",
      th: "ซ่อนพินวิดีโอ",
      tr: "Video Pinlerini Gizle",
      uk: "Приховати закріплення відео",
      vi: "Ẩn ghim video",
    },
    id: "socialFocus_pinterest_hide_video_pins",
    defaultValue: false,
  },
];

// MARK: - Mobile Builder

const pinterestMobileGroups = [
  {
    groupName: {
      ar: "",
      ca: "",
      "zh-CN": "",
      "zh-TW": "",
      hr: "",
      cs: "",
      da: "",
      nl: "",
      en: "",
      fi: "",
      fr: "",
      de: "",
      el: "",
      he: "",
      hi: "",
      hu: "",
      id: "",
      it: "",
      ja: "",
      ko: "",
      ms: "",
      no: "",
      pl: "",
      pt: "",
      ro: "",
      ru: "",
      sk: "",
      es: "",
      sv: "",
      th: "",
      tr: "",
      uk: "",
      vi: "",
    },
    groupId: "disableSocialFocus",
    parentCategoryId: "pinterest",
    options: [pinterestMobileGroups_DisableSocialFocus],
  },
  {
    groupName: {
      ar: "أساسيات",
      ca: "Essencials",
      "zh-CN": "必需品",
      "zh-TW": "必需品",
      hr: "Osnove",
      cs: "Essentials",
      da: "Essentialer",
      nl: "Essentiële zaken",
      en: "Essentials",
      fi: "Essentials",
      fr: "Essentiel",
      de: "Wesentliches",
      el: "Βασικά",
      he: "יסודות",
      hi: "अनिवार्य",
      hu: "Essentials",
      id: "Penting",
      it: "Elementi essenziali",
      ja: "必需品",
      ko: "골자",
      ms: "Perkara-perkara penting",
      no: "Essensielle",
      pl: "Elementy zasadnicze",
      pt: "Fundamentos",
      ro: "Esențiale",
      ru: "Основы",
      sk: "Essentials",
      es: "Esenciales",
      sv: "Essentials",
      th: "สิ่งจำเป็น",
      tr: "Temeller",
      uk: "Основи",
      vi: "Yếu tố cần thiết",
    },
    groupId: "essentials",
    parentCategoryId: "pinterest",
    options: pinterestMobileGroups_Essentials,
  },
  {
    groupName: {
      ar: "الحد الزمني",
      ca: "Límit de temps",
      "zh-CN": "时限",
      "zh-TW": "時限",
      hr: "Vremensko ograničenje",
      cs: "Časový limit",
      da: "Tidsgrænse",
      nl: "Tijdslimiet",
      en: "Time Limit",
      fi: "Määräaika",
      fr: "Limite de temps",
      de: "Zeitlimit",
      el: "Προθεσμία",
      he: "מגבלת זמן",
      hi: "समय सीमा",
      hu: "Időkorlát",
      id: "Batas waktu",
      it: "Limite di tempo",
      ja: "期限",
      ko: "시간 제한",
      ms: "Had Masa",
      no: "Tidsbegrensning",
      pl: "Limit czasu",
      pt: "Limite de tempo",
      ro: "Limită de timp",
      ru: "Лимит времени",
      sk: "Časový limit",
      es: "Límite de tiempo",
      sv: "Tidsgräns",
      th: "จำกัดเวลา",
      tr: "Zaman Sınırı",
      uk: "Обмеження часу",
      vi: "Giới hạn thời gian",
    },
    groupId: "timeLimit",
    parentCategoryId: "pinterest",
    options: pinterestMobileGroups_TimeLimit,
  },
  {
    groupName: {
      ar: "آحرون",
      ca: "Altres",
      "zh-CN": "其他的",
      "zh-TW": "其他的",
      hr: "Drugi",
      cs: "Ostatní",
      da: "Andre",
      nl: "Anderen",
      en: "Others",
      fi: "Muut",
      fr: "Autres",
      de: "Andere",
      el: "Οι υπολοιποι",
      he: "אחרים",
      hi: "अन्य",
      hu: "Mások",
      id: "Yang lain",
      it: "Altri",
      ja: "その他",
      ko: "기타",
      ms: "Lain-lain",
      no: "Andre",
      pl: "Inni",
      pt: "Outros",
      ro: "Alții",
      ru: "Другие",
      sk: "Iní",
      es: "Otros",
      sv: "Andra",
      th: "คนอื่น",
      tr: "Diğerleri",
      uk: "Інші",
      vi: "Người khác",
    },
    groupId: "other",
    parentCategoryId: "pinterest",
    options: pinterestMobileGroups_Others,
  },
];
