// [snowpack] add styles to the page (skip if no document exists)
if (typeof document !== 'undefined') {
  const code = ".input-container[data-v-58982e92] {\n  display: flex;\n  align-items: center;\n  width: max-content;\n  gap: 0.8rem;\n}\n.input-container--column[data-v-58982e92] {\n  flex-direction: column;\n  max-width: 100%;\n}\nhtml:not(.light) .input-container--column .input[data-v-58982e92] {\n  background-color: hsl(var(--clr-white));\n  border: 1px solid hsl(var(--clr-black), 0.4);\n}\nhtml:not(.light) .input-container--column .input__input[data-v-58982e92] {\n  color: hsl(var(--clr-black));\n}\nhtml:not(.light) .input-container--column .input__input[data-v-58982e92]::placeholder {\n  color: hsl(var(--clr-black), 0.5);\n}\n.input[data-v-58982e92] {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  width: 300px;\n  height: 60px;\n  border-radius: 12px;\n  background-color: hsl(var(--clr-grey));\n  border: 1px solid hsl(var(--clr-state, var(--clr-grey)), 0.4);\n}\n.input--correct[data-v-58982e92] {\n  --clr-state: var(--clr-primary);\n}\n.input--warn[data-v-58982e92] {\n  --clr-state: var(--clr-warning);\n}\n.input--false[data-v-58982e92] {\n  --clr-state: var(--clr-alert);\n}\n.input[data-v-58982e92]:hover, .input[data-v-58982e92]:focus-within {\n  border: 1px solid hsl(var(--clr-state, var(--clr-white)), 0.8);\n}\n.input[data-v-58982e92]::before {\n  content: \"\";\n  width: 1px;\n  height: 50%;\n  background-color: hsl(var(--clr-state, var(--clr-grey)));\n  margin-left: 0.5rem;\n}\n.input__input[data-v-58982e92] {\n  color: hsl(var(--clr-white));\n  background-color: inherit;\n  border: none;\n  margin: 0 0.5rem;\n  height: 100%;\n}\n.input__input[data-v-58982e92]:focus {\n  outline: none;\n}\n.input__input[data-v-58982e92]::placeholder {\n  color: hsl(var(--clr-white), 0.5);\n}\n.input__icon[data-v-58982e92] {\n  height: 28px;\n  width: 28px;\n  color: hsl(var(--clr-state, var(--clr--grey)));\n  margin-right: 0.3rem;\n  opacity: 0;\n}\n.input__icon--visible[data-v-58982e92] {\n  opacity: 1;\n}\n.light .input[data-v-58982e92] {\n  background-color: hsl(var(--clr-black));\n  color: hsl(var(--clr-white));\n}";

  const styleEl = document.createElement("style");
  const codeEl = document.createTextNode(code);
  styleEl.type = 'text/css';
  styleEl.appendChild(codeEl);
  document.head.appendChild(styleEl);
}