((twod, k) => { if(window[k]) return; window[k] = true;(()=>{"use strict";function e(e,t,n,o,s,r,i){try{var c=r(e,i),a=Ct(c,"value")}catch(e){return void n(e)}Ct(c,"done")?t(a):on(new sn((e=>e(a))),o,s)}function t(t){const n=function(){var n=this,o=arguments;return new sn((function(s,r){function i(t){e(a,s,r,i,c,rn,t)}function c(t){e(a,s,r,i,c,cn,t)}var a=Pt(t,n,o);i(void 0)}))};return $t(n,"apply",(function(e,t){return Pt(n,e,t)})),n}function n(e,t){let n,o=!0;return"boolean"==typeof e?(o=e,n=t):n=e,Tn((e=>{const t=fn(ht.document)
;"interactive"==t||"complete"==t?(n&&n(),e()):Cn.addEventListener("DOMContentLoaded",(()=>{n&&n(),e()}),Dt({capture:o,once:!0}))}))}const o=["browser","chrome"],s=e=>{const t=Object.call,n=t.bind(t),o=Object.assign,s=Object.getOwnPropertyDescriptor,r=Object.getPrototypeOf,i=e=>o({__proto__:null},e),c=r(function*(){}());return i({sourceWindow:e,cSO:i,F_c:n,F_a:Object.apply,F_b:Object.bind,F_tS:Function.toString,A_fE:[].forEach,A_so:[].some,A_sh:[].shift,A_j:[].join,A_iO:[].indexOf,
A_iA:Array.isArray,O_a:o,O_k:Object.keys,O_v:Object.values,O_dP:Object.defineProperties,O_dPy:Object.defineProperty,O_hOP:Object.hasOwnProperty,O_gOPN:Object.getOwnPropertyNames,O_gOPD:s,O_gOPDs:Object.getOwnPropertyDescriptors,O_gPO:r,O_tS:{}.toString,J_p:JSON.parse,J_s:JSON.stringify,M_f:Math.floor,M_r:Math.random,M_m:Math.max,M_mi:Math.min,N_tS:(0).toString,N_MSI:Number.MAX_SAFE_INTEGER,P_t:Promise.prototype.then,P_c:Promise.prototype.catch,P_co:Promise.prototype.constructor,G_n:c.next,
G_t:c.throw,R_rABS:FileReader.prototype.readAsBinaryString,R_rAT:FileReader.prototype.readAsText,R_r:s(FileReader.prototype,"result").get,R_enq:e.ReadableStreamDefaultController?e.ReadableStreamDefaultController.prototype.enqueue:null,R_cl:e.ReadableStreamDefaultController?e.ReadableStreamDefaultController.prototype.close:null,S_fCC:String.fromCharCode,S_sl:"".slice,S_su:"".substr,S_sp_nr:"".split,S_iO:"".indexOf,S_tr:"".trim,S_r_nr:"".replace,S_rA_nr:"".replaceAll,S_cCA:"".charCodeAt,
S_tLC:"".toLowerCase,S_tUC:"".toUpperCase,Y_tST:Symbol.toStringTag,Y_unsc:Symbol.unscopables,USP_tS:URLSearchParams.prototype.toString,D_pFS:DOMParser.prototype.parseFromString,U_cOU:URL.createObjectURL,U_rOU:URL.revokeObjectURL,X_o:XMLHttpRequest.prototype.open,X_pSD:XMLHttpRequest.prototype.DONE,X_pSH:XMLHttpRequest.prototype.HEADERS_RECEIVED,X_pSL:XMLHttpRequest.prototype.LOADING,X_pSO:XMLHttpRequest.prototype.OPENED,X_pSU:XMLHttpRequest.prototype.UNSENT,X_s:XMLHttpRequest.prototype.send,
D_n:Date.now,I_tS:e=>""+e,E_r:Element.prototype.remove,E_s:Element.prototype.setAttribute,E_rA:Element.prototype.removeAttribute,D_cS:s(Document.prototype,"currentScript").get,D_gRS:s(Document.prototype,"readyState").get,D_cE:Document.prototype.createElementNS,D_gEBT:Document.prototype.getElementsByTagName,M_rT:s(MouseEvent.prototype,"relatedTarget").get,C_d:s(CustomEvent.prototype,"detail").get,P_p:s(PageTransitionEvent.prototype,"persisted").get,C_pA:CustomEvent.prototype.AT_TARGET,
M_d:MutationObserver.prototype.disconnect,W_aEL:addEventListener,W_rEL:removeEventListener,parseInt,parseFloat,CustomEvent,CompositionEvent,KeyboardEvent,MouseEvent,MutationObserver,console:Object.assign({},console),Error,Uint8Array,Blob,ReadableStream,Number,String,Proxy,Window,FileReader,DOMParser,XMLHttpRequest,Function,RegExp,Promise,encodeURIComponent,decodeURIComponent,encodeURI,decodeURI,escape,unescape,atob,btoa,setTimeout,clearTimeout,setInterval,clearInterval,postMessage,dispatchEvent,
alert,prompt,confirm,close,getElementById:e.Document.prototype.getElementById,createEvent:e.Document.prototype.createEvent,createElement:e.Document.prototype.createElement})},r="vault"in twod;if(r&&void 0===twod.vault)throw"Invalid vault"
;const i=twod.vault=twod.vault||s(twod.unsafeWindow),{cSO:c,F_c:a,F_a:d,F_b:l,F_tS:u,A_fE:p,A_so:g,A_sh:m,A_j:f,A_iO:h,A_iA:v,O_a:_,O_k:b,O_v:w,O_dP:y,O_dPy:M,O_hOP:x,O_gOPN:L,O_gOPD:E,O_gOPDs:S,O_gPO:O,O_tS:I,J_p:R,J_s:j,M_f:P,M_r:D,M_m:$,M_mi:C,N_tS:T,N_MSI:A,P_t:U,P_c:k,P_co:B,G_n:F,G_t:X,R_rABS:N,R_rAT:q,R_r:W,R_enq:H,R_cl:J,S_fCC:G,S_sl:K,S_su:Y,S_iO:z,S_sp_nr:V,S_tr:Q,S_rA_nr:Z,S_cCA:ee,S_tLC:te,S_tUC:ne,Y_tST:oe,Y_unsc:se,D_pFS:re,D_cS:ie,D_gRS:ce,D_cE:ae,D_gEBT:de,E_r:le,E_s:ue,E_rA:pe,C_pA:ge,M_d:me,C_d:fe,P_p:he,M_rT:ve,U_cOU:_e,U_rOU:be,USP_tS:we,X_o:ye,X_s:Me,X_pSD:xe,X_pSH:Le,X_pSL:Ee,X_pSO:Se,X_pSU:Oe,D_n:Ie,I_tS:Re,W_aEL:je,W_rEL:Pe,parseInt:De,parseFloat:$e,console:Ce,encodeURIComponent:Te,decodeURIComponent:Ae,encodeURI:Ue,decodeURI:ke,escape:Be,unescape:Fe,atob:Xe,btoa:Ne,postMessage:qe,dispatchEvent:We,alert:He,prompt:Je,confirm:Ge,close:Ke,getElementById:Ye,createEvent:ze,createElement:Ve,CustomEvent:Qe,CompositionEvent:Ze,KeyboardEvent:et,MouseEvent:tt,MutationObserver:nt,Uint8Array:ot,FileReader:st,DOMParser:rt,XMLHttpRequest:it,Function:ct,RegExp:at,Blob:dt,ReadableStream:lt,Number:ut,String:pt,Proxy:gt,Window:mt}=i,ft=twod,{unsafeWindow:ht,unsafeThis:vt}=ft,_t=a,bt=d,wt=b,yt=w,Mt=_,xt=M,Lt=L,Et=E,St=O,Ot=v,It=D,Rt=$,jt=C,Pt=(e,t,n)=>_t(bt,e,t,n),Dt=c,$t=(e,t,n)=>(xt(e,t,Dt({
value:n,configurable:!0,enumerable:!0,writable:!0})),e),Ct=(e,t)=>{const n=Et(e,t);return n?Dt(n).value:void 0},Tt=(e,t)=>{const n=(e,t,o)=>{const s=Et(e,t),r=s?Dt(s):void 0;let i;return r?r.enumerable?r.value:void 0:--o>=0&&(i=St(e))?n(i,t,o):void 0};return n(e,t,5)},At=e=>{const t=(t,...n)=>Pt(e,t,n);return $t(t,"wrappedJSObject",e),t},Ut=()=>e=>At(e),kt=At(l),Bt=R,Ft=e=>{const t=(e,n)=>{let o;if(null===e)o="null";else{const i=typeof e;if("object"===i){if(n){
if(-1!=Gt(n,e))throw"Converting circular structure to JSON";$t(n,n.length,e)}else n=[e];if(Ot(e)){let i="";for(let o=0;o<e.length;o++){let c;c=Yt(e,o)?Yt(s=e,r=o)?s[r]:void 0:Tt(e,o);const a=t(c,n);i+=`${o?",":""}${void 0===a?"null":a}`}o=`[${i}]`}else{let s="";Kt(wt(e),(o=>{const r=t(e[o],n);void 0!==r&&(s+=`${s?",":""}${j(o)}: ${r}`)})),o=`{${s}}`}n.length-=1}else{if("bigint"===i)throw"Do not know how to serialize a BigInt";o=j(e)}}var s,r;return o};return t(e)
},Xt=Ut()(g),Nt=Ut()(m),qt=(e,t)=>{const n=[];return Kt(e,(e=>{t(e)&&Jt(n,e)})),n},Wt=(e,t,n)=>{const o=e.length;let s=t||0;if(s>=o)return[];s<0&&(s=Rt(0,o+s));let r=void 0===n?o:n;r<0&&(r=Rt(0,o+r)),r>o&&(r=o);const i=Dt({});for(let t=s;t<r;t++)i[t]=Ct(e,t);return yt(i)},Ht=Ut()(f),Jt=(e,t)=>{let n=e.length||0;return $t(e,n,t),n++,e.length=n},Gt=Ut()(h),Kt=Ut()(p),Yt=Ut()(x),zt=Ut()(V),Vt=Ut()(K),Qt=At(I),Zt=St({}),en=e=>{const t=Dt(e),n=Lt(t);for(let e=0;e<n.length;e++){const o=n[e],s=t[o]
;null!==s&&"object"==typeof s&&St(s)===Zt&&(t[o]=en(s))}return t},tn=Ut()(u),nn=Ut()(T),on=Ut()(U),sn=(Ut()(k),Ct(ht,"Promise")),rn=Ut()(F),cn=Ut()(X),an=Ut()(N),dn=(Ut()(q),Ut()(W)),ln=(H&&Ut()(H),J&&Ut()(J),G),un=Ut()(Y),pn=Ut()(z),gn=(Ut()(Q),Ut()(Z||function(e,t){return Ht(zt(this,e),t)}),Ut()(ee)),mn=Ut()(te),fn=(Ut()(ne),At(re),At(ie),At(ce)),hn=At(ae),vn=At(de),_n=(At(le),At(ue),At(pe),At(ve)),bn=At(fe),wn=At(he),yn=me?Ut()(me):me,Mn=be,xn=(At(we),Ut()(ye),Ut()(Me),
Ie),Ln=Qe,En=tt,Sn=ot,On=nt,In=dt,Rn=at,jn=function(e,t){return Ct(e,t)},Pn=Dt({addEventListener:!1,Array:!0,Blob:!0,close:!1,CustomEvent:!0,Date:!0,DOMParser:!0,Error:!0,Event:!0,FileReader:!0,KeyboardEvent:!0,location:!0,Math:!0,MouseEvent:!0,Number:!0,Object:!0,ReadableStream:!0,removeEventListener:!1,Uint8Array:!0,XMLHttpRequest:!0}),Dn=((()=>{const e=Dt({getElementById:Ye,createEvent:ze,createElement:Ve,dispatchEvent:We,addEventListener,removeEventListener}),t=Dt({});Kt(wt(e),(n=>{try{
const o=e[n];t[n]=function(...e){return Pt(o,ht.document,e)}}catch(e){t[n]=((e,t)=>{if($n.error(`Tampermonkey sandbox preparation ${t?"("+t+") ":""}failed. This usually is caused by a third-party extension.`,e),t)return()=>{}})(e,`document.${n}`)}}))})(),Dt({top:!0,location:!0}));twod.bridges=twod.bridges||Dt({});const $n=twod.console=twod.console||Dt({}),Cn=Dt({addEventListener:kt(je,ht),removeEventListener:kt(Pe,ht)});Kt(wt(Dn),(async e=>{if(!Cn[e])try{const t=ht[e];if(null==t)return;Cn[e]=t
}catch(e){}})),Kt(wt(Pn),(async e=>{if(!Cn[e])try{let t=Ct(ht,e);if(void 0===t&&(vt===ht||void 0===(t=Ct(vt,e))))return;const n=Pn[e];Cn[e]=!1===n&&"function"==typeof t?kt(t,vt):t}catch(e){}}));const Tn=e=>{let t,n=[],o=!1;e((e=>{if(!o){if(n.length){const t=n;n=[],Kt(t,(t=>t(e)))}else t=e;o=!0}}));const s=Dt({then:e=>(o?e(t):Jt(n,e),s)});return s},An=()=>nn(xn()+19831206*It()+1,36),Un=function(){var e=t((function*(e){yield null,e()}));return function(t){return e.apply(this,arguments)}
}(),kn=(()=>{const{console:e,bridges:t}=twod,n=Dt({});let o;const s=(t,o,s,i)=>{let c,a=[],d=[],l=[],u=[];const p=()=>{d=[],l=[],u=[],h(),y=null,delete n[o]},g=e=>{t.send("port.message",Dt({response_id:o,value:e}))},m=e=>{i&&"messageId"in e&&Jt(a,e),g(e)},f=(e,t=!0)=>{c=e,t&&g(e)},h=()=>{c=void 0},v=Dt({addListener:e=>{Jt(d,e)}}),_=Dt({addListener:e=>{Jt(l,e)}}),b=Dt({addListener:e=>{Jt(u,e)}}),w=()=>{p(),t.send("port.message",Dt({response_id:o,disconnect:!0}))};let y=Dt(s?{postMessage:m,
connectMessage:f,stopReconnecting:h,onMessage:v,onDisconnect:_,onReconnect:b,disconnect:w}:{postMessage:m,onMessage:v,onDisconnect:_,disconnect:w});return n[o]=Dt({message:t=>{if(i&&(e=>"ack"in e)(t)){const{messageId:n}=t;(t=>{if(!t)return void e.warn("PortMessaging: no message id in ack message");if(c&&c.messageId===t)return;let n=-1;Xt(a,((e,o)=>e.messageId===t&&(n=o,!0))),-1!==n?(Kt(Wt(a,0,n),(t=>e.warn(`PortMessaging: message ${t.messageId} was not ack'ed!`,t))),
a=Wt(a,n+1)):e.warn(`PortMessaging: no one is waiting for ${t}`)})(n)}d&&Kt(d,(e=>e(t)))},disconnect:()=>{if(c&&s)return r(s,o),f(c),i&&Kt(a,(e=>g(e))),void(u.length&&Kt(u,(e=>e())));l.length&&Kt(l,(e=>e())),p()}}),y},r=(e,n)=>{t.first.send("port.message",Dt({response_id:n,connect:!0,destination:e}))};return Dt({message:(t,r)=>{let i;if(t.connect){if(!t.destination||!t.response_id)throw"invalid message";o&&o(t.destination,s(r,t.response_id))}else{if(!t.response_id)throw"invalid message"
;if(!(i=n[t.response_id]))return void e.warn("ports: unknown id",t.response_id,t);t.disconnect?i.disconnect():i.message(t.value)}},connect:function(e,n,o){const i=An();return r(e,i),s(t.first,i,n?e:void 0,o)},onConnect:Dt({addListener:e=>{o=e}})})})(),{setInterval:Bn,setTimeout:Fn,clearInterval:Xn,clearTimeout:Nn,console:qn,cloneInto:Wn,exportFunction:Hn,createObjectIn:Jn}=ht,Gn=Object.assign({},qn),Kn=Bn.bind(ht),Yn=Fn.bind(ht),zn=Xn.bind(ht),Vn=(Nn.bind(ht),
vt==ht.top),{arrayBuffer:Qn,blob:Zn}=ht.Response.prototype,{arrayBuffer:eo}=ht.Blob.prototype,{then:to}=ht.Promise.prototype,{fetch:no,location:oo,document:so,Response:ro}=ht,io=At(Qn),co=At(Zn),ao=At(eo),lo=Wn,uo=Hn,po=(Dt({encode:e=>Fe(Te(e)),decode:e=>Ae(Be(e))}),Dt({encode:e=>{let t="";for(let n=0;n<e.length;n++)t+=ln(255&gn(e,n));return Ne(t)},decode:e=>Xe(e)})),go=(e,t)=>{const n=hn(ht.document,"http://www.w3.org/1999/xhtml",e);return"string"==typeof t?n.append(t):t&&Kt(wt(t),(e=>{
"textContent"==e?n.textContent=t[e]:n.setAttribute(e,t[e])})),n},mo=e=>{const t=ht.document;if(t.body||"text/xml"==t.contentType)e();else{let t=!1;const o=new On((()=>{t=!0,mo(e),(yn||(e=>e.disconnect()))(o)}));o.observe(ht.document,Dt({childList:!0})),n((()=>{t||((yn||(e=>e.disconnect()))(o),e())}))}},fo=e=>{n((()=>{Yn((()=>e()),1)}))};let ho,vo;const _o=oo.host,bo=e=>{"n:"==un(e,0,2)?ho=un(e,2):e&&(vo=un(e,2))},wo=()=>ho||(vo?(ho=(e=>{const t=(e,t)=>e<<t|e>>>32-t,n=(e,t)=>{
const n=2147483648&e,o=2147483648&t,s=1073741824&e,r=1073741824&t,i=(1073741823&e)+(1073741823&t);return s&r?2147483648^i^n^o:s|r?1073741824&i?3221225472^i^n^o:1073741824^i^n^o:i^n^o},o=(e,o,s,r,i,c,a)=>(e=n(e,n(n(((e,t,n)=>e&t|~e&n)(o,s,r),i),a)),n(t(e,c),o)),s=(e,o,s,r,i,c,a)=>(e=n(e,n(n(((e,t,n)=>e&n|t&~n)(o,s,r),i),a)),n(t(e,c),o)),r=(e,o,s,r,i,c,a)=>(e=n(e,n(n(((e,t,n)=>e^t^n)(o,s,r),i),a)),n(t(e,c),o)),i=(e,o,s,r,i,c,a)=>(e=n(e,n(n(((e,t,n)=>t^(e|~n))(o,s,r),i),a)),n(t(e,c),o)),c=e=>{
let t,n,o="",s="";for(n=0;n<=3;n++)t=e>>>8*n&255,s="0"+nn(t,16),o+=un(s,s.length-2,2);return o};let a,d,l,u,p,g,m,f;const h=(e=>{let t;const n=e.length,o=n+8,s=16*((o-o%64)/64+1),r=[];for(let e=0;e<=s-1;e++)Jt(r,0);let i=0,c=0;for(;c<n;)t=(c-c%4)/4,i=c%4*8,r[t]=r[t]|gn(e,c)<<i,c++;return t=(c-c%4)/4,i=c%4*8,r[t]=r[t]|128<<i,r[s-2]=n<<3,r[s-1]=n>>>29,r})(e);p=1732584193,g=4023233417,m=2562383102,f=271733878;for(let e=0;e<h.length;e+=16)a=p,d=g,l=m,u=f,p=o(p,g,m,f,h[e+0],7,3614090360),
f=o(f,p,g,m,h[e+1],12,3905402710),m=o(m,f,p,g,h[e+2],17,606105819),g=o(g,m,f,p,h[e+3],22,3250441966),p=o(p,g,m,f,h[e+4],7,4118548399),f=o(f,p,g,m,h[e+5],12,1200080426),m=o(m,f,p,g,h[e+6],17,2821735955),g=o(g,m,f,p,h[e+7],22,4249261313),p=o(p,g,m,f,h[e+8],7,1770035416),f=o(f,p,g,m,h[e+9],12,2336552879),m=o(m,f,p,g,h[e+10],17,4294925233),g=o(g,m,f,p,h[e+11],22,2304563134),p=o(p,g,m,f,h[e+12],7,1804603682),f=o(f,p,g,m,h[e+13],12,4254626195),m=o(m,f,p,g,h[e+14],17,2792965006),
g=o(g,m,f,p,h[e+15],22,1236535329),p=s(p,g,m,f,h[e+1],5,4129170786),f=s(f,p,g,m,h[e+6],9,3225465664),m=s(m,f,p,g,h[e+11],14,643717713),g=s(g,m,f,p,h[e+0],20,3921069994),p=s(p,g,m,f,h[e+5],5,3593408605),f=s(f,p,g,m,h[e+10],9,38016083),m=s(m,f,p,g,h[e+15],14,3634488961),g=s(g,m,f,p,h[e+4],20,3889429448),p=s(p,g,m,f,h[e+9],5,568446438),f=s(f,p,g,m,h[e+14],9,3275163606),m=s(m,f,p,g,h[e+3],14,4107603335),g=s(g,m,f,p,h[e+8],20,1163531501),p=s(p,g,m,f,h[e+13],5,2850285829),
f=s(f,p,g,m,h[e+2],9,4243563512),m=s(m,f,p,g,h[e+7],14,1735328473),g=s(g,m,f,p,h[e+12],20,2368359562),p=r(p,g,m,f,h[e+5],4,4294588738),f=r(f,p,g,m,h[e+8],11,2272392833),m=r(m,f,p,g,h[e+11],16,1839030562),g=r(g,m,f,p,h[e+14],23,4259657740),p=r(p,g,m,f,h[e+1],4,2763975236),f=r(f,p,g,m,h[e+4],11,1272893353),m=r(m,f,p,g,h[e+7],16,4139469664),g=r(g,m,f,p,h[e+10],23,3200236656),p=r(p,g,m,f,h[e+13],4,681279174),f=r(f,p,g,m,h[e+0],11,3936430074),m=r(m,f,p,g,h[e+3],16,3572445317),
g=r(g,m,f,p,h[e+6],23,76029189),p=r(p,g,m,f,h[e+9],4,3654602809),f=r(f,p,g,m,h[e+12],11,3873151461),m=r(m,f,p,g,h[e+15],16,530742520),g=r(g,m,f,p,h[e+2],23,3299628645),p=i(p,g,m,f,h[e+0],6,4096336452),f=i(f,p,g,m,h[e+7],10,1126891415),m=i(m,f,p,g,h[e+14],15,2878612391),g=i(g,m,f,p,h[e+5],21,4237533241),p=i(p,g,m,f,h[e+12],6,1700485571),f=i(f,p,g,m,h[e+3],10,2399980690),m=i(m,f,p,g,h[e+10],15,4293915773),g=i(g,m,f,p,h[e+1],21,2240044497),p=i(p,g,m,f,h[e+8],6,1873313359),
f=i(f,p,g,m,h[e+15],10,4264355552),m=i(m,f,p,g,h[e+6],15,2734768916),g=i(g,m,f,p,h[e+13],21,1309151649),p=i(p,g,m,f,h[e+4],6,4149444226),f=i(f,p,g,m,h[e+11],10,3174756917),m=i(m,f,p,g,h[e+2],15,718787259),g=i(g,m,f,p,h[e+9],21,3951481745),p=n(p,a),g=n(g,d),m=n(m,l),f=n(f,u);const v=c(p)+c(g)+c(m)+c(f);return mn(v)})(`${_o}#${vo}`),ho):void 0),yo=e=>void 0!==Ct(e,"objUrl"),Mo=e=>void 0!==Ct(e,"blob"),xo=e=>void 0!==Ct(e,"dataUri"),Lo=e=>void 0!==e.binary,Eo=globalThis,{chrome:So,browser:Oo}=Eo
;let Io,Ro,jo,Po;jo=()=>{if(void 0!==Io)return Io;try{const e=navigator.userAgent.match(/Firefox\/([0-9]+)\./);e&&(Io=parseInt(e[1]))}catch(e){}return Io<78&&(Io=78),Io},Po=()=>{if(void 0!==Ro)return Ro;try{Ro=!So.windows}catch(e){}return Ro},jo(),jo(),jo(),["browser"].concat(["chrome"]);const Do=(()=>{const e={getInternalPathRegexp:function(e,t){const n=new RegExp("(\\"+["/",".","+","?","|","(",")","[","]","{","}","\\"].join("|\\")+")","g"),o=$o.getURL("/")
;return new RegExp(o.replace(n,"\\$1")+"([a-zA-Z"+(e?"\\/":"")+"]*)"+(t||"").replace(n,"\\$1"))},getInternalPageRegexp:function(){return Do.getInternalPathRegexp(!1,".html")},getPlatformInfo:e=>So.runtime.getPlatformInfo(e),getBrowserInfo:e=>So.runtime.getBrowserInfo(e)};let t=null;return Object.defineProperty(e,"lastError",{get:()=>So.runtime.lastError,enumerable:!0}),Object.defineProperty(e,"id",{
get:()=>(t=t||(jo()<54?(location.href.match(/[^:]+:\/\/([^/]+)/)||[])[1]:So.runtime.id)||"FirefoxTM",t),enumerable:!0}),Object.defineProperty(e,"short_id",{get:()=>"firefox@tampermonkey.net"==So.runtime.id?"fire":"firb",enumerable:!0}),e})(),$o=(()=>{const e={};let t;return Object.defineProperties({},{inIncognitoContext:{get:()=>(void 0===t&&(t=So.extension.inIncognitoContext),t),set:e=>{t=e},enumerable:!0},...Object.getOwnPropertyDescriptors({getURL:function(e){return So.runtime.getURL(e)},
sendMessage:function(e,t){return So.runtime.sendMessage(e,t)},onMessage:{addListener:function(t){return So.runtime.onMessage.addListener(((n,o,s)=>{const r="xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,(e=>{const t=16*Math.random()|0;return("x"==e?t:3&t|8).toString(16)})),i=o.tab?o.tab.id:0;i&&(e[i]=e[i]||{},e[i][r]=s);let c=!0;const a=t(n,o,(t=>{c=!1,s(t),i&&delete e[i][r]}));return i&&c&&!0!==a&&delete e[i][r],a}))}},connect:function(e){return So.runtime.connect({name:e})},urls:{
prepareForReport:function(e){return e}}})})})(),Co=()=>{(()=>{if(/file:\/\/.*\.user\.js.*/.test(window.location.href)){const e=()=>{$o.sendMessage({method:"source@firefox",source:document.body.textContent},(()=>{}))};"complete"===document.readyState?e():window.addEventListener("load",e,!1)}})()},To=So&&So.userScripts&&So.userScripts.onBeforeScript?{supported:!0,onBeforeScript:{addListener:e=>So.userScripts.onBeforeScript.addListener(e)}}:{supported:!1
},Ao=({sendPrefix:e,listenPrefix:n,send:o,onMessage:s})=>{if(void 0===o||void 0===s)throw"invalid args";let r,i,c=1;const a=Dt({}),d=Dt({}),l=e=>{e&&(r=e)},u=e=>{const t=++c;return d[c]=e,t};s(((t,s)=>t==`${n}_${r}`?(t=>{const{m:n,r:s,a:c,n:l}=t;if(a[n]&&(Kt(a[n],(e=>e(c))),delete a[n]),"message.response"==n){if(null==s)throw"Invalid Message";((e,t)=>{let n;e&&(n=d[e])&&(n(t),delete d[e])})(s,c)}else if(i){const t=s?t=>{o(`${e}_${r}`,Dt({m:"message.response",a:t,r:s}))}:()=>{};i(Dt({method:n,
args:c,node:l}),t)}})(s):null));const p=Dt({init:(g=t((function*(e){r?l():l(e)})),function(e){return g.apply(this,arguments)}),refresh:()=>null,switchId:e=>{r&&p.cleanup(),l(e)},send:(t,n,s,i)=>Tn((c=>{let a,d;"function"!=typeof s&&null!==s?(a=s,d=i):d=s,o(`${e}_${r}`,Dt({m:t,a:n,r:d?u(d):null,n:a})),c()})),sendToId:(t,n,s)=>{o(`${e}_${t}`,Dt({m:n,a:s,r:null}))},once:(e,t)=>{a[e]||(a[e]=[]),Jt(a[e],t)},setMessageListener:e=>{i=e},cleanup:()=>null});var g;return p
},Uo=To,ko=To.supported&&!ht.pagejs;let Bo;const Fo=(e,t)=>{try{Bo(e),t&&t()}catch(e){t&&t(e.message||e)}},Xo="u"+An(),{bridges:No}=twod;let qo=[];const Wo=e=>{Uo.onBeforeScript.addListener((o=>{const s=(e,n)=>{Kt(t,(t=>t(e,n)))},r=e=>Jt(n,Dt({listener:e,clone:o.export}));xt(o.global,"pagejs",Dt({set:o.export((t=>{delete o.global.pagejs;const n=o.metadata,{modes:i,nonce:c}=n;if(c&&bo(c),Kt(qo,(e=>e(t,n))),qo=[],i.js){const n=lo,i=uo,c=Dt({unsafeWindow:o.global,unsafeThis:o.global.window,
pageWindow:o.global.window.wrappedJSObject,contextId:Xo,fSend:s,fOnMessage:r,cloneInto:n?(e,t,o)=>n(e.wrappedJSObject||e,t,o):void 0,exportFunction:i?(e,t,n)=>i(e.wrappedJSObject||e,t,n):void 0});t(o.export(c)),No.js.sendToId(Xo,"commid",Dt({id:e}))}})),configurable:!0})),Bo=o.global.eval}));const t=[],n=[],o=(e,t)=>{Kt(n,(({listener:n,clone:o})=>n(e,o(t))))},s=e=>Jt(t,e);return Dt({createBridge:()=>{const t=Ao(Dt({sendPrefix:"2S",listenPrefix:"2U",cloneInto:lo,send:o,onMessage:s}))
;return t.init(e),t}})};let Ho=[],Jo=[];const Go=e=>{const t=$o.connect(e);if(Do.lastError)return;let n=[];const o=Dt({postMessage:e=>t.postMessage(e),onMessage:Dt({addListener:e=>t.onMessage.addListener(e)}),onDisconnect:Dt({addListener:e=>{Jt(n,e)}}),disconnect:()=>(s(!1),t.disconnect())}),s=e=>{e&&Kt(n,(e=>e())),n=[],Ho=qt(Ho,(e=>e!==r)),Jo=qt(Jo,(e=>e!==i))};t.onDisconnect.addListener((()=>s(!0)));const r=()=>{t.disconnect(),Do.lastError,s(!0)};Jt(Ho,r);const i=()=>{t.disconnect(),
Do.lastError};return Jt(Jo,i),o};let Ko;Cn.addEventListener("pagehide",(e=>{wn(e)&&Kt(Jo,(e=>e()))})),Cn.addEventListener("pageshow",(e=>{wn(e)&&Kt(Ho,(e=>e()))}));const{console:Yo}=twod,zo=e=>{const n=e.details&&e.details.url;return Tn(function(){var o=t((function*(t){if(n&&"blob:"===un(n,0,5)){ko&&(e=Bt(Ft(e)));const t=yield no(n),s=yield co(t),r=yield(o=s,Tn((e=>{const t=new Cn.FileReader;t.onload=()=>{e(dn(t))},t.onerror=t=>{$n.warn(`unable to decode data ${t}`),e("")},an(t,o)
}))),i=s.type||"application/octet-stream";try{e.details.url=`data:${i};base64,${po.encode(r)}`}catch(e){Yo.warn(`content: failed to get blob data from ${n}`,e)}}var o;t(e)}));return function(e){return o.apply(this,arguments)}}())},Vo=Dt({setInterval:e=>{let t;e.onMessage.addListener((n=>{"setInterval"==n.method&&(t=Kn(e.postMessage,n.t))})),e.onDisconnect.addListener((()=>{t&&zn(t),t=null}))},registerMenuCommand:e=>{const t=Go("registerMenuCommand");if(!t)return void Yn((()=>e.disconnect()),1)
;let n=!1,o=!1;t.onMessage.addListener((s=>{if(n||(n=!0,o&&(t.disconnect(),o=!1)),"ack"in s)e.postMessage(s);else{const{method:t,event:n}=s;e.postMessage(Dt({method:t,event:n}))}})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{const{messageId:n,name:o,uuid:s,accessKey:r,autoClose:i,title:c,id:a}=e,d=Ht([a,Ko,s],"#");t.postMessage(Dt({messageId:n,method:"registerMenuCommand",name:o,title:c,uuid:s,menuId:d,accessKey:r,autoClose:i}))})),
e.onDisconnect.addListener((()=>{n?t.disconnect():o=!0}))},notification:e=>{const t=Go("notification");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{t.postMessage(e)})),e.onDisconnect.addListener((()=>{t.disconnect()}))):Yn((()=>e.disconnect()),1)},openInTab:e=>{const t=Go("openInTab");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),
e.onMessage.addListener((e=>{const{messageId:n}=e;if("method"in e){const{method:o}=e;if("openInTab"==o)if("url"in e){let o=e.url;const{active:s,loadInBackground:r,insert:i,incognito:c,setParent:a}="boolean"==typeof e.options||void 0===e.options?Dt({loadInBackground:e.options}):e.options,d=void 0===s?void 0!==r&&!r:s,l=void 0===i||i;o&&"//"==un(o,0,2)&&(o=oo.protocol+o),t.postMessage(Dt({messageId:n,method:"openInTab",details:Dt({url:o,options:Dt({active:!!d,insert:!!l,incognito:!!c,
setParent:!c&&!!a})}),uuid:e.uuid}))}else t.postMessage(e);else Yo.warn(`content: unknown method ${o}`)}else"name"in e?t.postMessage(Dt({messageId:n,name:e.name})):"focus"in e?t.postMessage(Dt({messageId:n,focus:!0})):"close"in e&&t.postMessage(Dt({messageId:n,close:!0}))})),e.onDisconnect.addListener((()=>{t.disconnect()}))):Yn((()=>e.disconnect()),1)},download:e=>{let t;const n=Go("download");n?(n.onMessage.addListener((t=>{e.postMessage(t)})),n.onDisconnect.addListener((()=>{e.disconnect(),
t=!0})),e.onMessage.addListener((e=>{"cancel"in e?(t=!0,n.postMessage(Dt({cancel:!0,id:Ko,uuid:e.uuid}))):"details"in e?zo(e).then((e=>{if(t)return;let{url:o,...s}=e.details;n.postMessage(Dt({messageId:e.messageId,method:"download",details:Dt({...s,from:Dt({url:o})}),id:Ko,uuid:e.uuid,location:oo.href}))})):n.postMessage(Dt({messageId:e.messageId,method:"download",uuid:e.uuid,id:e.id}))})),e.onDisconnect.addListener((()=>{n.disconnect()}))):Yn((()=>e.disconnect()),1)},webRequest:e=>{
const t=Go("webRequest");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{const{messageId:n,rules:o,uuid:s}=e;t.postMessage(Dt({messageId:n,method:"webRequest",rules:o,uuid:s}))})),e.onDisconnect.addListener((()=>{t.disconnect()}))):Yn((()=>e.disconnect()),1)},xhr:e=>{let n,o;const s=[],r=function(){var e=t((function*(e){if(e&&Jt(s,e),o)yield o,r();else{const e=Nt(s);e&&e()}}));return function(t){
return e.apply(this,arguments)}}(),i=Go("xhr");i?(i.onMessage.addListener((n=>{"ack"in n?e.postMessage(n):r((()=>{const{onpartial:s,data:r,...i}=n;let c;if(s&&r){const{tfd:n}=r;if(n){const r=(e=>e&&(Mo(e)||yo(e)||xo(e)||Lo(e))?(e=>{let t,n,o,s,r;if(yo(e))t=e.objUrl.url;else if(Mo(e))n=e.blob;else if(xo(e))o=e.dataUri;else{if(!Lo(e))throw"incompatible TransferableData";s=e.binary,r=e.type}return Dt({toBlob:()=>Tn((e=>{if(n)e(n);else if(t)try{on(no(t),(t=>{on(co(t),(t=>{e(t)}))}))}catch(t){
e(void 0)}else if(o)e((e=>{let t;const n=zt(e,","),o=jn(n,0),s=jn(n,1);t=-1!=pn(o,"base64")?Xe(s):Fe(s);const r=jn(zt(o,":"),1),i=jn(zt(r,";"),0);return new In([t],Dt({type:i}))})(o));else{if(!s)throw"incompatible Transferable";{const t=(e=>{const t=new Sn(e.length);for(let n=0;n<e.length;n++)t[n]=gn(e,n);return t.buffer})(s);e(new In([t],r?Dt({type:r}):void 0))}}})),dispose:()=>{t&&Mn(t),t=n=o=s=void 0}})})(e):void 0)(n);if(!r)return;return void(o=Tn(function(){var n=t((function*(t){
const n=()=>{o=null,t(),r&&r.dispose()};try{const t=yield r.toBlob();if(!t)return void n();const o=t.type;let a;if(a="arrayBuffer"in t?yield ao(t):yield io(new ro(t)),!a)return void n();c=Dt({nada:Dt({buffer:a,type:o})}),e.postMessage(Dt({...i,onpartial:s,data:c})),n()}catch(e){Yo.warn(e),n()}}));return function(e){return n.apply(this,arguments)}}()))}c=r}else c=r;e.postMessage(Dt({...i,onpartial:s,data:c}))}))})),i.onDisconnect.addListener((()=>{r(function(){var o=t((function*(){e.disconnect(),
n=!0}));return function(){return o.apply(this,arguments)}}())})),e.onMessage.addListener((e=>{zo(e).then((e=>{n||(e.location=oo.href,i.postMessage(e))}))})),e.onDisconnect.addListener((()=>{i.disconnect()}))):Yn((()=>e.disconnect()),1)},onurlchange:e=>{const t=Go("onurlchange");if(!t)return void Yn((()=>e.disconnect()),1);let n=()=>{e.postMessage(Dt({url:oo.href}))};const o=()=>{n&&(Cn.removeEventListener("hashchange",n),n=null)};Cn.addEventListener("hashchange",n),t.onMessage.addListener((t=>{
e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect(),o()})),e.onMessage.addListener((e=>{t.postMessage(e)})),e.onDisconnect.addListener((()=>{t.disconnect(),o()}))},values:e=>{const t=Go("values");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{t.postMessage(e)})),e.onDisconnect.addListener((()=>{t.disconnect()}))):Yn((()=>e.disconnect()),1)},backgroundControl:e=>{const t=Go("backgroundControl")
;t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{t.postMessage(e)})),e.onDisconnect.addListener((()=>{t.disconnect()}))):Yn((()=>e.disconnect()),1)},keepAlive:e=>{const t=Go("keepAlive");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{t.postMessage(e),Do.lastError})),e.onDisconnect.addListener((()=>{t.disconnect()
}))):Yn((()=>e.disconnect()),1)}}),Qo=Dt({setTimeout:({args:e,cb:t})=>{Yn(t,e.t)},setClipboard:({args:e,cb:t})=>{const{content:n,info:o,uuid:s}=e;let r,i;"object"==typeof o?(o.type&&(r=o.type),o.mimetype&&(i=o.mimetype)):"string"==typeof o&&(r=o);const c=i||("html"==r?"text/html":"text/plain");ht.document.addEventListener("copy",(e=>{e.stopImmediatePropagation(),e.preventDefault(),e.clipboardData&&e.clipboardData.setData(c,n)}),Dt({capture:!0,once:!0})),ht.document.execCommand("copy"),t()},
closeTab:({args:{uuid:e},cb:t})=>{$o.sendMessage(Dt({method:"closeTab",uuid:e,id:Ko}),(e=>{e&&e.error&&Yo.warn(e.error),t(e)}))},focusTab:({args:{uuid:e},cb:t})=>{$o.sendMessage(Dt({method:"focusTab",uuid:e,id:Ko}),(e=>{e&&e.error&&Yo.warn(e.error),t(e)}))},addElement:(Zo=t((function*({args:e,node:t,cb:o}){try{const s=go(e.tag,Dt({...e.properties||Dt({}),...e.id?Dt({id:e.id}):Dt({})}));let r,i;if("script"===e.tag&&(r=wo())&&s.setAttribute("nonce",r),t)i=t;else{const e=ht.document
;if(i=e.head||e.body||e.documentElement,!i){const e=ht.document;i=yield Tn((t=>n((()=>t(e.head||e.body)))))}}i.appendChild(s),r&&s.removeAttribute("nonce"),o()}catch(e){Yo.warn("content: error adding script",e)}})),function(){return Zo.apply(this,arguments)}),tabs:({args:e,cb:t})=>{e.method="tabs",$o.sendMessage(e,(e=>e&&t(e.data)))},cookie:({args:e,cb:t})=>{e.method="cookie",$o.sendMessage(e,(e=>e&&t(e.data)))}});var Zo;const es=Dt({init:()=>{Ko=twod.contextId},
processMessage:({method:e,args:t,node:n},o)=>{let s;if(s=Qo[e])return s(Dt({args:t,node:n,cb:o}));o()},processConnect:(e,t)=>{let n;if(n=Vo[e])return n(t)}}),ts=["GM_info","GM.info"],ns=["unsafeWindow",...ts],os=e=>e.replace(new RegExp("[\"']","g"),"\\$1");let ss=!1;const rs=(e,n,o,s,r,i)=>{const{console:c}=twod;ss=ss||e.logLevel>=60;const{version:a,injectMode:d,inIncognitoContext:l,isFirstPartyIsolation:u,downloadMode:p,relaxedCsp:g,userAgent:m,container:f,logLevel:h}=e,v=Dt({version:a,
injectMode:d,inIncognitoContext:l,isFirstPartyIsolation:u,downloadMode:p,relaxedCsp:g,container:f});Kt(n,function(){var n=t((function*(t){const{script:n,storage:a}=t,{name:d,uuid:l,options:{run_at:u}}=n,{requires:p,...g}=n,f=p.length,_=!n.options.unwrap,b=Dt({...v,userAgent:m,logLevel:h,sandboxMode:r});let w,y;const M=((e,t)=>{
const{measure_scripts:n,top_level_await:o,enforce_strict_mode:s}=e,{source_url:r,script:i,code:c}=t,{name:a,grant:d}=i,{requires:l}=i,u=!i.options.unwrap,p=l.map((e=>e.textContent||"")).join("\n");if(u){let e="";const t=["define","module","exports"],l=t.map((()=>"undefined")),u=-1!==i.grant.indexOf("none");let g;return g=u?ts:d.concat(ns),g.forEach((e=>{const n=e.split(".")[0];"window"!==n&&-1===t.indexOf(n)&&(t.push(n),l.push(`p.${n}`))})),
[`with (${u?"this.s":"this"}) {`,"(async (u, { p, r, s }) => {","try {",n?`console.time("${e=`SCRIPT RUN TIME[${os(a)}]`}");\n`:"","r(u, s, [",l.join(","),"]);",n?`console.timeEnd("${e}");\n`:"","} catch (e) {","if (e.message && e.stack) {","console.error(\"ERROR: Execution of script '",os(a),"' failed! \" + e.message);","console.log(e.stack);","} else {","console.error(e);","}","}","})","(",(o?"async ":"")+"function(",t.join(","),") {",s?'"use strict";\n':"\n",p,c,"\n",`}, ${u?"this":"seed"})`,"}","\n",r?`//# sourceURL=${r}\n`:""].join("")
}return[p,c,"\n",r?`//# sourceURL=${r}\n`:""].join("")})(e,t);return _?(w=()=>{ss&&c.debug(`env: inject "${d}" now`);const e=`__f__${An()}`,t=Dt({storage:a,script:g}),n=`window["${e}"] = function(){${M}}`;let r=!0;s.once(`scriptack-${e}`,(()=>{ss&&!r&&c.log(`env: execution of "${d}" was delayed`),o(n,(e=>{e&&c.error(`Uncaught SyntaxError: ${e}`)}))})),s.send("script",Dt({id:e,unwrap:!1,bundle:t,flags:b})),r=!1},y="context-menu"==u||"document-start"==u?void 0:()=>{
ss&&c.debug(`env: run "${d}" now  (${f} requires)`),s.send("run",Dt({uuid:l}))}):y=()=>{ss&&c.debug(`env: inject @unwrap "${d}" now`),o(M,(e=>{e&&c.error(`Uncaught SyntaxError: ${e}`)}))},i&&(yield null),is(d,u,w,y,ss)}));return function(e){return n.apply(this,arguments)}}())},is=(e,t,o,s,r)=>{const{console:i}=twod;let c;"document-start"==t?(r&&i.debug(`env: run "${e}" ASAP -> document-start`),c=e=>e()):"document-body"==t?(r&&i.debug(`env: schedule "${e}" for document-body`),
c=mo):"context-menu"==t?r&&i.debug(`env: run "${e}" ASAP -> context-menu`):"document-end"==t?(r&&i.debug(`env: schedule "${e}" for document-end`),c=e=>n(!1,e)):(r&&i.debug(`env: schedule "${e}" for document-idle`),c=fo),o&&o(),s&&c&&c((()=>{s()}))},cs=(e,t)=>{let n,o;try{o=(0,eval)(e)}catch(e){n=e.message||e}return t&&t(n),o},as=({sendPrefix:e,listenPrefix:n,cloneInto:o})=>{const s=e=>o?o(e,ht.document):e,i=Dt({});let c,a,d=1;const l=Dt({});let u=!1,p=[];const g=()=>{
b=ht.document.documentElement,u=!1;const e=p;p=[],Kt(e,(e=>{u||y()?Jt(p,e):e()}))};let m;const f=e=>{const t=++d;return l[d]=e,t},h=(e,t)=>{const{m:n,a:o,r,n:i}=t,{m:c,c:a}=((e,t,n)=>{let o,r;return n?(r=new En(e,Dt({relatedTarget:n})),o=new Ln(e,Dt({detail:s(t)}))):o=new Ln(e,Dt({detail:s(t)})),Dt({m:r,c:o})})(e,Dt({m:n,a:o,r}),i);c&&Pt(We,ht,[c]),Pt(We,ht,[a])},v=t=>{const n=(e=>{if("MouseEvent"===(e=>{const t=zt(Qt(e)," ");return Vt(Ht(Wt(t,1)," "),0,-1)})(e)){const t=_n(e)
;if(!t)throw"Invalid MouseEvent";return void(m=t)}const t=en(bn(e));return m&&(t.n=m,m=void 0),t})(t);if(!n)return;const{m:o,r:s,a:r,n:d}=n;if(i[o]&&(Kt(i[o],(e=>e(r))),delete i[o]),"unlock"==o)h(`${e}_${a}`,Dt({m:"unlocked",a:void 0,r:null})),g();else if("unlocked"==o)g();else if("message.response"==o){if(null==s)throw"Invalid Message";((e,t)=>{let n;e&&(n=l[e])&&(n(t),delete l[e])})(s,r)}else if(c){const t=s?t=>{h(`${e}_${a}`,Dt({m:"message.response",a:t,r:s}))}:()=>{};c(Dt({method:o,args:r,
node:d}),t)}},_=e=>{e&&(a=e),a&&Cn.addEventListener(`${n}_${a}`,v,!0)};let b,w;const y=()=>{if((()=>{const e=ht.document.documentElement;return b||(b=e),b!==e})()){if(w){const e=w;w=void 0,e(ht.document)}return!0}},M=e=>(b=ht.document.documentElement,Tn(function(){var n=t((function*(t){if(w=t,r&&!e&&(yield null,y()))return;const n=new On((()=>{y()&&n.disconnect()}));n.observe(ht.document,Dt({childList:!0}))}));return function(e){return n.apply(this,arguments)}}())),x=Dt({
init:(L=t((function*(t,n){a?_():_(t),M(n).then((()=>{u=!0,x.refresh(),h(`${e}_${a}`,Dt({m:"unlock",a:void 0,r:null}))}))})),function(e,t){return L.apply(this,arguments)}),refresh:()=>{const e=a;e&&(x.cleanup(),x.init(e,!0))},switchId:e=>{a&&x.cleanup(),_(e)},send:(t,n,o,s)=>Tn((r=>{let i,c;"function"!=typeof o&&null!==o?(i=o,c=s):c=o,y();const d=()=>{h(`${e}_${a}`,Dt({m:t,a:n,r:c?f(c):null,n:i})),r()};u?Jt(p,d):d()})),sendToId:(t,n,o)=>{h(`${e}_${t}`,Dt({m:n,a:o,r:null}))},
setMessageListener:e=>{c=e},once:(e,t)=>{i[e]||(i[e]=[]),Jt(i[e],t)},cleanup:()=>{a&&(Cn.removeEventListener(`${n}_${a}`,v,!0),a=void 0)}});var L;return x},ds=function(e,t,n,o,s){let r;const i=wo(),c=go("script");i&&c.setAttribute("nonce",i);try{c.textContent=t,e.appendChild(c)}catch(e){r=e.message||e}if(i&&c.removeAttribute("nonce"),!s){const e=c.parentNode;e&&e.removeChild(c)}return o&&o(r),!r},ls=(e,t)=>{try{ds(so.head||so.body||so.documentElement||so,e,0,t)}catch(e){t&&t(e.message||e)}}
;let us,ps;const gs=e=>{const t=Go("tabInfo");t?(t.onMessage.addListener((e=>{if("ack"in e);else{const{info:t}=e;t?us=en(t):Gn.warn("tabInfo: unexpected message",e)}})),t.onDisconnect.addListener((()=>{ms()})),e(t)):Yn((()=>gs(e)),100)},ms=()=>{gs((e=>{us=ps||us,ps=void 0,e.postMessage(Dt({method:"tabInfo",messageId:An(),info:us}))}))},fs=e=>{e=e||Cn.location.href;const t=Go("tabInfo");t?(t.onMessage.addListener((e=>{"ack"in e||Gn.warn("tabInfo.frame: unexpected message",e)})),
t.onDisconnect.addListener((()=>{fs(e)})),t.postMessage(Dt({method:"tabInfo",messageId:An(),url:e}))):Yn((()=>fs(e)),100)};let hs=!1;const vs=location.pathname+location.search,_s="TM_"+Do.short_id+window.btoa(vs.length+vs).substr(0,255).replace(/[#=/]/g,"_"),bs=()=>{let e,t,n,o;try{o=document.cookie.split(";")}catch(e){return}for(e=0;e<o.length;e++)if(t=o[e].substr(0,o[e].indexOf("=")),n=o[e].substr(o[e].indexOf("=")+1),t=t.replace(/^\s+|\s+$/g,""),0===t.indexOf(_s)){
document.cookie=t+"=; expires=Thu, 01 Jan 1970 00:00:01 GMT;";const e=Ae(n);if(0!==e.indexOf("blob:"))continue;let o;try{if(0!==(new URL(e).origin+"/").indexOf($o.getURL("/")))continue;if(o=new XMLHttpRequest,o.open("GET",e,!1),o.send(null),200===o.status||0===o.status)return JSON.parse(o.responseText)}catch(e){console.warn("content: unable to decode "+(o&&o.responseText||"unknown"))}}};let ws=!1;const ys=(e,t,o)=>{const{contextId:s,bridges:r,console:i}=twod;let c;Tn((n=>{const o=e=>{let t=1
;const o=()=>{hs&&i.log('content: send "prepare" message'),$o.sendMessage({method:"prepare",id:s,topframe:Vn,url:window.location.href},(s=>{if(!ws){if(!s)return hs&&i.log("content: _early_ execution, connection to bg failed -> retry!"),window.setTimeout(o,t),void(t=jt(2*t,3e3));ws=!0,s.nonce&&bo(s.nonce),wt(s.contexters).length||wt(s.scripts).length||s.external_connect?(e&&e(s),n({info:s,type:"complete"==fn(ht.document)?"late":"normal"})):n({info:s})}}))};!function(e){
const t=()=>"prerender"!==document.webkitVisibilityState,n=()=>{t()&&(document.removeEventListener("webkitvisibilitychange",n,!1),e())};t()?e():document.addEventListener("webkitvisibilitychange",n,!1)}(o)},r=()=>{let r;if(hs&&i.log("content: Started ("+s+", "+window.location.origin+window.location.pathname+")",vt.tm_info),(r=vt.tm_info)||(r=bs())){delete vt.tm_info,r.nonce&&bo(r.nonce);const{contexters:o,scripts:i}=r;if(wt(o).length||wt(i).length){
if(r.contexters.raw||r.scripts.raw)if(e.raw)void 0===c&&(c=e.raw());else if(!t)throw"raw inject missing";n({info:r,type:"sync"})}else n({info:r});{let e;$o.sendMessage({method:"prepare",id:s,topframe:Vn,url:window.location.href,scripts:e,cleanup:!0},(()=>null))}}else t?o((({scripts:t,contexters:n})=>{e.raw&&void 0===c&&(t.raw||n.raw)&&(c=e.raw())})):(e.raw&&void 0===c&&(c=e.raw()),o())};t?window.setTimeout((()=>r()),1):r()})).then((({info:a,type:d})=>{const{external_connect:l}=a;if(!t&&(e=>{
if(e){const t=location.href.split("#")[0];return e.some((({source:e,flags:n})=>{const o=new Rn(e,n);if(""===t.replace(o,""))return!0}))}return!1})(l)&&Un((()=>r.first.send("external.connect"))),d){hs=hs||a.logLevel>=60;const{scripts:l}=a;if(l.raw){let n;if(t&&!e.raw||!c)n=!0;else{let e=!1;const t=r.raw,o=An();t.once("ack",(()=>{e=!0})),t.once("injectableack",(()=>{ls(`window["${o}"] = 1`)})),t.send("injectable",{id:o}),n=!e}n&&(e.js?(l.js=(l.js||[]).concat(l.raw||[]),
delete l.raw):e.dom&&(l.dom=(l.dom||[]).concat(l.raw||[]),delete l.raw))}if(l.js){if(!e.js)throw"js inject missing";e.js()}if(l.dom){if(!e.dom)throw"dom inject missing";e.dom()}n(!1,(()=>{hs&&i.log("content: DOMContentLoaded"),Kt(wt(r),(e=>r[e].send("DOMContentLoaded")))})),u=()=>{hs&&i.log("content: load"),Kt(wt(r),(e=>r[e].send("load")))},"complete"==fn(ht.document)?u():Cn.addEventListener("load",(()=>u()),Dt({capture:!0,once:!0}))
;const p=(l.dom||[]).length+(l.js||[]).length+(l.raw||[]).length;hs&&i.log("content: "+(d||"normal")+" start event processing for "+s+" ("+p+" to run)"),Ms(a,"sync"===d),!Vn&&p&&fs(location.href),o()}else o();var u}))},Ms=(e,t)=>{const{bridges:n}=twod,{scripts:s,...r}=e;s.js&&rs(r,s.js,Fo,n.js,"js",t),s.dom&&(Kt(o,(e=>vt[e]=void 0)),rs(r,s.dom,cs,n.dom,"dom",t)),s.raw&&rs(r,s.raw,ls,n.raw,"raw",t)},xs=function(){var e=t((function*(){const{contextId:e}=twod,{location:t,document:o}=ht
;(yield Tn((e=>n((()=>e(o.body||o)))))).addEventListener("mouseenter",(()=>{$o.sendMessage(Dt({method:"contextmenu",url:t.href,id:e}),(()=>{}))}),!1)}));return function(){return e.apply(this,arguments)}}();let Ls;t((function*(){const{unsafeWindow:e,bridges:t}=twod,{location:n,document:o}=e,r=o instanceof XMLDocument;if(!Dt({"http:":!0,"https:":!0,"file:":!0})[e.location.protocol])return;Vn&&(ms(),Cn.addEventListener("pagehide",(e=>{wn(e)&&(ps=us)})))
;const i=twod.contextId?twod.contextId:twod.contextId=An();let c;const a=Dt({});Mt(twod.console,Gn),Tn((n=>{if(ko){const{createBridge:e}=Wo(i);o=(o,s)=>{Ls=c=o;const{modes:i}=s;i.js&&(t.js=e(),a.js=()=>!1,r&&(i.raw=!1)),n(s)},Jt(qo,o)}else Tn((t=>{Ls=c=e.pagejs,delete e.pagejs,Ls?t():(()=>{let e=n=>{delete ht.pagejs,e=void 0,(e=>{if(!e)throw"Error: pagejs missing. Please see http://tmnk.net/faq#Q208 for more information.";Ls=c=e,t()})(n)};xt(ht,"pagejs",Dt({set:e,configurable:!0})),Yn((()=>{
e&&e()}),1)})()})).then((()=>{n(Dt({modes:Dt({js:!1,raw:!0,dom:!0})}))}));var o})).then((({modes:{dom:o,raw:d},answer:l})=>{var u;if(Co(),l&&(u=l).scripts&&u.contexters&&(vt.tm_info=l),o){const e=ko?cs(`() => ${c};`)():c,{createBridge:n,inject:o}=((e,t)=>{const n=(e,t)=>{Kt(s,(n=>n(e,t)))},o=e=>Jt(r,Dt({listener:e,clone:e=>e})),s=[],r=[],i=(e,t)=>{Kt(r,(({listener:n,clone:o})=>n(e,o(t))))},c=e=>Jt(s,e),a="c"+An();let d;return Dt({createBridge:()=>(d=Ao(Dt({sendPrefix:"2S",listenPrefix:"2U",
send:i,onMessage:c})),d.init(e),d),inject:()=>(t(Dt({unsafeWindow:ht,unsafeThis:vt,pageWindow:ht.wrappedJSObject,contextId:a,fSend:n,fOnMessage:o})),d.sendToId(a,"commid",Dt({id:e})),!0)})})(i,e);a.dom=o,t.dom=n()}if(d){const{createBridge:e,inject:n}=((e,t)=>{let n;return Dt({createBridge:()=>(n=as(Dt({sendPrefix:"2P",listenPrefix:"2C",cloneInto:lo})),n),inject:()=>{n.init(e);let o=!1;const r=An(),i="("+tn(((e,t)=>{const n=window,o=t(n),s=n.parent,{O_dPy:r,cSO:i}=o;r(s,e,i({value:o,
enumerable:!1,writable:!1,configurable:!0}))}))+')("'+r+'", '+tn(s)+")";return n.once("ack",(()=>{o=!0})),(o=>{((e,t)=>{const n=jn(vn(ht.document,"*"),0)||ht.document,o=go("div"),s=o.attachShadow(Dt({mode:"closed"}));s.appendChild(go("style",":host { display: none }"));const r=go("iframe",Dt({sandbox:"allow-scripts allow-same-origin",style:"display: none",src:"javascript:void 0"}));let i=()=>{if(null===i)return;i=null;let n=!1;try{const t=r.contentDocument,o=r.contentWindow
;t&&o&&(n=ds(jn(t.getElementsByTagName("*"),0),e))}catch(e){}t(o,n),r.remove(),o.remove()};r.addEventListener("load",i,Dt({once:!0,capture:!0})),s.appendChild(r),n.appendChild(o),i&&i()})(o,((o,s)=>{ds(o,`(${t})({ unsafeWindow: typeof globalThis === "undefined" ? window : globalThis, unsafeThis: window, vault: ${s?`window["${r}"]`:"null"}, contextId: "${r}", __proto__: null });delete window["${r}"]\n`,0,(()=>{n.sendToId(r,"commid",Dt({id:e}))}),!0)}))})(i),o}})})(i,c);a.raw=n,t.raw=e()}
t.first=t.js||t.raw||t.dom,$o.onMessage.addListener(((o,s,r)=>{"executeScript"==o.method?(o.url&&0!==pn(n.href,o.url)||void 0!==o.topframe&&o.topframe!=Vn||Ms(o.info,!1),r(Dt({}))):Vn&&("loadUrl"==o.method?(e.location=o.url,r(Dt({}))):"reload"==o.method?(n.reload(),r(Dt({}))):"setForeignAttr"==o.method?(t.first.send(o.method,o),r(Dt({}))):Gn.log("content: unknown method "+Ft(o)))})),kn.onConnect.addListener(((e,t)=>{es.processConnect(e,t)})),es.init(),Kt(wt(t),(e=>{if("first"==e)return
;const n=t[e];n.setMessageListener(((t,o)=>{const{method:s,args:r}=t;if("port.message"==s)kn.message(r,n);else if("csp"==s){let t;t="raw"==e?ls:"dom"==e?cs:Fo,t(r.src,(e=>{e&&Gn.error(`Uncaught Error: ${e}`)}))}else if("external.message"==s)$o.sendMessage(Dt({method:"externalMessage",request:r}),(e=>{o(e)}));else if("console"==s){const e=r,t=jn(e,0),n=jn(e,1),o=Gn[t]||Gn.log;o&&Pt(o,Gn,((e,...t)=>{let n=e.length;const o=Dt(e);for(let e=0;e<t.length;e++){const s=t[e],r=Ot(s)?s:[s]
;for(let e=0;e<r.length;e++)o[n+e]=Ct(r,e);n+=r.length}return yt(o)})(["injected:"],(e=>{const t=[];return Kt(e,(e=>{Jt(t,(e=>"string"==typeof e?Bt(e):e)(e))})),t})(n)))}else es.processMessage(t,o)}))})),ys(a,r,(()=>Ls=void 0)),xs()}))}))()})();})({ __proto__: null, unsafeWindow: typeof globalThis === "undefined" ? window : globalThis, unsafeThis: window, }, "tm_wj5tmu")