// autogenerated
globalThis.extensionSettings = {
  "hmcUrl": "https://hub.hysolate.com",
  "absUrl": "https://hub.abs.perception-point.io",
  "enableDownloadLocalLogsBeforeLogin": true,
  "enableFactoryResetBeforeLogin": false,
  "excludedLogFields": [
    "favIconBase64",
    "screenshot",
    "favicon",
    "base64Data",
    "shellCodeDetectionPatterns"
  ]
};
