

let common_mimes = {
	"application": {
		"x-abiword": ["abw"],
		"x-7z-compressed": ["7z"],
		"vnd.lotus-1-2-3": ["123"],
		"x-ace-compressed": ["ace"],
		"postscript": ["ps", "ai", "eps"],
		"x-ms-application": ["application"],
		"vnd.android.package-archive": ["apk"],
		"x-msdownload": ["bat", "com", "dll", "exe", "msi"],
		"vnd.amazon.ebook": ["azw"],
		"octet-stream": ["bin", "bpk", "deploy", "dist", "distz", "dms", "dump", "elc", "lrf", "mar", "pkg", "so"],
		"x-bzip2": ["bz2", "boz"],
		"x-bzip": ["bz"],
		"vnd.ms-cab-compressed": ["cab"],
		"x-cbr": ["cbr", "cb7", "cba", "cbt", "cbz"],
		"x-debian-package": ["deb", "udeb"],
		"x-apple-diskimage": ["dmg"],
		"msword": ["doc", "dot"],
		"vnd.ms-word.document.macroenabled.12": ["docm"],
		"vnd.openxmlformats-officedocument.wordprocessingml.document": ["docx"],
		"vnd.ms-word.template.macroenabled.12": ["dotm"],
		"vnd.openxmlformats-officedocument.wordprocessingml.template": ["dotx"],
		"x-dvi": ["dvi"],
		"epub+zip": ["epub"],
		"x-iso9660-image": ["iso"],
		"json": ["json"],
		"jsonml+json": ["jsonml"],
		"java-archive": ["jar"],
		"x-java-jnlp-file": ["jnlp"],
		"javascript": ["js"],
		"x-latex": ["latex"],
		"vnd.lotus-wordpro": ["lwp"],
		"mathematica": ["ma", "mb", "nb"],
		"mathml+xml": ["mathml"],
		"x-msaccess": ["mdb"],
		"x-mobipocket-ebook": ["mobi", "prc"],
		"vnd.lotus-notes": ["nsf"],
		"oda": ["oda"],
		"vnd.oasis.opendocument.database": ["odb"],
		"vnd.oasis.opendocument.chart": ["odc"],
		"vnd.oasis.opendocument.formula": ["odf"],
		"vnd.oasis.opendocument.formula-template": ["odft"],
		"vnd.oasis.opendocument.graphics": ["odg"],
		"vnd.oasis.opendocument.image": ["odi"],
		"vnd.oasis.opendocument.text-master": ["odm"],
		"vnd.oasis.opendocument.presentation": ["odp"],
		"vnd.oasis.opendocument.spreadsheet": ["ods"],
		"vnd.oasis.opendocument.text": ["odt"],
		"vnd.openofficeorg.extension": ["oxt"],
		"vnd.oasis.opendocument.chart-template": ["otc"],
		"vnd.oasis.opendocument.graphics-template": ["otg"],
		"vnd.oasis.opendocument.text-web": ["oth"],
		"vnd.oasis.opendocument.image-template": ["oti"],
		"vnd.oasis.opendocument.presentation-template": ["otp"],
		"vnd.oasis.opendocument.spreadsheet-template": ["ots"],
		"vnd.oasis.opendocument.text-template": ["ott"],
		"vnd.ms-powerpoint": ["ppt", "pot", "pps"],
		"vnd.ms-powerpoint.template.macroenabled.12": ["potm"],
		"vnd.openxmlformats-officedocument.presentationml.template": ["potx"],
		"vnd.ms-powerpoint.addin.macroenabled.12": ["ppam"],
		"vnd.cups-ppd": ["ppd"],
		"vnd.ms-powerpoint.slideshow.macroenabled.12": ["ppsm"],
		"vnd.openxmlformats-officedocument.presentationml.slideshow": ["ppsx"],
		"vnd.ms-powerpoint.presentation.macroenabled.12": ["pptm"],
		"vnd.openxmlformats-officedocument.presentationml.presentation": ["pptx"],
		"x-rar-compressed": ["rar"],
		"rtf": ["rtf"],
		"x-tar": ["tar"],
		"x-tex": ["tex"],
		"x-bittorrent": ["torrent"],
		"xhtml+xml": ["xht", "xhtml"],
		"vnd.ms-excel": ["xls", "xla", "xlc", "xlm", "xlt", "xlw"],
		"vnd.ms-excel.addin.macroenabled.12": ["xlam"],
		"x-xliff+xml": ["xlf"],
		"vnd.ms-excel.sheet.binary.macroenabled.12": ["xlsb"],
		"vnd.ms-excel.sheet.macroenabled.12": ["xlsm"],
		"vnd.openxmlformats-officedocument.spreadsheetml.sheet": ["xlsx"],
		"vnd.ms-excel.template.macroenabled.12": ["xltm"],
		"vnd.openxmlformats-officedocument.spreadsheetml.template": ["xltx"],
		"xml": ["xml", "xsl"],
		"zip": ["zip"],
		"pdf": ["pdf"],
		"rsd+xml": ["rsd"],
		"rss+xml": ["rss"]
	},

	"text": {
		"vnd.in3d.3dml": ["3dml"],
		"cache-manifest": ["appcache"],
		"x-asm": ["asm", "s"],
		"x-c": ["cc", "cpp", "c", "cxx", "dic", "hh", "h"],
		"plain": ["txt", "conf", "def", "in", "list", "log", "text"],
		"css": ["css"],
		"csv": ["csv"],
		"vnd.curl": ["curl"],
		"vnd.curl.dcurl": ["dcurl"],
		"prs.lines.tag": ["dsc"],
		"x-setext": ["etx"],
		"x-fortran": ["f77", "f90", "for", "f"],
		"vnd.fmi.flexstor": ["flx"],
		"vnd.fly": ["fly"],
		"vnd.graphviz": ["gv"],
		"html": ["htm", "html"],
		"calendar": ["ics", "ifb"],
		"vnd.sun.j2me.app-descriptor": ["jad"],
		"x-java-source": ["java"],
		"troff": ["man", "me", "ms", "roff", "tr", "t"],
		"vnd.curl.mcurl": ["mcurl"],
		"n3": ["n3"],
		"x-nfo": ["nfo"],
		"x-opml": ["opml"],
		"x-pascal": ["pas", "p"],
		"richtext": ["rtx"],
		"vnd.curl.scurl": ["scurl"],
		"x-sfv": ["sfv"],
		"sgml": ["sgml", "sgm"],
		"vnd.in3d.spot": ["spot"],
		"vnd.dvb.subtitle": ["sub"],
		"tab-separated-values": ["tsv"],
		"turtle": ["ttl"],
		"uri-list": ["uris", "uri", "urls"],
		"x-uuencode": ["uu"],
		"vcard": ["vcard"],
		"x-vcard": ["vcf"],
		"x-vcalendar": ["vcs"],
		"vnd.wap.wmlscript": ["wmls"],
		"vnd.wap.wml": ["wml"]
	},
	"image": {
		"x-3ds": ["3ds"],
		"bmp": ["bmp"],
		"prs.btif": ["btif"],
		"cgm": ["cgm"],
		"x-cmx": ["cmx"],
		"vnd.djvu": ["djv", "djvu"],
		"vnd.dwg": ["dwg"],
		"vnd.dxf": ["dxf"],
		"vnd.fastbidsheet": ["fbs"],
		"x-freehand": ["fh4", "fh5", "fh7", "fhc", "fh"],
		"vnd.fpx": ["fpx"],
		"vnd.fst": ["fst"],
		"g3fax": ["g3"],
		"gif": ["gif"],
		"x-icon": ["ico"],
		"ief": ["ief"],
		"jpeg": ["jpg", "jpe", "jpeg"],
		"ktx": ["ktx"],
		"vnd.ms-modi": ["mdi"],
		"vnd.fujixerox.edmics-mmr": ["mmr"],
		"vnd.net-fpx": ["npx"],
		"x-portable-bitmap": ["pbm"],
		"x-pict": ["pct", "pic"],
		"x-pcx": ["pcx"],
		"x-portable-graymap": ["pgm"],
		"png": ["png"],
		"x-portable-anymap": ["pnm"],
		"x-portable-pixmap": ["ppm"],
		"vnd.adobe.photoshop": ["psd"],
		"x-cmu-raster": ["ras"],
		"x-rgb": ["rgb"],
		"vnd.fujixerox.edmics-rlc": ["rlc"],
		"sgi": ["sgi"],
		"x-mrsid-image": ["sid"],
		"vnd.dvb.subtitle": ["sub"],
		"svg+xml": ["svg", "svgz"],
		"x-tga": ["tga"],
		"tiff": ["tiff", "tif"],
		"vnd.dece.graphic": ["uvg", "uvi", "uvvg", "uvvi"],
		"vnd.wap.wbmp": ["wbmp"],
		"vnd.ms-photo": ["wdp"],
		"webp": ["webp"],
		"x-xbitmap": ["xbm"],
		"vnd.xiff": ["xif"],
		"x-xpixmap": ["xpm"],
		"x-xwindowdump": ["xwd"]
	},
	"video": {
		"3gpp2": ["3g2"],
		"3gpp": ["3gp"],
		"x-ms-asf": ["asf", "asx"],
		"x-msvideo": ["avi"],
		"vnd.dvb.file": ["dvb"],
		"x-f4v": ["f4v"],
		"x-fli": ["fli"],
		"x-flv": ["flv"],
		"vnd.fvt": ["fvt"],
		"h261": ["h261"],
		"h263": ["h263"],
		"h264": ["h264"],
		"jpm": ["jpgm", "jpm"],
		"jpeg": ["jpgv"],
		"mpeg": ["mpeg", "m1v", "m2v", "mpe", "mpg"],
		"vnd.mpegurl": ["m4u", "mxu"],
		"x-m4v": ["m4v"],
		"mj2": ["mj2", "mjp2"],
		"x-matroska": ["mkv", "mk3d", "mks"],
		"x-mng": ["mng"],
		"x-sgi-movie": ["movie"],
		"quicktime": ["mov", "qt"],
		"mp4": ["mp4", "mp4v", "mpg4"],
		"ogg": ["ogv"],
		"vnd.ms-playready.media.pyv": ["pyv"],
		"x-smv": ["smv"],
		"vnd.dece.hd": ["uvh", "uvvh"],
		"vnd.dece.mobile": ["uvm", "uvvm"],
		"vnd.dece.pd": ["uvp", "uvvp"],
		"vnd.dece.sd": ["uvs", "uvvs"],
		"vnd.uvvu.mp4": ["uvu", "uvvu"],
		"vnd.dece.video": ["uvv", "uvvv"],
		"vnd.vivo": ["viv"],
		"x-ms-vob": ["vob"],
		"webm": ["webm"],
		"x-ms-wm": ["wm"],
		"x-ms-wmv": ["wmv"],
		"x-ms-wmx": ["wmx"],
		"x-ms-wvx": ["wvx"]
	},
	"audio": {
		"x-aac": ["aac"],

		"x-aiff": ["aif", "aifc", "aiff"],
		"basic": ["au", "snd"],
		"x-caf": ["caf"],
		"vnd.dra": ["dra"],
		"vnd.dts": ["dts"],
		"vnd.dts.hd": ["dtshd"],
		"vnd.nuera.ecelp4800": ["ecelp4800"],
		"vnd.nuera.ecelp7470": ["ecelp7470"],
		"vnd.nuera.ecelp9600": ["ecelp9600"],
		"vnd.digital-winds": ["eol"],
		"x-flac": ["flac"],
		"midi": ["midi", "kar", "mid", "rmi"],
		"vnd.lucent.voice": ["lvp"],
		"mpeg": ["mp3", "m2a", "m3a", "mp2a", "mp2", "mpga"],
		"x-mpegurl": ["m3u"],
		"mp4": ["m4a", "mp4a"],
		"x-matroska": ["mka"],
		"ogg": ["ogg", "oga", "spx"],
		"vnd.ms-playready.media.pya": ["pya"],
		"x-pn-realaudio": ["ra", "ram"],
		"vnd.rip": ["rip"],
		"x-pn-realaudio-plugin": ["rmp"],
		"s3m": ["s3m"],
		"silk": ["sil"],
		"vnd.dece.audio": ["uva", "uvva"],
		"x-wav": ["wav"],
		"x-ms-wax": ["wax"],
		"webm": ["weba"],
		"x-ms-wma": ["wma"],
		"xm": ["xm"]
	},

	"font": {
		"otf": ["otf"],
		"collection": ["ttc"],
		"ttf": ["ttf"],
		"woff2": ["woff2"],
		"woff": ["woff"]
	}
};

var other_mimes = {
	"application": {
		"x-authorware-bin": ["aab", "u32", "vox", "x32"],
		"x-authorware-map": ["aam"],
		"x-authorware-seg": ["aas"],
		"pkix-attr-cert": ["ac"],
		"vnd.americandynamics.acc": ["acc"],
		"vnd.acucobol": ["acu"],
		"vnd.acucorp": ["acutc", "atc"],
		"vnd.audiograph": ["aep"],
		"x-font-type1": ["afm", "pfa", "pfb", "pfm"],
		"vnd.ibm.modcap": ["afp", "list3820", "listafp"],
		"vnd.ahead.space": ["ahead"],
		"vnd.adobe.air-application-installer-package+zip": ["air"],
		"vnd.dvb.ait": ["ait"],
		"vnd.amiga.ami": ["ami"],

		"vnd.lotus-approach": ["apr"],
		"x-freearc": ["arc"],
		"pgp-signature": ["asc", "sig"],
		"vnd.accpac.simply.aso": ["aso"],
		"atom+xml": ["atom"],
		"atomcat+xml": ["atomcat"],
		"atomsvc+xml": ["atomsvc"],
		"vnd.antix.game-component": ["atx"],
		"applixware": ["aw"],
		"vnd.airzip.filesecure.azf": ["azf"],
		"vnd.airzip.filesecure.azs": ["azs"],

		"x-bcpio": ["bcpio"],
		"x-font-bdf": ["bdf"],
		"vnd.syncml.dm+wbxml": ["bdm"],
		"vnd.realvnc.bed": ["bed"],
		"vnd.fujitsu.oasysprs": ["bh2"],
		"octet-stream": ["bin", "bpk", "deploy", "dist", "distz", "dms", "dump", "elc", "lrf", "mar", "pkg", "so"],
		"x-blorb": ["blb", "blorb"],
		"vnd.bmi": ["bmi"],
		"vnd.framemaker": ["book", "fm", "frame", "maker"],
		"vnd.previewsystems.box": ["box"],
		"vnd.cluetrust.cartomobile-config": ["c11amc"],
		"vnd.cluetrust.cartomobile-config-pkg": ["c11amz"],
		"vnd.clonk.c4group": ["c4d", "c4f", "c4g", "c4p", "c4u"],
		"vnd.tcpdump.pcap": ["cap", "dmp", "pcap"],
		"vnd.curl.car": ["car"],
		"vnd.ms-pki.seccat": ["cat"],
		"x-director": ["cct", "cst", "cxt", "dcr", "dir", "dxr", "fgd", "swa", "w3d"],
		"ccxml+xml": ["ccxml"],
		"vnd.contact.cmsg": ["cdbcmsg"],
		"x-netcdf": ["cdf", "nc"],
		"vnd.mediastation.cdkey": ["cdkey"],
		"cdmi-capability": ["cdmia"],
		"cdmi-container": ["cdmic"],
		"cdmi-domain": ["cdmid"],
		"cdmi-object": ["cdmio"],
		"cdmi-queue": ["cdmiq"],
		"vnd.chemdraw+xml": ["cdxml"],
		"vnd.cinderella": ["cdy"],
		"pkix-cert": ["cer"],
		"x-cfs-compressed": ["cfs"],
		"x-chat": ["chat"],

		"vnd.kde.kchart": ["chrt"],
		"vnd.anser-web-certificate-issue-initiation": ["cii"],
		"vnd.ms-artgalry": ["cil"],
		"vnd.claymore": ["cla"],

		"vnd.crick.clicker.keyboard": ["clkk"],
		"vnd.crick.clicker.palette": ["clkp"],
		"vnd.crick.clicker.template": ["clkt"],
		"vnd.crick.clicker.wordbank": ["clkw"],
		"vnd.crick.clicker": ["clkx"],
		"x-msclip": ["clp"],
		"vnd.cosmocaller": ["cmc"],
		"vnd.yellowriver-custom-menu": ["cmp"],
		"vnd.rim.cod": ["cod"],
		"x-cpio": ["cpio"],
		"mac-compactpro": ["cpt"],
		"x-mscardfile": ["crd"],
		"pkix-crl": ["crl"],

		"vnd.rig.cryptonote": ["cryptonote"],
		"x-csh": ["csh"],
		"vnd.commonspace": ["csp"],
		"cu-seeme": ["cu"],
		"prs.cww": ["cww"],
		"vnd.mobius.daf": ["daf"],
		"vnd.dart": ["dart"],
		"vnd.fdsn.seed": ["dataless", "seed"],
		"davmount+xml": ["davmount"],
		"docbook+xml": ["dbk"],
		"vnd.oma.dd2+xml": ["dd2"],
		"vnd.fujixerox.ddd": ["ddd"],
		"vnd.dreamfactory": ["dfac"],
		"x-dgc-compressed": ["dgc"],
		"vnd.mobius.dis": ["dis"],
		"vnd.dna": ["dna"],
		"vnd.osgi.dp": ["dp"],
		"vnd.dpgraph": ["dpg"],
		"dssc+der": ["dssc"],
		"x-dtbook+xml": ["dtb"],
		"xml-dtd": ["dtd"],
		"vnd.spotfire.dxp": ["dxp"],
		"ecmascript": ["ecma"],
		"vnd.novadigm.edm": ["edm"],
		"vnd.novadigm.edx": ["edx"],
		"vnd.picsel": ["efif"],
		"vnd.pg.osasli": ["ei6"],
		"x-msmetafile": ["emf", "emz", "wmf", "wmz"],
		"emma+xml": ["emma"],
		"vnd.ms-fontobject": ["eot"],
		"vnd.eszigno3+xml": ["es3", "et3"],
		"vnd.osgi.subsystem": ["esa"],
		"vnd.epson.esf": ["esf"],
		"x-eva": ["eva"],
		"x-envoy": ["evy"],
		"exi": ["exi"],
		"vnd.novadigm.ext": ["ext"],
		"vnd.ezpix-album": ["ez2"],
		"vnd.ezpix-package": ["ez3"],
		"andrew-inset": ["ez"],
		"vnd.adobe.formscentral.fcdt": ["fcdt"],
		"vnd.isac.fcs": ["fcs"],
		"vnd.fdf": ["fdf"],
		"vnd.denovo.fcselayout-link": ["fe_launch"],
		"vnd.fujitsu.oasysgp": ["fg5"],
		"x-xfig": ["fig"],
		"vnd.micrografx.flo": ["flo"],
		"vnd.kde.kivio": ["flw"],
		"vnd.frogans.fnc": ["fnc"],
		"vnd.fsc.weblaunch": ["fsc"],
		"vnd.fluxtime.clip": ["ftc"],
		"vnd.anser-web-funds-transfer-initiation": ["fti"],

		"vnd.fuzzysheet": ["fzs"],
		"vnd.geoplan": ["g2w"],
		"vnd.geospace": ["g3w"],
		"vnd.groove-account": ["gac"],
		"x-tads": ["gam"],
		"rpki-ghostbusters": ["gbr"],
		"x-gca-compressed": ["gca"],
		"vnd.dynageo": ["geo"],
		"vnd.geometry-explorer": ["gex", "gre"],
		"vnd.geogebra.file": ["ggb"],
		"vnd.geogebra.tool": ["ggt"],
		"vnd.groove-help": ["ghf"],
		"vnd.groove-identity-message": ["gim"],
		"gml+xml": ["gml"],
		"vnd.gmx": ["gmx"],
		"x-gnumeric": ["gnumeric"],
		"vnd.flographit": ["gph"],
		"gpx+xml": ["gpx"],
		"vnd.grafeq": ["gqf", "gqs"],
		"srgs": ["gram"],
		"x-gramps-xml": ["gramps"],
		"vnd.groove-injector": ["grv"],
		"srgs+xml": ["grxml"],
		"x-font-ghostscript": ["gsf"],
		"x-gtar": ["gtar"],
		"vnd.groove-tool-message": ["gtm"],
		"gxf": ["gxf"],
		"vnd.geonext": ["gxt"],
		"vnd.hal+xml": ["hal"],
		"vnd.hbci": ["hbci"],
		"x-hdf": ["hdf"],

		"vnd.hp-hpgl": ["hpgl"],
		"vnd.hp-hpid": ["hpid"],
		"vnd.hp-hps": ["hps"],
		"mac-binhex40": ["hqx"],
		"vnd.kenameaapp": ["htke"],
		"vnd.yamaha.hv-dic": ["hvd"],
		"vnd.yamaha.hv-voice": ["hvp"],
		"vnd.yamaha.hv-script": ["hvs"],
		"vnd.intergeo": ["i2g"],
		"vnd.iccprofile": ["icc", "icm"],
		"vnd.shana.informed.formdata": ["ifm"],
		"vnd.igloader": ["igl"],
		"vnd.insors.igm": ["igm"],
		"vnd.micrografx.igx": ["igx"],
		"vnd.shana.informed.interchange": ["iif"],
		"vnd.accpac.simply.imp": ["imp"],
		"vnd.ms-ims": ["ims"],
		"inkml+xml": ["ink", "inkml"],
		"x-install-instructions": ["install"],
		"vnd.astraea-software.iota": ["iota"],
		"ipfix": ["ipfix"],
		"vnd.shana.informed.package": ["ipk"],
		"vnd.ibm.rights-management": ["irm"],
		"vnd.irepository.package+xml": ["irp"],
		"vnd.shana.informed.formtemplate": ["itp"],
		"vnd.immervision-ivp": ["ivp"],
		"vnd.immervision-ivu": ["ivu"],
		"vnd.jam": ["jam"],

		"vnd.jisp": ["jisp"],
		"vnd.hp-jlyt": ["jlt"],

		"vnd.joost.joda-archive": ["joda"],

		"vnd.kde.karbon": ["karbon"],
		"vnd.kde.kformula": ["kfo"],
		"vnd.kidspiration": ["kia"],
		"vnd.google-earth.kml+xml": ["kml"],
		"vnd.google-earth.kmz": ["kmz"],
		"vnd.kinar": ["kne", "knp"],
		"vnd.kde.kontour": ["kon"],
		"vnd.kde.kpresenter": ["kpr", "kpt"],
		"vnd.ds-keypoint": ["kpxx"],
		"vnd.kde.kspread": ["ksp"],
		"vnd.kahootz": ["ktr", "ktz"],
		"vnd.kde.kword": ["kwd", "kwt"],
		"vnd.las.las+xml": ["lasxml"],
		"vnd.llamagraphics.life-balance.desktop": ["lbd"],
		"vnd.llamagraphics.life-balance.exchange+xml": ["lbe"],
		"vnd.hhe.lesson-player": ["les"],
		"x-lzh-compressed": ["lha", "lzh"],
		"vnd.route66.link66+xml": ["link66"],

		"lost+xml": ["lostxml"],
		"vnd.ms-lrm": ["lrm"],
		"vnd.frogans.ltf": ["ltf"],
		"vnd.lotus-wordpro": ["lwp"],
		"x-msmediaview": ["m13", "m14", "mvb"],
		"mp21": ["m21", "mp21"],
		"vnd.apple.mpegurl": ["m3u8"],
		"mads+xml": ["mads"],

		"vnd.mobius.mbk": ["mbk"],
		"mbox": ["mbox"],
		"vnd.medcalcdata": ["mc1"],
		"vnd.mcd": ["mcd"],

		"metalink4+xml": ["meta4"],
		"metalink+xml": ["metalink"],
		"mets+xml": ["mets"],
		"vnd.mfmp": ["mfm"],
		"rpki-manifest": ["mft"],
		"vnd.osgeo.mapguide.package": ["mgp"],
		"vnd.proteus.magazine": ["mgz"],
		"x-mie": ["mie"],
		"vnd.mif": ["mif"],
		"vnd.dolby.mlp": ["mlp"],
		"vnd.chipnuts.karaoke-mmd": ["mmd"],
		"vnd.smaf": ["mmf"],
		"x-msmoney": ["mny"],
		"mods+xml": ["mods"],
		"mp4": ["mp4s"],
		"vnd.mophun.certificate": ["mpc"],
		"vnd.apple.installer+xml": ["mpkg"],
		"vnd.blueice.multipass": ["mpm"],
		"vnd.mophun.application": ["mpn"],
		"vnd.ms-project": ["mpp", "mpt"],
		"vnd.ibm.minipay": ["mpy"],
		"vnd.mobius.mqy": ["mqy"],
		"marc": ["mrc"],
		"marcxml+xml": ["mrcx"],
		"mediaservercontrol+xml": ["mscml"],
		"vnd.fdsn.mseed": ["mseed"],
		"vnd.mseq": ["mseq"],
		"vnd.epson.msf": ["msf"],
		"vnd.mobius.msl": ["msl"],
		"vnd.muvee.style": ["msty"],
		"vnd.musician": ["mus"],
		"vnd.recordare.musicxml+xml": ["musicxml"],
		"vnd.mfer": ["mwf"],
		"mxf": ["mxf"],
		"vnd.recordare.musicxml": ["mxl"],
		"xv+xml": ["mxml", "xhvml", "xvm", "xvml"],
		"vnd.triscape.mxs": ["mxs"],
		"vnd.wolfram.player": ["nbp"],
		"x-dtbncx+xml": ["ncx"],
		"vnd.nokia.n-gage.symbian.install": ["gage"],
		"vnd.nokia.n-gage.data": ["ngdat"],
		"vnd.nitf": ["nitf", "ntf"],
		"vnd.neurolanguage.nlu": ["nlu"],
		"vnd.enliven": ["nml"],
		"vnd.noblenet-directory": ["nnd"],
		"vnd.noblenet-sealer": ["nns"],
		"vnd.noblenet-web": ["nnw"],
		"x-conference": ["nsc"],
		"x-nzb": ["nzb"],
		"vnd.fujitsu.oasys2": ["oa2"],
		"vnd.fujitsu.oasys3": ["oa3"],
		"vnd.fujitsu.oasys": ["oas"],
		"x-msbinder": ["obd"],
		"x-tgif": ["obj"],
		"ogg": ["ogx"],
		"omdoc+xml": ["omdoc"],
		"onenote": ["onepkg", "onetmp", "onetoc2", "onetoc"],
		"oebps-package+xml": ["opf"],
		"vnd.palm": ["oprc", "pdb", "pqa"],
		"vnd.lotus-organizer": ["org"],
		"vnd.yamaha.openscoreformat": ["osf"],
		"vnd.yamaha.openscoreformat.osfpvg+xml": ["osfpvg"],
		"oxps": ["oxps"],

		"pkcs10": ["p10"],
		"x-pkcs12": ["p12", "pfx"],
		"x-pkcs7-certificates": ["p7b", "spc"],
		"pkcs7-mime": ["p7c", "p7m"],
		"x-pkcs7-certreqresp": ["p7r"],
		"pkcs7-signature": ["p7s"],
		"pkcs8": ["p8"],
		"vnd.pawaafile": ["paw"],
		"vnd.powerbuilder6": ["pbd"],
		"x-font-pcf": ["pcf"],
		"vnd.hp-pcl": ["pcl"],
		"vnd.hp-pclxl": ["pclxl"],
		"vnd.curl.pcurl": ["pcurl"],
		"font-tdpfr": ["pfr"],
		"x-chess-pgn": ["pgn"],
		"pgp-encrypted": ["pgp"],
		"pkixcmp": ["pki"],
		"pkix-pkipath": ["pkipath"],
		"vnd.3gpp.pic-bw-large": ["plb"],
		"vnd.mobius.plc": ["plc"],
		"vnd.pocketlearn": ["plf"],
		"pls+xml": ["pls"],
		"vnd.ctc-posml": ["pml"],
		"vnd.macports.portpkg": ["portpkg"],
		"vnd.lotus-freelance": ["pre"],

		"vnd.3gpp.pic-bw-small": ["psb"],
		"x-font-linux-psf": ["psf"],
		"pskc+xml": ["pskcxml"],
		"vnd.pvi.ptid1": ["ptid"],
		"x-mspublisher": ["pub"],
		"vnd.3gpp.pic-bw-let": ["pvb"],
		"vnd.3m.post-it-notes": ["pwn"],
		"vnd.epson.quickanime": ["qam"],
		"vnd.intu.qbo": ["qbo"],
		"vnd.intu.qfx": ["qfx"],
		"vnd.publishare-delta-tree": ["qps"],
		"vnd.quark.quarkxpress": ["qwd", "qwt", "qxb", "qxd", "qxl", "qxt"],
		"vnd.ipunplugged.rcprofile": ["rcprofile"],
		"rdf+xml": ["rdf"],
		"vnd.data-vision.rdz": ["rdz"],
		"vnd.businessobjects": ["rep"],
		"x-dtbresource+xml": ["res"],
		"reginfo+xml": ["rif"],
		"x-research-info-systems": ["ris"],
		"resource-lists+xml": ["rl"],
		"resource-lists-diff+xml": ["rld"],
		"vnd.rn-realmedia": ["rm"],
		"vnd.jcp.javame.midlet-rms": ["rms"],
		"vnd.rn-realmedia-vbr": ["rmvb"],
		"relax-ng-compact-syntax": ["rnc"],
		"rpki-roa": ["roa"],
		"vnd.cloanto.rp9": ["rp9"],
		"vnd.nokia.radio-presets": ["rpss"],
		"vnd.nokia.radio-preset": ["rpst"],
		"sparql-query": ["rq"],
		"rls-services+xml": ["rs"],
		"vnd.yamaha.smaf-audio": ["saf"],
		"sbml+xml": ["sbml"],
		"vnd.ibm.secure-container": ["sc"],
		"x-msschedule": ["scd"],
		"vnd.lotus-screencam": ["scm"],
		"scvp-cv-request": ["scq"],
		"scvp-cv-response": ["scs"],
		"vnd.stardivision.draw": ["sda"],
		"vnd.stardivision.calc": ["sdc"],
		"vnd.stardivision.impress": ["sdd"],
		"vnd.solent.sdkm+xml": ["sdkd", "sdkm"],
		"sdp": ["sdp"],
		"vnd.stardivision.writer": ["sdw", "vor"],
		"vnd.seemail": ["see"],
		"vnd.sema": ["sema"],
		"vnd.semd": ["semd"],
		"vnd.semf": ["semf"],
		"java-serialized-object": ["ser"],
		"set-payment-initiation": ["setpay"],
		"set-registration-initiation": ["setreg"],
		"vnd.hydrostatix.sof-data": ["hdstx"],
		"vnd.spotfire.sfs": ["sfs"],
		"vnd.stardivision.writer-global": ["sgl"],
		"x-sh": ["sh"],
		"x-shar": ["shar"],
		"shf+xml": ["shf"],
		"vnd.symbian.install": ["sis", "sisx"],
		"x-stuffit": ["sit"],
		"x-stuffitx": ["sitx"],
		"vnd.koan": ["skd", "skm", "skp", "skt"],
		"vnd.ms-powerpoint.slide.macroenabled.12": ["sldm"],
		"vnd.openxmlformats-officedocument.presentationml.slide": ["sldx"],
		"vnd.epson.salt": ["slt"],
		"vnd.stepmania.stepchart": ["sm"],
		"vnd.stardivision.math": ["smf"],
		"smil+xml": ["smi", "smil"],
		"vnd.stepmania.package": ["smzip"],
		"x-font-snf": ["snf"],
		"vnd.yamaha.smaf-phrase": ["spf"],

		"scvp-vp-response": ["spp"],
		"scvp-vp-request": ["spq"],
		"x-sql": ["sql"],
		"x-wais-source": ["src"],
		"x-subrip": ["srt"],
		"sru+xml": ["sru"],
		"sparql-results+xml": ["srx"],
		"ssdl+xml": ["ssdl"],
		"vnd.kodak-descriptor": ["sse"],
		"vnd.epson.ssf": ["ssf"],
		"ssml+xml": ["ssml"],
		"vnd.sailingtracker.track": ["st"],
		"vnd.sun.xml.calc.template": ["stc"],
		"vnd.sun.xml.draw.template": ["std"],
		"vnd.wt.stf": ["stf"],
		"vnd.sun.xml.impress.template": ["sti"],
		"hyperstudio": ["stk"],
		"vnd.ms-pki.stl": ["stl"],
		"vnd.pg.format": ["str"],
		"vnd.sun.xml.writer.template": ["stw"],
		"vnd.sus-calendar": ["sus", "susp"],
		"x-sv4cpio": ["sv4cpio"],
		"x-sv4crc": ["sv4crc"],
		"vnd.dvb.service": ["svc"],
		"vnd.svd": ["svd"],

		"vnd.aristanetworks.swi": ["swi"],
		"vnd.sun.xml.calc": ["sxc"],
		"vnd.sun.xml.draw": ["sxd"],
		"vnd.sun.xml.writer.global": ["sxg"],
		"vnd.sun.xml.impress": ["sxi"],
		"vnd.sun.xml.math": ["sxm"],
		"vnd.sun.xml.writer": ["sxw"],
		"x-t3vm-image": ["t3"],
		"vnd.mynfc": ["taglet"],
		"vnd.tao.intent-module-archive": ["tao"],
		"vnd.3gpp2.tcap": ["tcap"],
		"x-tcl": ["tcl"],
		"vnd.smart.teacher": ["teacher"],
		"tei+xml": ["tei", "teicorpus"],
		"x-texinfo": ["texi", "texinfo"],
		"thraud+xml": ["tfi"],
		"x-tex-tfm": ["tfm"],
		"vnd.ms-officetheme": ["thmx"],
		"vnd.tmobile-livetv": ["tmo"],
		"vnd.groove-tool-template": ["tpl"],
		"vnd.trid.tpt": ["tpt"],
		"vnd.trueapp": ["tra"],
		"x-msterminal": ["trm"],
		"timestamped-data": ["tsd"],
		"vnd.simtech-mindmapper": ["twd", "twds"],
		"vnd.genomatix.tuxedo": ["txd"],
		"vnd.mobius.txf": ["txf"],
		"vnd.ufdl": ["ufd", "ufdl"],
		"x-glulx": ["ulx"],
		"vnd.umajin": ["umj"],
		"vnd.unity": ["unityweb"],
		"vnd.uoml+xml": ["uoml"],
		"x-ustar": ["ustar"],
		"vnd.uiq.theme": ["utz"],
		"vnd.dece.data": ["uvd", "uvf", "uvvd", "uvvf"],
		"vnd.dece.ttml+xml": ["uvt", "uvvt"],
		"vnd.dece.unspecified": ["uvvx", "uvx"],
		"vnd.dece.zip": ["uvvz", "uvz"],
		"x-cdlink": ["vcd"],
		"vnd.groove-vcard": ["vcg"],
		"vnd.vcx": ["vcx"],
		"vnd.visionary": ["vis"],

		"vnd.vsf": ["vsf"],
		"voicexml+xml": ["vxml"],
		"x-doom": ["wad"],
		"vnd.criticaltools.wbs+xml": ["wbs"],
		"vnd.wap.wbxml": ["wbxml"],
		"vnd.ms-works": ["wcm", "wdb", "wks", "wps"],
		"vnd.pmi.widget": ["wg"],
		"widget": ["wgt"],
		"x-ms-wmd": ["wmd"],
		"vnd.wap.wmlc": ["wmlc"],
		"vnd.wap.wmlscriptc": ["wmlsc"],
		"x-ms-wmz": ["wmz"],
		"vnd.wordperfect": ["wpd"],
		"vnd.ms-wpl": ["wpl"],
		"vnd.wqd": ["wqd"],
		"x-mswrite": ["wri"],
		"wsdl+xml": ["wsdl"],
		"wspolicy+xml": ["wspolicy"],
		"vnd.webturbo": ["wtb"],
		"xaml+xml": ["xaml"],
		"x-silverlight-app": ["xap"],
		"vnd.xara": ["xar"],

		"vnd.fujixerox.docuworks.binder": ["xbd"],
		"xcap-diff+xml": ["xdf"],
		"vnd.syncml.dm+xml": ["xdm"],
		"vnd.adobe.xdp+xml": ["xdp"],
		"dssc+xml": ["xdssc"],
		"vnd.fujixerox.docuworks": ["xdw"],
		"xenc+xml": ["xenc"],
		"patch-ops-error+xml": ["xer"],
		"vnd.adobe.xfdf": ["xfdf"],
		"vnd.xfdl": ["xfdl"],
		"vnd.olpc-sugar": ["xo"],
		"xop+xml": ["xop"],
		"x-xpinstall": ["xpi"],
		"xproc+xml": ["xpl"],
		"vnd.is-xpr": ["xpr"],
		"vnd.ms-xpsdocument": ["xps"],
		"vnd.intercon.formnet": ["xpw", "xpx"],
		"xslt+xml": ["xslt"],
		"vnd.syncml+xml": ["xsm"],
		"xspf+xml": ["xspf"],
		"vnd.mozilla.xul+xml": ["xul"],
		"x-xz": ["xz"],
		"yang": ["yang"],
		"yin+xml": ["yin"],
		"x-zmachine": ["z1", "z2", "z3", "z4", "z5", "z6", "z7", "z8"],
		"vnd.zzazz.deck+xml": ["zaz"],
		"vnd.zul": ["zir", "zirz"],
		"vnd.handheld-entertainment+xml": ["zmm"]
	},

	"chemical": {
		"x-cdx": ["cdx"],
		"x-cif": ["cif"],
		"x-cmdf": ["cmdf"],
		"x-cml": ["cml"],
		"x-csml": ["csml"],
		"x-xyz": ["xyz"]
	},
	"model": {
		"vnd.collada+xml": ["dae"],
		"vnd.dwf": ["dwf"],
		"vnd.gdl": ["gdl"],
		"vnd.gtw": ["gtw"],
		"iges": ["iges", "igs"],
		"mesh": ["mesh", "msh", "silo"],
		"vnd.mts": ["mts"],
		"vrml": ["vrml", "wrl"],
		"vnd.vtu": ["vtu"],
		"x3d+binary": ["x3db", "x3dbz"],
		"x3d+xml": ["x3d", "x3dz"],
		"x3d+vrml": ["x3dv", "x3dvz"]
	},
	"message": {
		"rfc822": ["eml", "mime"]
	}

};

var unsafe_mimes = ["application/x-ms-application", "application/vnd.android.package-archive", "application/x-msdownload", "application/vnd.ms-htmlhelp", "application/java-vm", "application/x-x509-ca-cert", "application/vnd.adobe.fxp", "application/winhlp", "application/java-archive", "application/x-java-jnlp-file", "application/javascript", "application/x-ms-shortcut", "application/x-msaccess", "application/vnd.openofficeorg.extension", "application/pics-rules", "application/vnd.ecowin.chart", "application/x-futuresplash", "application/x-shockwave-flash", "application/vnd.visio", "application/x-ms-xbap", "audio/adpcm"];

let officialErrors = ["FILE_FAILED", "FILE_ACCESS_DENIED", "FILE_NO_SPACE", "FILE_NAME_TOO_LONG", "FILE_TOO_LARGE", "FILE_VIRUS_INFECTED", "FILE_TRANSIENT_ERROR", "FILE_BLOCKED", "FILE_SECURITY_CHECK_FAILED", "FILE_TOO_SHORT", "NETWORK_FAILED", "NETWORK_TIMEOUT", "NETWORK_DISCONNECTED", "NETWORK_SERVER_DOWN", "NETWORK_INVALID_REQUEST", "SERVER_FAILED", "SERVER_NO_RANGE", "SERVER_BAD_CONTENT", "SERVER_UNAUTHORIZED", "SERVER_CERT_PROBLEM", "SERVER_FORBIDDEN", "USER_CANCELED", "USER_SHUTDOWN", "CRASH"];

var e2m = {};

function setExtToMimeDict() {
	let mains_1 = Object.keys(common_mimes);
	for (let main of mains_1) {
		let keys = Object.keys(common_mimes[main]);
		for (let key of keys) {
			let L = common_mimes[main][key];
			let mime = main + "/" + key;
			for (let ext of L) e2m[ext] = mime;
		}
	}

	let mains_2 = Object.keys(other_mimes);
	for (let main of mains_2) {
		let keys = Object.keys(other_mimes[main]);
		for (let key of keys) {
			let L = other_mimes[main][key];
			let mime = main + "/" + key;
			for (let ext of L) e2m[ext] = mime;
		}
	}
}

setExtToMimeDict();

